### ISSUE TITLE
Opbouw nieuws overzicht pagina

### ISSUE THREAD

**Issue by sanderpotjer** [stichtingsympathy/joomlacommunity.nl#10]
We hebben ontwerp/frontend nodig voor de nieuws pagina. Mag artikel afbeelding, titel, datum en categorie alleen zijn in bijv blokkenopbouw. Introtekst hoeft er niet per se bij 

http://nieuw.joomlacommunity.eu/nieuws

**Comment by n9iels** [comment]
@sanderpotjer Ik vond in de html map van de template een override die er wat mij betreft goed uit zag :)
Deze heb ik toegepast en wat integratie van Easy-discuss gedaan. Zie commit b1b1c43cc62d542aadbffc6532d1dc96313adb58

De geïntegreerde punten van Easy-Discuss:
- De getoonde avatar komt nu van het Easy-Discuss profiel van de schrijver
- De auteur wordt altijd getoond in de vorm van zijn echte naam en een link naar het Easy-discuss profiel

**Comment by conconnl** [comment]
@sanderpotjer wat is de status hiervan?
Als ik de pagina bekijk, lijkt het allemaal op orde te zijn.

**Comment by conconnl** [comment]
@sanderpotjer kun je een status update geven of dit issue sluiten.
