### ISSUE TITLE
[Development] - EasyDiscuss Avatar toevoegen aan RSComments

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#103]
@n9iels graag ook aan RSComments net zoals bij RSEvents de EasyDiscuss avatar koppeling toevoegen.
Als je dan zoals de vorige keer volledig beschrijft wat er aangepast is, zorg ik er weer voor dat RSJoomla het als standaard aan de extensie toevoegt.

![rscomments](https://cloud.githubusercontent.com/assets/11913918/17599274/9d53c86e-5ffe-11e6-9b3a-20e6d900622a.png)

**Comment by n9iels** [comment]
Feature is ingebouwd, ging een stukje soepeler dan met RSEvents :). Commit dat is bijgevoegd klopt in zijn geheel

**Comment by conconnl** [comment]
Hoi @n9iels RSComments! is tussendoor per ongeluk geupdate.
Nu is deze feature natuurlijk weg.
Kun je deze 10 september toevoegen en met mij dan direct de feature request schrijven voor RSJoomla!? Dan kunnen we dit gelijk in gang zetten bij ze.

**Comment by conconnl** [comment]
Tested successful.
Submitted a merge request to RSJoomla!
