### ISSUE TITLE
[Poll] Social share bij forumonderwerpen

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#104]
Het is mogelijk om bij elk forumonderwerp een aantal social share buttons te laten zien.  Dit zijn Twitter, LinkedIn, Google, Facebook, DIGG en Pingomatic.

Ik zelf vind het niet heel erg interessant om dit bij elk onderwerp mogelijk te maken maar misschien dat mensen hier wel gebruik van zullen willen maken. Dus hierbij de vraag wat jullie zelf van deze optie vinden, wellicht dat we de meerderheid van de stemmen als keuze kunnen aannemen. 

Voor een voorbeeld kan je [HIER KLIKKEN](http://nieuw.joomlacommunity.eu/forum/recent/weersgesteldheid). Je moet natuurlijk wel ingelogd zijn.

**Comment by SpiritJC** [comment]
Ik persoonlijk vin het behoorlijk druk en ik denk niet dat deze functie in een forum echt gebruikt word. Wat mij betreft is het niet nodig.

**Comment by conconnl** [comment]
+1 voor niet gebruiken.
Zoals Marco aangeeft, maakt het dit extra druk.
Ik verwacht ook niet dat mensen snel een forum bericht willen delen op social media.

**Comment by n9iels** [comment]
Volgensmij staat deze optie ondertussen uitgeschakeld en zijn we het er over eens dat het goed is. Lijkt me dat dit issue dan ook gesloten kan worden?

**Comment by conconnl** [comment]
Mee eens  
Deze kan wat mij betreft ook gesloten worden.

**Comment by n9iels** [comment]
Hierbij gesloten. Kan altijd heropend worden
