### ISSUE TITLE
[Structuur] Updaten forumregels

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#106]
Ik had al bij #23 al een opmerking gemaakt en Sander en Martijn getagd over het updaten van de forumregels maar het is eigenlijk een apart issue waard dus bij deze maak ik hem even aan.

Er is een [private Gist aangemaakt](https://gist.github.com/hvdmeer/78ab3218f413315c51687bea97511af1) met daarin de forumregels van het huidige forum. Hierin heb ik zelf al een aantal aanpassingen gemaakt, via Gist zijn deze aanpassingen mooi terug te vinden.

Hierbij het verzoek aan de personen die hier of voor verantwoordelijk zijn (via stichting sympathy?) of die een zinnige aanpassing/opmerking hebben om of een bewerking te maken (als dit kan, dit is mijn eerste Gist) of in deze issue de aanpassing/opmerking te plaatsen zodat er of over gediscussieerd kan worden of de aanpassing worden gemaakt.

De URL is: https://gist.github.com/hvdmeer/78ab3218f413315c51687bea97511af1

**Comment by sanderpotjer** [comment]
@hvdmeer ik denk dat dit voor nu verder goed is, @martijnmaandag heeft het in artikel geplaatst. Voor een volgende fase zou het mooi zijn als we de regels kunnen terugbrengen tot 1 half A4-tje ofzo met alleen echt de belangrijkste regels/richtlijnen. Dus wellicht wat minder specifiek alles benoemen.
