### ISSUE TITLE
Vertaling EasyDiscuss

### ISSUE THREAD

**Issue by MartijnMaandag** [stichtingsympathy/joomlacommunity.nl#107]
Hans en ik hebben inmiddels op Transifex alle zaken die in de Front-end verschijnen vertaald. De back-end heeft wat mij betreft minder belang en zal langzaam volgen.
Aangezien het verdere proces rond een vertaling in Transifex voor mij een beetje ondoorzichtig is (aproven, waarschijnlijk door Stackideas en uitleveren bij een volgende release) heb ik alles wat er nu is even gedownload en een installatiescript gemaakt. Dit heb ik op de site toegepast. Omdat ik begrijp dat dit nog op een andere manier via GitHub moet gebeuren en ik daar geen verstand van heb plaats ik het installatiescript hier ook nog even.

Verder: De vertaling is wat mij betreft nog niet af, aangezien er door verschillende mensen aan is gewerkt en sommige zaken ge='aproved' staan waar ik geen invloed op heb. Daarnaast is het in Transifex heel lastig om terug te vinden waar een 'gevonden fout' gebruikt wordt en te corrigeren. Ik heb de hele site daarom ook maar lokaal gehaald waardoor ik makkelijker kan zoeken en corrigeren (wat ik dan wel weer in Transifex zal doen).

Ik verzoek iedereen om taalfouten, ideeën welke termen we moeten gebruiken, typfouten, inconsistenties, enz enz door te geven.
Ik denk dat het handig is het in dit issue aan te geven.
Ik ben vanaf woensdag de rest van de week weg, maar zal het daarna weer oppakken.

[taalbestand-com_easydiscuss_408_nl.zip](https://github.com/stichtingsympathy/joomlacommunity.nl/files/417915/taalbestand-com_easydiscuss_408_nl.zip)

**Comment by n9iels** [comment]
Ik heb de bestanden toegevoegd aan GitHub :) Het idee is dat de website zowel live als lokaal draait. GitHub zorgt ervoor dat kan worden bijgehouden welke wijzigingen er worden gemaakt. We kunnen op deze manier ook een test versie en live versie maken. Vandaar dat dus in principe alles via GitHub moet gebeuren, om vervolgens door te worden gezet naar de live versie.

Over de vertaling, als ik zo snel kijk ziet het er prima uit! Goed werk!. Wellicht dat het een idee is om nog even te kijken naar de Badges die je als gebruiker kunt verdienen? Misschien dat we deze wat meer Joomla! gerelateerd kunnen maken?

**Comment by hvdmeer** [comment]
Dat is wel een goede eigenlijk. :scream:

**Comment by MartijnMaandag** [comment]
Goed idee van de badges @n9iels Ik denk dat we dat met een taaloverride moeten doen en niet in de vertaling van EasyDiscuss. Ik zal daar even over gaan nadenken en kom dan wel met een voorstel.
Staat er ergens beschreven hoe je met Github moet werken? Ik doe ondertussen zo vaak een beroep op anderen dat ik het zelf misschien ook maar eens moet leren ;-)

**Comment by hvdmeer** [comment]
Zal dit bij een update overschreven worden? Want als je een badge/onderscheiding opent krijg je gewoon een editorscherm waarbij je de badge kan kiezen, voor welke prestatie die is ingesteld en hoe die heet. Op een één of andere manier is dit zo opgesteld dat ik niet denk dat het overschreven kan worden. Maar als ik het mis heb. :wink: 

Overigens kunnen we ook eigen badges gebruiken, als iemand zin heeft om speciale Joomla! badges te regelen?

**Comment by n9iels** [comment]
@MartijnMaandag @hvdmeer alle wijzigingen die in de database worden gemaakt worden opgeslagen. Denk hierbij dus aan artikelen, menu items, instellingen (afgezien de Algemene instellingen) en dus ook EasyDicuss. Aangezien die badges de database staan kun je alles gewoon op de live site aanpassen.

En tja, van mijn ontwerp kunsten wordt je niet gelukkig haha. Weet niet of hier iemand rond dwaalt die goed is met ontwerpen?

**Comment by crommie** [comment]
Patrick Smits is daar heel goed in!

**Comment by conconnl** [comment]
Is de vertaling klaar?
Kan deze dus gesloten worden?

**Comment by hans2103** [comment]
@MartijnMaandag wat is de status hiervan?

**Comment by MartijnMaandag** [comment]
De front-end is vertaald en geïmplementeerd. De back-end nog niet, maar dat vind ik geen enkel probleem (desnoods zetten we de back-end op Engels) aangezien we dat zelf alleen zien.
Wat mij betreft dus afgehandeld.
