### ISSUE TITLE
[Layout] - Locatie naam op Locaties overzicht klikbaar maken

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#109]
Zorgen dat de locatie naam op de locaties overzicht klikbaar is en de pagina toont met de locatie informatie, i.p.v. evenement overzicht.
Op de Locatie informatie pagina een knop tonen waarmee de evenementen op te roepen zijn.

**Comment by hvdmeer** [comment]
Dat zou ik voor mijn eigen site ook graag willen @conconnl Als dit niet teruggekoppeld wordt met RSJoomla en standaard/mogelijk wordt, dan leen ik graag de aanpassing. :smile:

**Comment by conconnl** [comment]
Ik heb er puur een template override van gemaakt en niet een functie, dus kan het niet doorzetten naar RS. Het is opensource dus je mag alles kopiëren.

**Comment by jissereitsma** [comment]
Kan dit issue dan niet gewoon gesloten worden?

**Comment by conconnl** [comment]
Nee, moet nog een optie erin zien te bouwen.
Op deze pagina http://nieuw.joomlacommunity.eu/bijeenkomsten/locaties/locatie/3-s-hertogenbosch
Moet een mogelijkheid komen om naar de totaal overzicht van alle bijeenkomsten te gaan van die locatie.
Oftewel deze:
http://nieuw.joomlacommunity.eu/bijeenkomsten/joomla-gebruikersgroepen-jug/categorie/317-s-hertogenbosch

**Comment by sanderpotjer** [comment]
Ik vraag mij wel een beetje af in hoeverre een overzicht van locaties een toegevoegde waarde is. Ik denk eigenlijk dat het eerder verwarrend werkt met het overzicht van de categorieën (in veel gevallen gebruikersgroepen). 

Momenteel staat bij ieder event in de rechter zijkolom informatie over de locatie. Onder artikel komt automatisch de info over de locatie te staan als deze is ingevuld. Een doorklik naar een pagina van de locatie lijkt mij daarmee overbodig, of ik mis iets.

**Comment by conconnl** [comment]
Ik kan hier geen uitsluitsel overgeven. 
De verschillende pagina's voor de gebruikersgroepen en dus ook locaties zijn bedacht door de coördinator enige wat ik op verzoek deed was wat kleine tweaks. 

Mij maakt het zelf niet uit of er een locatie overzicht pagina aanwezig is. 
Als andere dit overkill vinden, kan deze lijk mij gewoon weggehaald worden. 
Nu de locatie aanklikbaar is en alle informatie van de locatie toont heb je al een locatie overzicht.

**Comment by sanderpotjer** [comment]
@Stitch123 kan jij aangeven of het locatie overzicht echt een must is? Of zoals het nu is al voldoet?

**Comment by Stitch123** [comment]
Hallo heren, ik heb even bewust niet alles gevolgd omdat er eerst overige punten uitgezocht moesten worden.  Ik laat het zsm weten!

**Comment by Stitch123** [comment]
Hallo @conconnl & @sanderpotjer 
Ik denk dat zoals het nu staat in het overzicht met de locaties met enige extra info, men door kan klikken naar alle info over die betreffende JUG voldoende is. Ik miste alleen eigenlijk het 'voorwoord' zoals zojuist gepost, met de uitleg over de werking van de JUG's.

**Comment by sanderpotjer** [comment]
Check, dan sluit ik deze.
