### ISSUE TITLE
[Informatie] - Afspraken & Besluiten / To-Do - Downloads

### ISSUE THREAD

**Issue by MartijnMaandag** [stichtingsympathy/joomlacommunity.nl#11]
Downloads wordt Taalpakketten..
We leveren geen extensies meer.
Vertalingen wordt in tweeën gesplitst, Joomla core en Extensies.
Bij de core wordt verwezen naar .org en naar lokaal (voor de voorbeelddata). Naast NL wordt ook BE geleverd.
Bij extensies kan op twee manieren verwezen worden.
1. Naar een externe locatie waar één of meer vertalingen staan. (per extensiebouwer). (URL + beheerder + beschrijving)
2. Naar lokale map waar vertaling staat. (iemand kan vertaling uploaden en beheren +beschrijving)

Mogelijkheid om tags toe te kennen, zodat naar inzicht overzichten kunnen worden gemaakt.
Zoeken.

**Comment by sanderpotjer** [comment]
Sluit dit issue. Eventuele aanpassingen/issues voor downloads graag in separate issues
