### ISSUE TITLE
[Fase 1] - [Form] PHP error in gebruikers overzicht

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#110]
Het gebruikersoverzicht op het form (http://nieuw.joomlacommunity.eu/forum/recent/users) geeft momenteel de PHP error:
```
0 - Call to undefined method JPagination::getPageNumber()
```
Vraag me niet waar dit precies aan ligt.. Wie heeft oorspronkelijk EasyDiscuss geïnstalleerd en heeft toegang tot de download en licentie? Ik vermoed namelijk dat het fout gaat omdat het op de live website wordt geïnstalleerd en/of geüpdate.

Mijn voorstel is om EasyDisucus nu lokaal goed te installeren en deze vervolgens correct op GitHub te zetten. Dan zouden de problemen lijkt mij opgelost moeten zijn. Dus wie o wie heeft de licentie....

**Comment by hvdmeer** [comment]
@sanderpotjer heeft sowieso de licentie (API key), maar ik kan ook inloggen bij Stackideas en kan de licentie zien. Maar als je naar EasyDiscuss - Instellingen gaat en daar kiest voor Advanced dan zie je de API key ook staan. :wink:  

Ze hebben een launcher package (voor average users) en een Component, Full -packet die beide voor advanced users bedoeld zijn. Welke wil je hebben @n9iels ?

**Comment by hvdmeer** [comment]
Oh, er is gisteren/vannacht een nieuwe versie uitgebracht.

**Comment by n9iels** [comment]
Graag de versie die momenteel geïnstalleerd staat op de website :)

**Comment by hvdmeer** [comment]
Die kan je in #91 vinden.

**Comment by MartijnMaandag** [comment]
Ik heb even gezocht bij Stackedeas. Hier staat een vraag http://stackideas.com/forums/fatal-error-users
De daar geleverde user.php lost het probleem bij mij lokaal op.

**Comment by hvdmeer** [comment]
Vreemd gedrag op deze pagina. De foutmelding is er niet meer bij mij, ik zie een lijst met gebruikers.
Wanneer ik ga zoeken werkt het alleen niet en ik krijg nu met geen mogelijkheid meer die eerste pagina met gebruikersnamen weer tevoorschijn.

**Comment by MartijnMaandag** [comment]
Als ik zoek krijg ik gewoon de personen te zien die voldoen aan het criterium. Daarna met een leeg zoekveld nogmaals zoeken en ik krijg weer alle gebruikers.

**Comment by hvdmeer** [comment]
Ik heb me even uitgelogd, een ctrl-F5 gedaan, weer ingelogd en toen kon ik inderdaad iemand zoeken. Maar als ik daarna of op Leden of Gebruikers klik blijf ik onderstaand overzicht houden:
![forumzoeken](https://cloud.githubusercontent.com/assets/7062995/18086567/ded9c9da-6eb0-11e6-869f-0aca9fe92f3c.png)

**Comment by MartijnMaandag** [comment]
Wat ik nu heb ondervonden: In Firefox en Chrome werkt het goed.
In Edge blijft het oude zoekresultaat staan en kun je het veld dus niet schoonmaken. Welke Browser heb jij gebruikt?

**Comment by hvdmeer** [comment]
Chrome 52.0. Het lijkt goed te gaan wanneer ik na het zoeken de string verwijder en dan opnieuw op zoeken klik. Als ik de leden/gebruikers knop gebruik dan gaat het niet goed hier.

**Comment by MartijnMaandag** [comment]
Ik ga wel een vraag stellen bij StackIdeas.

**Comment by MartijnMaandag** [comment]
Heb van StackIdeas de volgende bug-fix gekregen; default.js vervangen in
components\com_easydiscuss\themes\wireframe\users\default.js
Dat hier gedaan en het werkt nu volgens mij goed.
Misschien kan een van de coders het volgens de officiële weg installeren?
@hvdmeer Ik ben vanaf nu ruim drie weken weg. Ik heb bij StackIdeas in het forum aangegeven dat het is opgelost, maar gezien de tijdsverschillen kunnen ze misschien nog reageren. Ik kan daar niet op terug komen. Ik geloof dat jij daar ook toegang hebt.
Dit is de link: http://stackideas.com/forums/search-filter-on-member-list-does-not-work-correct-in-edge-browser


[default.zip](https://github.com/stichtingsympathy/joomlacommunity.nl/files/447703/default.zip)

**Comment by n9iels** [comment]
Ik heb het bestand vervangen. Hopen dat EasyDiscuss binnenkort een update uitbrengt met deze fixes :)

**Comment by jissereitsma** [comment]
Als het bestand is vervangen, en de PHP error is weg, dan kan dit ticket volgens mij toch gesloten worden? Bij mij doet het het prima.

**Comment by conconnl** [comment]
Lijkt er wel op.
Wordt gesloten, heropenen kan altijd nog.
