### ISSUE TITLE
[Development] rs_events - img niet responsive

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomlacommunity.nl#111]
De afbeelding in de description van RS Events steekt uit buiten zijn voegen. 
Het is niet responsive. 

<img width="1056" alt="schermafdruk 2016-08-22 12 26 33" src="https://cloud.githubusercontent.com/assets/639822/17851705/bca7e138-6863-11e6-8d00-0b7f7d8e3490.png">

**Comment by conconnl** [comment]
Die pagina moet ik nog doen, dus dit zal ik meenemen als ik hiermee aan de slag ga. 
Ben vanmiddag net geland in Turkije, zit twee hier, maar zal wel aan het knutselen zijn. Anders ben ik bij terugkomst nog een week vrij.

**Comment by n9iels** [comment]
@conconnl Fijne vakantie! :)

**Comment by jissereitsma** [comment]
Als ik het goed zie, is de image nu wel responsive en kan dit issue gesloten worden?

**Comment by n9iels** [comment]
Ik heb dit probleem opgelost door in de locaties alle fixed `height` en `width` weg te halen. Ook heb ik aan elke afbeelding `class="img-responsive"` toegevoegd.  Ze blijven nu netjes binnen de viewpoort.
![image](https://cloud.githubusercontent.com/assets/2659866/20465286/2242bb70-af5a-11e6-850a-36c8600b9fad.png)
