### ISSUE TITLE
[Layout] Styling Forumoverzicht als Recent

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#112]
Als je via het menu item op het forum uitkomt dan zie je recente berichten. Kies je dan voor om naar de categorieën te gaan dan ziet de styling er ineens anders uit.
Ik zou graag zien dat de categorieënoverzicht de zelfde styling heeft als die van de recente items. Screenshots hieronder. 

Ik ben zelf niet zo'n held met styling, dus als iemand hierbij kan helpen.

Recent
![jc-recent](https://cloud.githubusercontent.com/assets/7062995/18085522/cec1587e-6eab-11e6-9e1a-e997f6112522.png)

Categorieën
![jc-forum](https://cloud.githubusercontent.com/assets/7062995/18085537/d930a526-6eab-11e6-9ae1-e88d18cb30f2.png)

**Comment by sanderpotjer** [comment]
@hvdmeer ik heb het forum qua layout wat meer gelijk getrokken als de rest van de site. Ook de 11px en 12px groter gemaakt. Kan jij even kijken of het zo in grote lijnen naar wens is en er geen grote show-stoppers voor nu zijn? Kunnen uiteraard ook na livegang blijven verbeteren, als boel maar werkt nu.
