### ISSUE TITLE
[Fase 1] - [Layout] mobiel comment input buiten viewport

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomlacommunity.nl#114]
Op mobiel vallen de inputvelden van de comment tool buiten de viewport. Ze horen binnen de viewport te blijven.

![](http://i.imgur.com/sxPJ09Y.jpg)

**Comment by conconnl** [comment]
De breedte is keihard gedefinieerd in de view.
Zal deze met een override eruit halen.

**Comment by conconnl** [comment]
Aangezien naast deze velden ook de Buttons, ReCAPTCHA v2, reactie veld en andere punten iets beter kunnen bekijk ik het hele stuk, maak ik verbeteringen waar ik denk dat dit nodig is.
Natuurlijk mag altijd iemand anders daarna nog kijken of zelfs ombouwen naar volledig Bootstrap.

**Comment by conconnl** [comment]
Update:

Ik ben tot de conclusie gekomen dat RSComments! bootstrap gebruikt om alles mooi te maken op verschillende viewports.
In de Configuratie kun je kiezen om deze zaken te laden, dit stond niet aan.
Ik ging er automatisch vanuit dat de correcte Bootstrap versie al geladen werd.
<img width="453" alt="screen shot 2016-09-04 at 15 02 38" src="https://cloud.githubusercontent.com/assets/11913918/18231145/d0b8f85e-72b0-11e6-8587-6c77d29de80c.png">

Er moet dus geoordeeld worden of deze opties aan moeten, of dat de het op een andere manier geladen dient te worden. Of wellicht zelfs de views aangepast dienen te worden.
**JQuery**
Als JQuery frontend niet geladen wordt, werken sommige opties niet zoals het openen en sluiten van het reactieformulier (wellicht andere)
> Ik denk dat we hier geen keuze hebben
**Bootstrap**
Als Bootstrap niet geladen worden ziet het reactieformulier op mobiel er sowieso niet uit, maar op Desktop en tablet ook niet super.
_Geen Bootstrap_
<img width="628" alt="screen shot 2016-09-04 at 15 06 58" src="https://cloud.githubusercontent.com/assets/11913918/18231167/4c790ae2-72b1-11e6-8f68-945c37ab0ad6.png">
_Wel Bootstrap_
<img width="615" alt="screen shot 2016-09-04 at 15 15 57" src="https://cloud.githubusercontent.com/assets/11913918/18231202/871a8c06-72b2-11e6-8a0a-7f282530aac8.png">
> Hier een aparte issue voor aanmaken? (Bootstrap anders inladen)

**FontAwesome**
Doordat RSEvents deze ook al laad maakt het geen verschil uit in RSComments op de betreffende pagina's. Waarschijnlijk wel op andere pagina's.
Ik zou verwachten dat deze door de site zelf ingeladen wordt, aangezien je dit dan ook kunt gebruiken in Joomla Artikelen. Dan kunnen we het laden bij RSEvents ook uitschakelen.

> Hier een aparte issue voor aanmaken?

**Comment by n9iels** [comment]
De versie die ie inlaad is BS2. Ik heb al wat dingen gedaan waardoor die met BS3 compatibele is. Staat een template overridd voor en less bestand.
Dus Bootstrap NIET inladen anders krijg je conflicten.

Fontawesome hebben we niet. Wel een eigen icon set. Puur om laattijd en extra troep te besparen.

Jquery ook niet inladen. Krijg je ook conflicten van plus useless jquery files. Beter maar 1x inladen via de template

**Comment by conconnl** [comment]
Hoi Niels,

Als je iets gedaan hebt om BS2 compatibel te maken met BS3, dan is dit stuk nog niet compleet.
Als we bootstrap niet laden via RSComments, moeten we alles met de hand stijlen om het fatsoenlijk te krijgen.

> Ga je hier verbeteringen voor aanbrengen?

Blijkbaar wordt JQuery nu niet ingeladen in de template, RSComments werkt niet als je JQuery laden uitschakelt in de instellingen.
Dan zou het 1x inladen via de template nog gebouwd moeten worden.

> Ga je dit dan bouwen?

Ik snap niet wat je bedoel met extra troep besparen als je het over FontAwesome hebt, kun je hier meer uitleg over geven?

**Comment by n9iels** [comment]
Font awesome heeft zo een 400 icons. Die gebruikt je niet allemaal. Bootstrap heeft ook zijn eigen set, en onze template ook. Das wel heel veel :)

De template laat atm al jQuery in. Dus wass instaat er een conclict. Zou ik even naar moeten kijken.Zelfde geld voor Bootstrap.

Zal kijken of ik morgen tijd heb

**Comment by conconnl** [comment]
@n9iels ik ga het nog vreemder maken.
Bij mij "Lokaal" werkt de verberg reactieformulier wel, met alle opties qua zaken inladen wel.
Op de live site werkt het niet.
Ik heb net een nieuwe download gedaan van de GIT repository.

Dus of de data op de server is niet up to dat of er is iets anders mis.

**Comment by n9iels** [comment]
Hmmm laat me even kijken of de live site.

**Comment by sanderpotjer** [comment]
Als het even kan zou het mooi zijn als er überhaupt geen Bootstrap 2 JS/CSS wordt geladen, want wel erg zonde als zowel BS 2 en BS 3 op pagina's wordt geladen. Dan kunnen we beter template overrides maken zodat de layout er via Bootstrap 3 vanuit template ook gewoon goed uitziet.

Kortom, we moeten er eigenlijk voor zorgen dat RSComments gewoon werkt als in de backend alle opties voor laden CSS/JS op "Nee" staan.

**Comment by conconnl** [comment]
@sanderpotjer 
Was het maar alleen RSComments, het gaat dus om elke RS Extensie en wellicht andere die we gebruiken.
Als iemand tijd heeft om overal de correcte override voor te maken is het geen probleem om zoiets voor elkaar te krijgen.

Ik ga het straks eens proberen.

**Comment by conconnl** [comment]
Alles is uitgevoerd.
De bootstrap, JQeury en Font Awesome inlaad instellingen zijn aangepast naar "Nee"
