### ISSUE TITLE
[Fase 1] - [Layout] mobiel padding-top footer

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomlacommunity.nl#116]
Op mobiel kleeft de footer tekst tegen de border. Kan de tekst los gemaakt worden van de top?

![](http://i.imgur.com/V9c0POH.jpg)

**Comment by n9iels** [comment]
Ik heb was padding toegevoegd

![image](https://cloud.githubusercontent.com/assets/2659866/18257386/2ff70172-73c3-11e6-9f65-e3243fbee315.png)

**Comment by pe7er** [comment]
Ik zie hier geen pull request voor. Hoe kan ik dit testen?

**Comment by jissereitsma** [comment]
Niet gemakkelijk om te testen: Je moet eerst Gulp of PhpStorm gebruiken om `template.less` te compileren naar CSS.

**Comment by pe7er** [comment]
En dit is al toegevoegd aan de core code ipv als PR?

**Comment by hans2103** [comment]
SUccesvol getest. Er is nu een mooie ruimte tussen de balk en de tekst.
