### ISSUE TITLE
[Structuur] Menu items controleren

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#118]
Ik was net even aan het zoeken naar de omschrijving van de JUG's en zag nadat ik alle menu items had opgevraagd dat er gedeactiveerde, of niet interessante menu items aanwezig zijn.

Om schoon te beginnen is het handig om een opschoning te maken in welke items verwijderd kunnen worden uit de verschillende menu's.

**Comment by hans2103** [comment]
er zijn momenteel geen gedepubliceerde menu items te zien in Joomla backend bij "Alle menu items". Wel staan er een aantal bij "verplaatst naar prullenbak".

De prullenbak kan geleegd worden bij livegang van website. 
Dit issue kan gesloten worden.
