### ISSUE TITLE
[Structuur] Menu item "Overige bijeenkomsten"

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#119]
Bij het nakijken van een paar menu items viel het me op dat er een menu item "Overige bijeenkomsten" aanwezig is bij het hoofdmenu item "Bijeenkomsten"

In dit menu item zijn aanwezig, "Joomla! Extension Meetings" en "Joomladagen". 

Nu zijn de "Joomla! Extension Meetings" één keer georganiseerd en zijn de Joomladagen maar één keer per jaar. Is het nodig om hiervoor een apart menu item te gaan gebruiken? 

Het lijkt mij dat een uniek menu item wordt gebruikt voor zaken die regelmatig terugkeren. Deze issue os dus meer bedoeld om te beoordelen of dit menu item aanwezig moet zijn of dat de evenementen beter ergens anders onder passen. 
Overige bijeenkomsten zegt natuurlijk ook niet zoveelVoorbeeld; De Joomladagen heeft een eigen website en de frontpage berichten op Joomlacommunity gaan volgens mij goed. Aanmeldingen gaan via de werkwijze van de Joomladagen en niet via RSEvents. Dis waarom opnemen?

**Comment by conconnl** [comment]
Hoi Hans,
Je hebt helemaal gelijk.
Nu ook de hoofd titel is verandert en dus de doel van de totale informatie aangepast is, moet deze structuur ook anders.

Ik denk wel dat we een kopje "Overige" moeten behouden i.p.v. "Overige bijeenkomsten"
Deze koppelen aan een artikel met informatie over bijeenkomsten die ook weleens plaatsvinden, waarbij je kunt linken naar de betreffende website of pagina.
Dan is het wel altijd duidelijk dat er nog meer gebeurt door het jaar heen dan alleen maar de paar die duidelijk aangegeven staan.

Ik voer direct een paar aanpassingen door.
