### ISSUE TITLE
[Informatie] - Afspraken & Besluiten / To-Do - Nieuws

### ISSUE THREAD

**Issue by superknutsel** [stichtingsympathy/joomlacommunity.nl#12]
Nieuws categorievoorstel :

- Algemeen
- Versies (was Releases, eventueel samenvoegen met Extensies en misschien een filteroptie / tags?)
- Extensies wel of niet afhankelijk van de invulling van het "Versies" menu-item
- Evenementen
- Gebruikersgroepen
- Over JoomlaCommunity.nl misschien veranderen i.p.v. JoomlaCommunity ?
- Toekomstplannen/lopende Projecten ?

-- In Nederland lijkt wat overbodig omdat de site al een heel Nederlands karakter heeft. Veel artikelen kunnen beter geplaatst worden in Algemeen of Evenementen.

Misschien met Tags nog iets leuks doen om toch wat flexibeler te zijn qua onderwerpen/trefwoorden?

**Comment by n9iels** [comment]
Ik heb je voorstel voor de categorieën verwerkt. Deze categorieën heb ik aangemaakt door of bestaande categorieën van naam te wijzigen, of een totaal nieuwe categorie aan te maken. Verder heb ik alle andere categorieën onder nieuws gedepubliceerd.

Ow en omdat ik toch bezig was heb ik ook alle nieuwsberichten van 2004 t/m 2011 in het archief gezet. Dat ruimt toch wel een beetje op :)
Wat we daarmee doen moeten we later maar bepalen, het staat ten slotte niet in de weg
