### ISSUE TITLE
[Tekst] - Beschrijving PBF bijeenkomsten pagina

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#120]
Op de PBF bijeenkomsten pagina een beschrijving maken over deze bijeenkomsten, zodat de pagina niet leeg is als er geen geplande bijeenkomst is.

http://nieuw.joomlacommunity.eu/bijeenkomsten/pizza-bugs-fun-pbf

**Comment by hvdmeer** [comment]
Ik heb de algemene beschrijving van de huidige website gekopieerd en in de categoriebeschrijving geplakt en lichtelijk bewerkt. 
Als dit voldoende zo is kan deze issue gesloten worden.

**Comment by conconnl** [comment]
Dankjewel
