### ISSUE TITLE
[Fase 1] - [Layout] - Tablet Bottom module view niet correct

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#124]
<img width="449" alt="screen shot 2016-09-03 at 15 42 29" src="https://cloud.githubusercontent.com/assets/11913918/18224872/1e59eba0-71ed-11e6-9c44-af159134be81.png">

Bij tablet formaat gaat het niet lekker met Taalpakketten en Aan de slag

**Comment by RemcoJanssen** [comment]
Ga ik mee aan de slag!

**Comment by RemcoJanssen** [comment]
Pull Request ingediend

**Comment by conconnl** [comment]
#143 Merged
