### ISSUE TITLE
[Layout] - Stijlguide Icons (i.p.v. Font Awesome)

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#125]
Aangezien de JC template eigen Iconen blijkt te hebben is het gewenst om de coderingen hiervan te weten, zodat we alle reeds aangepast views, maar ook bestaande views van Extensies kunnen overschrijven.
Dan hoeven we Font Awesome niet meer in te laden.

**Comment by n9iels** [comment]
Ik heb even wat bekeken. De icons set in de template is een hele kleine samengestelde set. Het gaat voornamelijk om bepaalde icons die niet bij elkaar in één set zitten. Ook zijn deze gebruikt om BS2 icons te vervangen denk ik.

Ik stel voor om te kijken hoe ver we komen met de standaard icons set van Bootstrap 3 (http://getbootstrap.com/components/#glyphicons). Als deze niet voldoet kunnen we ook altijd nog font-awesome inladen ipv deze.

**Comment by n9iels** [comment]
FontAwesome is nu geïnstalleerd, Glyphicon wordt niet meer ingeladen. De set van de template nog wel, zo kunnen we garanderen dat bepaalde icons zichtbaar blijven.

FontAwesome is toegevoegd met deze commit a1d9c8f52721b63f3f9ac8d4645c227f92592b19
