### ISSUE TITLE
[ACL] Rechten voor teams

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#128]
Alle rechten voor de "Teams" gebruikersgroepen zijn nu ingesteld.

**JUG**
Elke gebruikersgroep die onder de "Gebruikersgroepen" gebruikersgroep valt (Utrecht, Rotterdam, Amsterdam etc.) heeft toegang tot haar eigen com_content categorie voor verslagen. Ook heeft deze groep toegang tot haar EasyDiscuss categorie om events te plaatsen

**Nieuws**
De gebruikersgroep "Nieuws" heeft volledige rechten binnen de Nieuws categorie en alle categorieën daaronder

**Algemeen auteur**
De gebruikersgroep "Algemeen Auteur" Heeft volledige rechten over het artikel beheer voor alle categorieën.

**Geregistreerd**
De gebruikersgroep "Geregistreerd" kan inloggen op de front-end. **Elke gebruiker moet naast zijn toegangsniveau altijd geregistreerd zijn**

**Preview**
Deze groep is gemaakt voor testers van de nieuw site. Hiermee kan offline worden ingelogd en is toegang tot de back-end met Akeeba Backup. Op deze manier kan iedereen zijn eigen test site maken indien nodig.

**Comment by slibbe** [comment]
Hmm, ik kan er niet een evenement bij maken. Dus de toegang tot EasyDiscuss moet nog?

**Comment by conconnl** [comment]
Bedoel je een bericht op EasyDiscuss of een evenement op Bijeenkomsten pagina?

**Comment by hvdmeer** [comment]
Je was "alleen" Super User, ik heb je ook bij de Amsterdam / Weesp toegevoegd.

**Comment by conconnl** [comment]
Viewing Access Levels "Fase2" toegevoegd aan de site.
Om makkelijk delen die we naar Fase2 verschuiven te verbergen op de site voor bezoekers, maar ook direct geen verwarring te veroorzaken met andere Access Levels.
