### ISSUE TITLE
[RSComments] plaatsen comment mislukt

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomlacommunity.nl#129]
Ondanks het aangevinkte knopje "ik ga akkoord met de voorwaarden", kan ik geen comments plaatsen. Ik krijg de error dat ik akkoord moet gaan met de voorwarden.
![schermafdruk 2016-09-05 22 46 47](https://cloud.githubusercontent.com/assets/639822/18256823/b8974bb2-73ba-11e6-8dd9-8a95a4b64517.png)

**Comment by conconnl** [comment]
Alle opties staan aan om te design-en niet om te testen.

Als alles ingesteld is, kunnen we het testen.
Als we dan issues tegenkomen, kan ik het laten fixen.
Net als dat die PHP foutmelding, zojuist heb laten fixen door RSJoomla

Ieder geval bedankt voor het melden.

**Comment by hvdmeer** [comment]
@conconnl @hans2103 Heeft dit te maken met deze melding?

> <b>Deprecated</b>:  Methods with the same name as their class will not be constructors in a future version of PHP; JSecurImageColor has a deprecated constructor in <b>/home/users/jooomftp/nieuw.joomlacommunity.eu/components/com_rscomments/helpers/securimage/securimage.php</b> on line <b>1329</b>

Die zie ik hier: http://nieuw.joomlacommunity.eu/bijeenkomsten/joomla-gebruikersgroepen-jug/evenement/76-piwik-een-open-source-alternatief-voor-google-analytics

**Comment by conconnl** [comment]
Hoi Hans,

Ja, dit is al gerepareerd.
Moet alleen nog gepusht worden naar de live site.

**Comment by conconnl** [comment]
@hans2103 kun jij het opnieuw testen?

**Comment by hans2103** [comment]
succesvol getest. Ik kan een comment plaatsen
