### ISSUE TITLE
[Informatie] - Afspraken & Besluiten / To-Do - Documentatie

### ISSUE THREAD

**Issue by MartijnMaandag** [stichtingsympathy/joomlacommunity.nl#13]
We zouden een artikel kunnen maken 'Aan de slag met Joomla' waarbij verwezen wordt naar de losse artikelen op docs.joomla.org.
Er kan ook verwezen worden naar video's die eventueel beschikbaar zijn.
Basis kan zijn het artikel 'Aan de slag met Joomla' uit het 'Handboek Joomla'.
Titel maken 'Aan de slag' in plaats van 'Documentatie'.

**Comment by marijkestuivenberg** [comment]
Verdere ideeën:
Enkele veel bezochte artikelen reviewen/updaten en laten staan, zoals bijvoorbeeld een meertalige website maken, Joomla testen. Dit soort artikelen dan vergelijken met wat er wel (of niet) op docs staat.
De boekenhoek kan eventueel ook op dit gedeelte, dan moet er wel iemand of een groepje zijn die dit up to date houden.

**Comment by slibbe** [comment]
Ik neem het boekengebeuren op me.

**Comment by marijkestuivenberg** [comment]
Todo

- Bepalen hoe de link moet gaan heten in de toekomst - Aan de slag
- Dit aanpassen en de bijbehorende css corrigeren.
- Dummy pagina uitschakelen.
- Artikel opbouwen voor de startpagina + custom modules.
- Submenu's opschonen, nieuwe submenu's naar tutorial(s)

**Comment by marijkestuivenberg** [comment]
Verder, er moet een styleguide ontwikkeld worden. Zodat wanneer men tutorials wil toevoegen deze kan raadplegen voor de styling

**Comment by conconnl** [comment]
@marijkestuivenberg op de hoofdpagina staat deze pagina.
http://nieuw.joomlacommunity.eu/home/stijlgids

**Comment by marijkestuivenberg** [comment]
Wat ik mis in de stijlgids is hoe we het beste afbeeldingen plaatsen. M.n. in de documentatie is het handig om te kunnen klikken op een afbeelding om ze in een modal window groter te kunnen bekijken. Is hiervoor een class? Kan dit toegevoegd worden aan de stijlgids

**Comment by marijkestuivenberg** [comment]
Een idee:
Wanneer je een individueel artikel in de documentatie bekijkt, lijkt het me prettiger lezen als het contentgedeelte breder is. Misschien is het een idee om zijbalk inklapbaar te maken? Dan kan de gebruiker zelf beslissen of deze het ook prettiger vindt het artikel over de volledige breedtje te bekijken of niet, en in het geval hij/zij het menu nodig heeft om verder te klikken de zijbalk weer uitklappen.

**Comment by sanderpotjer** [comment]
Sluit dit issue. Eventuele aanpassingen/issues voor downloads graag in separate issues
