### ISSUE TITLE
[Forum] Testen, testen, testen en .....

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#130]
Het wordt tijd om het forum goed testen op de volgende gebieden:
- Kloppen de ACL instellingen
- Klopt de weergave
- Is het gebruikersvriendelijk
- Zijn er geen bugs

Ik stel de volgende tests voor de volgende gebruikersgroepen voor

**Publiek (niet ingelogd, dus ook niet als offline gebruiker)**
- [ ] Vragen en antwoorden daarop zijn zichtbaar
- [ ] Er mag niks aangepast of gepost worden (antwoorden, stemmen, liken, etc.)
- [ ] Profiel van gebruikers is niet zichtbaar

**Geregisterd (normale gebruikers)**
- [ ] Er kan een nieuw topic worden geopend
- [ ] Er kan worden gereageerd op eigen topics of vragen van andere personen
- [ ] Profiel van andere gebruikers kan worden bekeken
- [ ] Gebruiker kan zijn topic sluiten en een reactie als antwoord markeren
- [ ] Gebruikers kunnen op een reactie stemmen (positief, negatief) en liken

**Moderator**
- [ ] Topics kunnen worden gesloten, geopend, samen gevoegd
- [ ] Berichten kunnen worden aangepast of verwijderd
- [ ] Gebruikers kunnen worden geband van het forum

**Algemeen**
- [ ] Het is makkelijk om een nieuwe vraag te stellen
- [ ] Het is duidelijk hoe dit moet, waar dit kan en hoe een categorie aangewezen kan worden
- [ ] Het is voor niet ingelogde gebruikers duidelijk waar ze kunnen inloggen of kunnen registeren.
- [ ] Er missen geen functies die het oude forum wel had
- [ ] Het nieuwe forum bevat geen functies die niet van toepassing zijn voor ons gebruik

**Comment by hvdmeer** [comment]
Hej @n9iels, waar jij Form schrijft, bedoel je dan Forum?

**Comment by n9iels** [comment]
ehhh het kan zijn dat ik die dingen 2 een beetje door elkaar heb gebruikt.....
Dus ja :)

**Comment by hans2103** [comment]
**Publiek (niet ingelogd, dus ook niet als offline gebruiker)**
- [ ] Vragen en antwoorden daarop zijn zichtbaar
- [ ] Er mag niks aangepast of gepost worden (antwoorden, stemmen, liken, etc.)
- [ ] Profiel van gebruikers is niet zichtbaar

**Geregisterd (normale gebruikers)**
- [ ] Er kan een nieuw topic worden geopend
- [ ] Er kan worden gereageerd op eigen topics of vragen van andere personen
- [ ] Profiel van andere gebruikers kan worden bekeken
- [ ] Gebruiker kan zijn topic sluiten en een reactie als antwoord markeren
- [ ] Gebruikers kunnen op een reactie stemmen (positief, negatief) en liken

**Moderator**
- [ ] Topics kunnen worden gesloten, geopend, samen gevoegd
- [ ] Berichten kunnen worden aangepast of verwijderd
- [ ] Gebruikers kunnen worden geband van het forum

**Algemeen**
- [ ] Het is makkelijk om een nieuwe vraag te stellen
- [ ] Het is duidelijk hoe dit moet, waar dit kan en hoe een categorie aangewezen kan worden
- [ ] Het is voor niet ingelogde gebruikers duidelijk waar ze kunnen inloggen of kunnen registeren.
- [ ] Er missen geen functies die het oude forum wel had
- [ ] Het nieuwe forum bevat geen functies die niet van toepassing zijn voor ons gebruik

**Comment by hans2103** [comment]
aanname bij het testen van moderator is dat de betreffende user is toegewezen aan de gebruikersgroep Moderator. 
Ik heb lokaal een nieuwe user aangemaakt toegewezen aan alleen de groep Moderator. 
Testen van het forum bij het onderdeel Moderator faalt. 
Ik kan niet inloggen.

@hvdmeer kan jij dit onderzoeken en oplossen?

**Comment by hans2103** [comment]
## NOTE 

voor de overige testers: klik op het potloodje van het eerste item van @n9iels. Kopieer de lijst van te testen items en plak hem in een nieuwe reactie. Plaats dan vinkjes bij elk succesvol geteste item.

**Comment by hvdmeer** [comment]
**Publiek (niet ingelogd, dus ook niet als offline gebruiker)**
- [ ] Vragen en antwoorden daarop zijn zichtbaar
- [ ] Er mag niks aangepast of gepost worden (antwoorden, stemmen, liken, etc.)
- [ ] Profiel van gebruikers is niet zichtbaar

**Geregisterd (normale gebruikers)**
- [ ] Er kan een nieuw topic worden geopend
- [ ] Er kan worden gereageerd op eigen topics of vragen van andere personen
- [ ] Profiel van andere gebruikers kan worden bekeken
- [ ] Gebruiker kan zijn topic sluiten en een reactie als antwoord markeren
- [ ] Gebruikers kunnen op een reactie stemmen (positief, negatief) en liken

**Moderator**
- [ ] Topics kunnen worden gesloten, geopend, samen gevoegd
- [ ] Berichten kunnen worden aangepast of verwijderd
- [ ] Gebruikers kunnen worden geband van het forum

**Algemeen**
- [ ] Het is makkelijk om een nieuwe vraag te stellen
- [ ] Het is duidelijk hoe dit moet, waar dit kan en hoe een categorie aangewezen kan worden
- [ ] Het is voor niet ingelogde gebruikers duidelijk waar ze kunnen inloggen of kunnen registeren.
- [ ] Er missen geen functies die het oude forum wel had
- [ ] Het nieuwe forum bevat geen functies die niet van toepassing zijn voor ons gebruik

**Comment by MartijnMaandag** [comment]
Voor het gemak heb ik alle artikelen van voor 1-1-2016 op gearchiveerd gezet.

**Comment by sanderpotjer** [comment]
@hvdmeer kan jij wellicht nog wat mensen regelen voor testen van forum functionaliteiten?

**Comment by hvdmeer** [comment]
Ik zou een paar actieve mensen van forum kunnen vragen @sanderpotjer . Als ik me niet vergis is er een test ACL beschikbaar zodat men kan inloggen op de nieuwe site.
