### ISSUE TITLE
Contact pagina

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#131]
De contact pagina (http://nieuw.joomlacommunity.eu/home/contact) is nu nog leeg. Hier moet informatie komen hoe er contact kan worden opgenomen met mensen uit de Joomla!Community.

Denk hierbij aan
- De stichting
- Moderators
- Team coordinators (bijv. om mee te helpen met JC)

**Comment by MartijnMaandag** [comment]
Ik heb de contactpagina gevuld (kort). 
Genoemde informatie heb ik verdeeld over artikelen "Over JoomlaCommunity" en "Contact".
Kan wat mij betreft gesloten worden.
