### ISSUE TITLE
[TEXT] - RSEvents! Mails

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#132]
In RSEvents! kunnen er e-mails geconfigureerd worden voor verschillende acties.

**Comment by hvdmeer** [comment]
@conconnl Fase-1, hier maar eens mee aan de slag? Werkt dit samen met Acymailing?

**Comment by conconnl** [comment]
@hvdmeer dit staat volledig los van AcyMailing.
Dit is een taak van Edith, ik weet niet wat ze hier precies mee wilt.

**Comment by Stitch123** [comment]
Hallo heren,
Blijkbaar heb ik even last van van m'n geheugen....iets wat niet veel voorkomt.....
Ik vermoed dat ik hiermee bedoelde dat als we iets posten op de agenda de betreffende JUG deelnemers een mailtje zouden krijgen. Een reminder van de bijeenkomsten (over een week zijn we er weer) en verslagen (het verslag van de vorige bijeenkomst). Of dit onder Fase 1 valt....vind ik discutabel, dit kan ook naar fase 2 denk ik zo......

**Comment by conconnl** [comment]
Dit gaat over de mails die automatisch verzonden worden, als mensen zich registreren en andere acties.
Als dit naar Fase 2 gaat kan alles van RSEvents niet online.
![2016-11-09 19_48_02-emails - joomlacommunity nl - administration](https://cloud.githubusercontent.com/assets/11913918/20150295/79195e70-a6b5-11e6-9513-c24e439a4e57.png)

**Comment by hvdmeer** [comment]
Ik ga hier mee aan de slag aangezien het toch best belangrijk is dat dit op 1 december live kan gaan.
- [] Registratie e-mail
- [] Activatie e-mail
- [] Uitschrijf e-mail
- [] Afgewezen inschrijving e-mail
- [] Uitnodigen e-mail
- [] Herinnering e-mail
- [] Naherinnering e-mail
- [] Moderatie e-mail
- [] Tag Moderatie e-mail
- [] Nieuwe evenement inschrijving notificatie e-mail
- [] Rapporteer e-mail
- [] Evenement goedkeurings-mail

**Comment by hvdmeer** [comment]
Alles is vertaald.
