### ISSUE TITLE
[Page] - Organisatoren pagina

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#133]
Vanuit de JUGs is het gewenst om een pagina te creëren met de informatie over en van de organisatoren.
Een algemene pagina is het beste zodat deze ook voor andere organisatoren gebruikt kan worden en niet alleen voor de JUGs.

Details volgen................

**Comment by slibbe** [comment]
Enig idee wat er op zo'n pagina moet komen? Ideeën over de layout daarvan?

**Comment by conconnl** [comment]
Ik heb zo snel even geen ideeën, dit punt komt van Edith.

**Comment by hvdmeer** [comment]
Ik heb ook niet echt een idee wat hiermee gedaan kan worden.

**Comment by sanderpotjer** [comment]
Zodra er concrete ideeën zijn kan dit opnieuw geopend worden of nieuw issue worden gemaakt.
