### ISSUE TITLE
[Media] - Mappen structuur voor Mediabeheer

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#134]
Een logische mappen structuur uitwerken voor de Mediabeheer, zodat vanuit alle delen van de site direct duidelijk is waar iets opgeslagen dient te worden.
Eventueel in de toekomst met verschillende rechten en profielen gewerkt kan worden.

**Comment by jissereitsma** [comment]
Pff, dat is nog al een punt. Ik zou zeggen dat je niet moet beginnen met een folderstructuur maar een lijst van alle plekken waarmee iets wordt opgeslagen (forum, downloads, blog) om dan van daaruit verder te werken. Ofwel een soort van Google Doc dat dan uitgebreid kan worden. Of juist de GitHub wiki hier gebruiken.

**Comment by hvdmeer** [comment]
Is hier al ergens een opzet gemaakt?
Gaat dit op voor de (hoofdzakelijk) afbeeldingen die op de website gebruikt worden of ook andere zaken?

**Comment by conconnl** [comment]
Er is nog geen opzet gemaakt.
Ik denk ook dat het vooral om de afbeeldingen gaan die op de site gebruikt worden.
Zoals bijvoorbeeld op de nieuwspagina, maar ook in de verschillende plekken zoals de bijeenkomsten.
