### ISSUE TITLE
[Gebruikersgroepen] - Categorieblog Verslagen

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#136]
Wanneer je via het menu naar **Bijeenkomsten** gaat en daarna naar **Verslagen** dan kom je in een **Categorielijst** uit van de Gebruikersgroepen.

Mijn voorstel is om deze categorielijst in een module aan de rechterkant te plaatsen en de lijst te vervangen door een blog zodra je direct de laatste verslagen ziet. Je kan dan nog steeds direct navigeren naar de verslagen van de Gebruikersgroep waarin je geïnteresseerd bent.

**Comment by conconnl** [comment]
Richt maar zoals jij denkt dat het beste is. 
Er is voor zover ik weet en kan zien nog helemaal niets gedaan met deze pagina.

**Comment by conconnl** [comment]
@hvdmeer je voorstel is doorgevoerd.

**Comment by slibbe** [comment]
Vind ik wel fraai werken. Enthousiasmeert ook om verslag te maken. 

Tested succesfully!

**Comment by hvdmeer** [comment]
Netjes, ik heb meteen #160 aangemaakt. ;)
