### ISSUE TITLE
[Login] - Login link en login status

### ISSUE THREAD

**Issue by jissereitsma** [stichtingsympathy/joomlacommunity.nl#137]
Op de nieuwe website zal het mogelijk worden voor eindgebruikers om in te loggen. Dat betekent ook dat het handig is om te weten of je al ingelogd bent, plus duidelijke links om in te loggen en weer uit te loggen. Voorbeeld: Ik ben nu ingelogd (omdat de site offline is) maar zie niet terug (tenminste vanuit een dummy mindset) dat ik ben ingelogd en hoe ik moet uitloggen.

Een mogelijkheid is om onderin wat linkjes mee te nemen (zoals "Inloggen", "Uitloggen", "Mijn account"). Andere optie is om dit juist helemaal bovenin te doen, eventueel gesteund met wat icoontjes.

Kan hier iemand met magische design krachten naar kijken?

**Comment by pe7er** [comment]
Misschien oplossen met een (tijdelijke) workaround:
menu item "Login" aanmaken dat alleen voor Guests zichtbaar is
menu item "Logout" dat alleen voor Registered zichtbaar is.

**Comment by allrude** [comment]
Inloggen is denk ik ook belangrijk op de forum page(s) als Easy discus een login menu optie heeft (niet bekend mee) dan kan op de forum pagina de login alvast worden aangezet, is dan meteen een workaround om voorlopig in te kunnen loggen op de frontend tot daarvoor een oplossing keuze is gemaakt

**Comment by hans2103** [comment]
login / logout menu items aangemaakt en toegewezen aan Hoofdmenu. 
Ze zijn nu zichtbaar in het hoofdmenu. 

login is zichtbaar voor gast
logout is zichtbaar voor geregistreerd

**Comment by conconnl** [comment]
Succesvol getest
