### ISSUE TITLE
[LayOut] - RSEvents! view van BS2 naar BS3

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#138]
De RSEvents views moeten van BS2 naar BS3 geconverteerd worden.

**Comment by conconnl** [comment]
http://nieuw.joomlacommunity.eu/bijeenkomsten/joomla-gebruikersgroepen-jug/bijeenkomsten/evenement/75-jug073

**Comment by hans2103** [comment]
@conconnl Welke views zijn er? En kan er voor elke view een apart issue aangemaakt worden?

**Comment by n9iels** [comment]
Ik heb de layout voor de kalender en een locatie bijgewerkt zodat deze met BS3 het goed doet.

**Comment by conconnl** [comment]
Ik weet niet wat en waar iets fout gegaan is.
De layout op alle pagina's van RSEvents zijn niet meer zoals deze waren.
Styling is totaal anders, zijn opeens bullets tevoorschijn gekomen en dergelijke rare effecten.

**Comment by sanderpotjer** [comment]
@conconnl klopt, ben er mee bezig

**Comment by conconnl** [comment]
@sanderpotjer Oke, dan hoor ik het wel als ze terug zijn.
Dan kan ik kijken welk punten er nog gedaan moesten worden vanuit de gebruikersgroepen, nu ik nog een beetje tijd heb.

**Comment by sanderpotjer** [comment]
Heb stijling van diverse RSEvents pagina's gedaan. Voor eventuele verdere issues graag losse issues aanmaken.
