### ISSUE TITLE
[Development] - Komento plugin voor comments onder RSEvents

### ISSUE THREAD

**Issue by sanderpotjer** [stichtingsympathy/joomlacommunity.nl#14]
Voorbeeld voor ZOO plugin [files_komento_elements_1.0.2_free.zip](https://github.com/stichtingsympathy/joomlacommunity.nl/files/92902/files_komento_elements_1.0.2_free.zip)

Hebben dus versie nodig voor RSEvents

**Comment by conconnl** [comment]
@n9iels Lukt het hiermee een beetje?
Zijn er nog RSEvents zaken die je nodig hebt, zoals installers of iets dergelijks?

**Comment by conconnl** [comment]
@hans2103 @n9iels Dit is niet meer nodig.
We gaan over naar RSComments.
