### ISSUE TITLE
[LayOut] - RSEvents! UTC selectie Modal werkt niet

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#141]
De UTC knop die een modal hoort te tonen werkt niet correct.
<img width="515" alt="screen shot 2016-09-10 at 10 19 54" src="https://cloud.githubusercontent.com/assets/11913918/18409101/5b308888-7740-11e6-8c1f-bba160f759d6.png">

Gerelateerd: #138

**Comment by jissereitsma** [comment]
Bijvoorbeeld http://nieuw.joomlacommunity.eu/bijeenkomsten/joomla-gebruikersgroepen-jug/bijeenkomsten/evenement/75-jug073 . @conconnl kan je bij de volgende issues direct een link tonen waarin dit probleem te zien is?

**Comment by conconnl** [comment]
Ja dat kan.
Die had ik al in de gerelateerde issue gezet 😄 
De link die je noemt klopt.

**Comment by jissereitsma** [comment]
O. Klik.

**Comment by jissereitsma** [comment]
Ik heb nu geprobeerd het voorbeeld van nieuw.joomlacommunity.eu op een eigen lokale copie te dupliceren, maar het lukt niet. Ik krijg nergens de **UTC** (of tijdzone) knop te zien. Jij wel?

**Comment by conconnl** [comment]
Dit is een optie die je aan kunt zetten in de instellingen van RSEvents!
Tab "Events"

**Comment by jissereitsma** [comment]
Check, gevonden. Er wordt wel een modal popup geopend, maar het modal window verschijnt vanwege styling niet in beeld. Ik pak dit verder op.

**Comment by jissereitsma** [comment]
Fixed in https://github.com/stichtingsympathy/joomlacommunity.nl/pull/158

**Comment by conconnl** [comment]
@jissereitsma 
Heb hem gemerged, als ik hem bij mij lokaal test zie ik dit:
<img width="1031" alt="screen shot 2016-09-10 at 15 04 04" src="https://cloud.githubusercontent.com/assets/11913918/18410628/e779d2be-7767-11e6-8380-eaacd0f30d45.png">

**Comment by jissereitsma** [comment]
Klopt. Het probleem is dat de verandering om dat scherm nog naar het midden te halen, wel is gefixed maar via LESS. En ik weet niet wat de beste manier is om die LESS code te compileren naar CSS en dan te committen. Ik kan de gecompileerde CSS weliswaar zelf wel committen, maar ik weet niet of het dan een troep wordt met git conflicts.

**Comment by conconnl** [comment]
Dan wachten we gewoon even op @hans2103

**Comment by hans2103** [comment]
Zo te zien heeft @n9iels de css al succesvol gecompileerd. De modal popup verschijnt netjes in het midden.
