### ISSUE TITLE
[LayOut] - RSEvents! Share buttons zijn niet mooi

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#142]
De share buttons staan niet echt mooi zo op de Events pagina's.
Kan een designer hier iets moois van maken?

<img width="378" alt="screen shot 2016-09-10 at 10 22 17" src="https://cloud.githubusercontent.com/assets/11913918/18409114/a381aaa4-7740-11e6-836c-9dcf8506d831.png">

Gerelateerd: #138

**Comment by jissereitsma** [comment]
Voorbeeld http://nieuw.joomlacommunity.eu/bijeenkomsten/joomla-gebruikersgroepen-jug/bijeenkomsten/evenement/75-jug073

**Comment by jissereitsma** [comment]
File `templates/jc/html/com_rseventspro/rseventspro/show.php`

**Comment by RemcoJanssen** [comment]
Ik ben bijna klaar met een fix hiervoor

**Comment by conconnl** [comment]
#150 Merged
