### ISSUE TITLE
[Fase 1] - Component not found

### ISSUE THREAD

**Issue by jissereitsma** [stichtingsympathy/joomlacommunity.nl#144]
Bij het bezoeken van de pagina http://nieuw.joomlacommunity.eu/home/over-joomlacommunity krijg ik een foutmelding *Fout tijdens het laden van component: , Component niet gevonden*. Ik gok dat dit ligt aan een module die wordt ingeladen terwijl dat niet zou moeten (omdat het component niet meer bestaat). Mijn lokale versie gebaseerd op de laatste Akeeba Backup heeft dit probleem niet.

**Comment by n9iels** [comment]
De live site loop zeer waarschijnlijk achter @hans2103 heeft rechten om dat te updaten

**Comment by jissereitsma** [comment]
Goed punt. De live site draait de `master` branch. Want ik heb inderdaad zelf de `development` branch draaien.

**Comment by n9iels** [comment]
Dat weet ik niet.... Dacht dat er op de server gewoon `git pull` wordt gedaan

**Comment by hans2103** [comment]
zojuist de server bijgewerkt. 
@jissereitsma  ik zie de foutmelding niet meer. Daarom sluit ik deze issue.
