### ISSUE TITLE
Submenus meteen onder hoofdmenu?

### ISSUE THREAD

**Issue by pe7er** [stichtingsympathy/joomlacommunity.nl#146]
Uit Usability oogpunt zou ik **alle submenus meteen onder het hoofdmenu** plaatsen.
Dan is de navigatie logischer en staat de submenu navigatie altijd op dezelfde plek.

**Voorkant > Bijeenkomsten:**
Nu staat er onder het hoofdmenu de titel "Bijeenkomsten" + advertentie en daaronder een submenu.

![joomlacommunity-bijeenkomsten](https://cloud.githubusercontent.com/assets/1217850/18409457/c4598088-7747-11e6-8b61-719472d50adf.png)

**Voorkant > Bijeenkomsten > Locaties:**
Hier ben ik de orientatie kwijt... 
Bezoekers die via een zoekmachine op deze pagina binnenkomen, moeten eerst heel goed kijken om dan te zien dat het een pagina over locaties voor bijeenkomsten is. 

![joomlacommunity-bijeenkomsten-locaties](https://cloud.githubusercontent.com/assets/1217850/18409468/0e8d7a4c-7748-11e6-873c-12c592166663.png)

**Voorkant > Home**
Op de voorkant is de ruimte tussen hoofdmenu + submenu weer heel anders:
![joomlacommunity-home](https://cloud.githubusercontent.com/assets/1217850/18409514/318e25d6-7749-11e6-917d-8b2d911885a5.png)

**Comment by jissereitsma** [comment]
Mee eens. Ik vond het ook al verwarrend.

**Comment by conconnl** [comment]
Helemaal mee eens.

**Comment by jissereitsma** [comment]
Zie PR https://github.com/stichtingsympathy/joomlacommunity.nl/pull/151 (niet direct mergen, pas na overleg met andere betrokkenen oa @sanderpotjer en ik denk @hans2103 )

**Comment by conconnl** [comment]
@sanderpotjer 
Kun je aub hiernaar kijken, zodat we weten of we dit mogen mergen?

**Comment by sanderpotjer** [comment]
Dit is gemerged, maar daarmee zeker nog niet af. Verplaatst alleen het element. Zijn nog verder CSS en JS aanpassingen nodig om dit goed te krijgen. Zal dit meenemen met direct nog andere header aanpassingen die nodig zijn (rond banner e.d.)

**Comment by n9iels** [comment]
Het menu ziet er nu ook wat vreemd uit, vermoed dat dat met dit issue te maken heeft?

![image](https://cloud.githubusercontent.com/assets/2659866/20465225/c76d8870-af58-11e6-830c-e091ce45142c.png)

**Comment by sanderpotjer** [comment]
@n9iels klopt. Inmiddels aangepast.
