### ISSUE TITLE
[FeatureRequest] - Google adres selectie

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#148]
Op de Gastsprekers aanmeld pagina is een veld "Kilometer vergoeding berekenen vanaf"
http://nieuw.joomlacommunity.eu/bijeenkomsten/aanmelden

Het zou mooi zijn als dit stuk gedaan kan worden met de Google Maps API om een adres te selecteren.
In RSForm!Pro zit alleen geen veld of plugin om dit te kunnen.

Als hier dit een keer gebouwd zou kunnen worden, kan ik weer zorgen dat RSJoomla! dit aan de standaard toevoegt.

**Comment by jissereitsma** [comment]
Ik zat er even aan te denken, maar dit is best een uitdagend klusje. Mijn voorkeur zou hebben dat dit veld gegenereerd wordt door middel van een `JFormField` klasse (wat dus eerst bekeken moet worden in de RSForm source). Vervolgens een nieuw `JFormFieldGmapAddress` klasse aanmaken met optie van GMaps openen in modal. Het voordeel hiervan is dat dit ding in een zelfstandige Joomla plugin aangeboden kan worden en kan worden hergebruikt door de community. Maar ja, wie gaat dat bouwen?

**Comment by conconnl** [comment]
Misschien een leuke uitdaging voor @n9iels 
Het is niet iets wat haast heeft, iedereen kan zijn adres intypen 😄

**Comment by n9iels** [comment]
klinkt wel als een leuke feature idd :) Kan RSForms overweg met een `JFormField`? Dat zou inderdaad het beste zijn want dan kan het algemeen gebruikt worden. Ik ga hier eens over denken :)

**Comment by sanderpotjer** [comment]
Dit heeft inderdaad zeer lage prio, echte "nice to have". RS extensies gebruiken helaas geen JForms...

**Comment by Stitch123** [comment]
Och heren....is het niet te ver gedacht? Een simpele ja of nee op de vraag of de gastspreker een kilometervergoeding wenst lijkt mij al voldoende....
Wellicht een extra veld waar men woont, dan kan je het zelf berekenen....

**Comment by conconnl** [comment]
Hoi Edith,

Mij maakt het niet veel uit. 
Aangezien het veld al aangemaakt was in het formulier kwam dit idee naar voren. 
Als jij vindt dat het niet nodig is, kunnen we de issue sluiten.

**Comment by Stitch123** [comment]
Wellicht iets moois voor de toekomst maar ivm de snelheid, voor nu maar even sluiten?

**Comment by sanderpotjer** [comment]
Dan sluit ik dit voor nu, als we een keer echt tijd over hebben kunnen we er naar kijken ;-)
