### ISSUE TITLE
[LayOut] Forum - color contrast niet groot genoeg

### ISSUE THREAD

**Issue by pe7er** [stichtingsympathy/joomlacommunity.nl#149]
Op het forum http://nieuw.joomlacommunity.eu/forum/leden/index is het **contrast van de letters t.o.v. de achtergrond** niet groot genoeg:

**Comment by pe7er** [comment]
Op het forum nieuw.joomlacommunity.eu/forum/leden/index is het contrast van de letters t.o.v. de achtergrond niet groot genoeg:
http://contrastchecker.com/
Foreground: #888
Background: #FFF
![contrast](https://cloud.githubusercontent.com/assets/1217850/18409640/99e640fc-774c-11e6-8513-303fed704a2e.png)

**Comment by hans2103** [comment]
@pe7er wat is je voorstel hoe het beter kan?

**Comment by pe7er** [comment]
Ik stel voor om het lettertype wat donkerder te maken.

Als je ipv lichtgrijs van #888888 gebruikt, donkergrijs van #585858 maakt, dan komt ie in ieder geval door deze contrast checker:

![contrastchecker](https://cloud.githubusercontent.com/assets/1217850/18431091/b4ef270c-78db-11e6-9dcd-f98cfd3d7b88.png)

Maar misschien is het handig om het ook nog even met enkele andere contrast checkers / accessibility checkers te controleren.

**Comment by hans2103** [comment]
Lijkt me een goed voorstel. En zo te zien heeft het niet te veel impact op het design en vergroot het direct de leesbaarheid.

**Comment by hans2103** [comment]
ik zie dat de styling van Easydiscuss met themes gaat.
Deze zitten in de map media/com_easydiscuss.

In dit geval is de kleur #888 de variabele _@fd-ui-meta-color_ uit het bestand media/com_easydiscuss/styles_lib/variables/variables.less

Ik heb verder geen ervaring met easydiscuss, maar als ik middels de met easydiscuss meegeleverde gulpfile de css wil compileren moet ik een package.json hebben met daarin alle dependencies. Deze zit er helaas niet bij.

**Comment by hans2103** [comment]
vragen stellen op het forum van Stackideas zit er zo te zien ook niet meer in:

> Starting from August 2016, customers with a valid and active license of the particular extension are allowed to access documentation section. However, essential documentation prior installing our extension are still available for public access. In order to maintain the quality of our support, customers with exclusive access are able to view this documentation section.

**Comment by hans2103** [comment]
vraag gesteld bij StackIdeas. http://stackideas.com/forums/adjust-theme-styling

**Comment by hans2103** [comment]
idee... om wijzigingen aan geinstalleerde extensie te voorkomen ga ik in de template inbakken dat de css van com_easydiscuss uitgeschakeld wordt en eigen css ingeladen wordt.

**Comment by hans2103** [comment]
@pe7er Ik heb de volgende acties ondernomen:

- uitschakeling van com_easydiscuss css file via helper.php in de JC template
- kopieren van com_easydiscuss less files naar de JC template
- toevoegen variabele met kleur #585858
- inladen van de extensie onafhankelijke com_easydiscuss css via de helper.php in JC template

**Comment by hans2103** [comment]
@pe7er kan jij testen of het contrast nu in orde is?

**Comment by conconnl** [comment]
Ziet er wat mij betreft goed uit.
Sluit het issue maar.
