### ISSUE TITLE
[LayOut] Lange emailadressen verdwijnen achter module - RS Events Pro

### ISSUE THREAD

**Issue by RemcoJanssen** [stichtingsympathy/joomlacommunity.nl#152]
Lange e-mailadressen verdwijnen achter 

<img width="1095" alt="schermafbeelding 2016-09-10 om 12 51 23" src="https://cloud.githubusercontent.com/assets/5138117/18409940/57518aea-7755-11e6-97cf-49b9772fafe7.png">

**Comment by conconnl** [comment]
Op welke pagina wordt die module en event tegelijkertijd getoond?

**Comment by yolknet** [comment]
Dat scherm is afkomstig van http://localhost/joomlacommunity/bijeenkomsten/joomla-gebruikersgroepen-jug/evenement/75-jug073

Voorstel:
De letters in de rechterkolom met gebruikersgroepen zijn met 25 pixels erg groot. Met 16 of 18px zijn ze ook prima leesbaar. De kolom kan dan smaller worden (.content-4 een breedte van 24% geven en een float right ipv left).

**Comment by conconnl** [comment]
Het scherm weet ik wel te vinden.
De module zie ik daar niet aan staan.
http://nieuw.joomlacommunity.eu/bijeenkomsten/joomla-gebruikersgroepen-jug/bijeenkomsten/evenement/75-jug073

**Comment by yolknet** [comment]
Dat is dan bijgewerkt sinds de backup. In mijn localhost staat het ook, op de site niet meer. Probleem opgelost dus?

**Comment by conconnl** [comment]
Voorlopig wel denk ik.
Denk wel dat we iets van Breadcrumbs moeten maken, zodat je nog een beetje weet waar je bent en terug kunt.
