### ISSUE TITLE
[Fase 1] - You have included the Google Maps API multiple times on this page

### ISSUE THREAD

**Issue by jissereitsma** [stichtingsympathy/joomlacommunity.nl#153]
Ik zie in de Error Console van bijvoorbeeld http://nieuw.joomlacommunity.eu/bijeenkomsten/joomla-gebruikersgroepen-jug/bijeenkomsten/evenement/75-jug073 staan de volgende melding: *js:93 You have included the Google Maps API multiple times on this page. This may cause unexpected errors.*.

**Comment by conconnl** [comment]
Ik denk dat dit de Google Map en de Google reCAPTHA is.
RSComments wordt getoond onder de RSEvents!.

**Comment by jissereitsma** [comment]
Ja, ik zie wel wat - maar volgens mij komt het doordat er 2x een zelfde source staat: https://maps.google.com/maps/api/js?libraries=geometry en https://maps.google.com/maps/api/js. Ik ga even kijken of de eerste weg kan.

**Comment by jissereitsma** [comment]
Ok, check - alleen de eerste nodig is, tweede mag weg. Ik ga kijken hoe.

**Comment by conconnl** [comment]
Werkt RSComments! dan ook nog op de pagina van artikelen?
Zoals: http://nieuw.joomlacommunity.eu/nieuws/gebruikersgroepen/334-verslagen/arnhem-nijmegen/2203-verslag-jug-arnhem-nijmegen-7-september

**Comment by jissereitsma** [comment]
Yup. Dat was juist even de uitdaging om alle scripts te laten werken - met of zonder extra library. Het is nu volledig uitbreidbaar. PR kan wat mij betreft gemerged worden.

**Comment by jissereitsma** [comment]
@conconnl Ready to merge en close.

**Comment by conconnl** [comment]
@jissereitsma Merged
