### ISSUE TITLE
[layout] Forum-> Registreren

### ISSUE THREAD

**Issue by allrude** [stichtingsympathy/joomlacommunity.nl#155]
Formulier velden in de tweede fieldset (Facebook, Twitter, Etc) hebben een size 150, en vallen buiten de container.

**Comment by hans2103** [comment]
@allrude wat is de url van de pagina?

**Comment by n9iels** [comment]
@hans2103 ik denk dat het hier gaat om /index.php/inloggen en dan op de knop "Registreren" drukken. Hiervoor zul je dus lokaal moet kijken, want op de live site is deze weergave niet te zien

**Comment by hans2103** [comment]
<img width="549" alt="schermafdruk 2016-09-26 15 56 43" src="https://cloud.githubusercontent.com/assets/639822/18836809/db45c7c2-8401-11e6-8282-14acce23d461.png">

**Comment by hans2103** [comment]
Vanuit de xml file plugins/users/easydiscussprofile/profiles/profile.xml de 150 gewijzigd naar 30.
Heeft iemand een idee hoe dit netjes kan zonder code hack op de extensie?
