### ISSUE TITLE
Gebruikersgroepen - Informatie toevoegen

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#156]
Coördinator Nederlandstalige JUG's - Edith van Leeuwen zal de onderstaande punten met de JUGs op moeten pakken.
- [ ] Locaties -  De namen van de organisatoren er nog bij komen inclusief foto (ronde afbeelding)
- [ ] Locaties -  Moeten de fotos nog toegevoegd worden van een bijeenkomst (indruk foto zaal)
- [ ] ???? - Quote vaste bezoeker

**Algemeen**
- [ ] - Wat moet een JUG aanleveren?

**Comment by sanderpotjer** [comment]
Ik heb voor nu in ieder geval mogelijk gemaakt om de organisatoren bij de JUGs te tonen
