### ISSUE TITLE
Responsive Issue met Stel een Vraag in Easy DIscuss

### ISSUE THREAD

**Issue by allrude** [stichtingsympathy/joomlacommunity.nl#161]
tussen schermgrote 512 en 624 breekt de design van de fields door dat de text  "Selecteer een categorie" te groot is (zie screenshot)

![stel een vraag - joomlacommunity nl](https://cloud.githubusercontent.com/assets/47407/18410664/60ba6c9c-7768-11e6-99b6-88da6157b8d7.jpg)

**Comment by hans2103** [comment]
url :  http://nieuw.joomlacommunity.eu/forum/recent/ask

**Comment by hans2103** [comment]
Voor mij is dit geen blocking issue.

**Comment by conconnl** [comment]
Voor mij is dit ook geen blocking issue.
Heb wel een idee: 
Wellicht vertaling aanpassen naar "Selecteer categorie", wellicht is dat voldoende.

**Comment by hans2103** [comment]
Door "Selecteer een categorie" te wijzigen naar "Kies categorie" is dit probleem helemaal opgelost.
Door "Selecteer een categorie" te wijzigen naar "Selecteer categorie" blijft het probleem bij onze template aanwezig tussen 510px en 530px bestaan. 

Alternatieve oplossing: niets doen en zo laten

@MartijnMaandag kan jij een besluit nemen hierin?

**Comment by MartijnMaandag** [comment]
Ik wil dit niet oplossen in het taalbestand van EasyDiscuss (hoewel ik dat wel kan) omdat dat inconsequent is hoe overal "Selecteer" gebruikt wordt als vertaling van "Select" en daarmee voor iedere gebruiker van het taalbestand gevolgen heeft.
Ik heb het nu opgelost via een override, zodat het alleen bij ons "Kies categorie" is geworden.
Override: COM_EASYDISCUSS_SELECT_A_CATEGORY
Ik denk dat iemand dat nog op de officiële manier moet implementeren?

**Comment by conconnl** [comment]
@MartijnMaandag je hebt het op de correcte plek geregeld, aangezien het een database setting is.
Issue sluit ik, aangezien het opgelost is.

**Comment by MartijnMaandag** [comment]
Toch nog even: Taal overrides komen volgens mij niet in de database (maar in language\overrides\nl-NL.override.ini). Ik heb geen verstand van het GitHub systeem, maar ik begreep dat alles dat in de bestandsstructuur terecht komt via GitHub geüpdatet moeten worden.

**Comment by conconnl** [comment]
Je hebt gelijk, wel vaag dat ik ze dan zag in mijn install.
Wellicht dat ik scheef keek.
Zal de overrides overtypen en uploaden.
