### ISSUE TITLE
[Layout] Layout submenu niet consistent

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#163]
De stijl van het locatie overzicht is verdwenen
![image](https://cloud.githubusercontent.com/assets/2659866/18412402/d3867fa2-778d-11e6-963b-dd11dd9e4023.png)

Kan dit wat te maken hebben met #160 @jissereitsma ? Of was dit al zo?

**Comment by conconnl** [comment]
@n9iels ik mis hier helemaal niets.

**Comment by hans2103** [comment]
@n9iels op welke pagina is deze verdwenen?

**Comment by n9iels** [comment]
De weergave van bijvoorbeeld de verslagen is net iets anders. Valt me sowieso op dat de weergave per submenu verschilt. Bijeenkomsten is weer een grote lettertype bijv.

<img width="352" alt="schermafbeelding 2016-09-11 om 22 54 32" src="https://cloud.githubusercontent.com/assets/2659866/18420452/4e7ab9fe-7873-11e6-901e-5656d9f1d602.png">

<img width="356" alt="schermafbeelding 2016-09-11 om 22 59 49" src="https://cloud.githubusercontent.com/assets/2659866/18420466/780107f6-7873-11e6-853a-d05575ae4303.png">

**Comment by conconnl** [comment]
Het zijn geen submenu's
Het zijn specifieke modules voor specifieke doelen, van verschillende extensies zowel core als RSJoomla 

Als je vindt dat alles hetzelfde moet zijn zal er voor elke module een override geschreven moeten worden.

**Comment by conconnl** [comment]
@n9iels Ga jij "Alternatieve lay-out" maken voor deze modules of moet ik dat doen.
Dan maak ze allemaal wel gelijk aan locaties: nieuw.joomlacommunity.eu/bijeenkomsten/locaties

**Comment by n9iels** [comment]
Ga ik wel doen

**Comment by conconnl** [comment]
@n9iels wat is de status hiervan?

**Comment by n9iels** [comment]
Nog niks aan veranderd

**Comment by hans2103** [comment]
De module "Gebruikersgroepen NL" komt vanuit mod_rseventspro_categories en plaatst een heading om de content in elke list-item.
Ik heb een override gemaakt die deze heading verwijdert.

**Comment by n9iels** [comment]
Yup, ziet er goed uit!
