### ISSUE TITLE
[LayOut] Footer artikel JUG verslagen

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#164]
Ik zag net dat #136 aangepakt was. Bij het volledige artikel staat daaronder een footer van de auteur. 
Nu ben ik dit in dit geval: http://nieuw.joomlacommunity.eu/bijeenkomsten/gebruikersgroepen-verslagen/334-arnhem-nijmegen/2203-verslag-jug-arnhem-nijmegen-7-september

Mijn avatar loopt alleen een klein stukje door het onderschrift heen.
Ook heb ik als test een afbeelding in mijn onderschrift gezet en die wordt niet opgenomen maar je ziet wel de code daarvoor staan.
![footer](https://cloud.githubusercontent.com/assets/7062995/18413645/0a2524c6-77ae-11e6-83c4-5bc99d425537.jpg)
Overigens, ik heb als voorstel wel dat afbeeldingen in de handtekeningen op het forum niet toegestaan zijn. Dit om het forum/de topics vooral overzichtelijk te houden.

**Comment by hans2103** [comment]
<img width="806" alt="schermafdruk 2016-09-11 21 24 02" src="https://cloud.githubusercontent.com/assets/639822/18419905/161f469a-7866-11e6-8112-702cd5584fb5.png">

**Comment by n9iels** [comment]
Ziet er hier ook goed uit! 👍

**Comment by hvdmeer** [comment]
Het screenshot van mij was thuis op de laatste versie van Chrome. Hier op mijn werk, ook de laatste versie van Chrome (onder win7) zit het er zelfde uit.
In welke browser hebben jullie gekeken?

**Comment by hans2103** [comment]
@hvdmeer Ik heb de screenshot gemaakt met CHrome, nadat ik de less files gewijzigd heb, css gecompileerd en nieuw.joomlacommunity.eu bijgewerkt. 
Kan het zijn dat bij jou de css nog in cache zit?

**Comment by hvdmeer** [comment]
Ai, ik dacht dat ik een refresh had gedaan... Inderdaad ziet het er nu hier ook goed uit. :)
Kan dus gesloten worden.
