### ISSUE TITLE
[easydiscuss] toegang Stackideas gewenst

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomlacommunity.nl#165]
Voor het oplossen van #149 heb ik toegang tot StackIdeas nodig.

> Starting from August 2016, customers with a valid and active license of the particular extension are allowed to access documentation section. However, essential documentation prior installing our extension are still available for public access. In order to maintain the quality of our support, customers with exclusive access are able to view this documentation section.

Wie kan mij deze toegang verschaffen?

**Comment by hvdmeer** [comment]
Heb je die nog nodig @hans2103 ? Ik ben later weer thuis en heb daar de inlog liggen.

**Comment by hans2103** [comment]
si... heb ik nog nodig voor #149.
Zou je de toegang in de wiki kunnen vermelden?

**Comment by sanderpotjer** [comment]
@hans2103 ik heb je de inlog gegeven. Gaan deze NIET!!! in een publieke wiki plaatsen
