### ISSUE TITLE
[Forum] Automatisch sluiten van topics

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#166]
Zelf was ik altijd van mening dat het automatisch sluiten van topics een functie is die niet echt nodig is. Maar het kan wel gebruikt worden om te voorkomen dat oudere topics niet gebruikt worden door anderen voor een eigen vraag. Wie hier ook een mening over heeft, wat vinden jullie bijvoorbeeld van het automatisch sluiten na 365 dagen?

En als reminder voor mijzelf: Dashboard - Instellingen - Algemeen - (tab) Composing

**Comment by conconnl** [comment]
Ik zeg doen.

**Comment by slibbe** [comment]
Ik zeg ook doen, maar na een kortere periode dan 365 dagen.

**Comment by hans2103** [comment]
"Topic closed due to inactivity", maar dan op z'n Nederlands.

**Comment by hvdmeer** [comment]
Ik heb het op 90 dagen gezet, normaal is er altijd wel een reactie geweest voor die tijd. En ik sluit deze dan meteen maar.

**Comment by n9iels** [comment]
Is er een mogelijkheid voor een notificatie? Ik ken een form dat iets stuurt als:
```
Het topic ***** dat je hebt aangemaakt is al 10 dagen niet bijgewerkt. Is je vraag ondertussen beantwoord? Zo ja vragen we je om in het topic aan te geven wat het antwoord was om andere met het zelfde probleem op weg te helpen. Als je niks doet zal dit topic na 5 dagen automatisch gesloten worden.
```

**Comment by erikvandoorne** [comment]
Ik vind de suggestie van n9iels wel een nette.

**Comment by hvdmeer** [comment]
Ik heb die niet ontdekt, wil nog wel even kijken.

**Comment by hvdmeer** [comment]
Ik heb het als idee geopperd maar blijkbaar zien niet veel andere gebruikers hier het nut van in:
https://stackideas.com/voices/easydiscuss/item/1373
