### ISSUE TITLE
[Structuur] Redirect gebruikersgroepen "shortlink"

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#167]
Naar aanleiding van een mail van Edith zat ik even op de JUG Arnhem vermelding op community.joomla.org. Daar staat als website van de gebruikersgroep vermeld: http://www.joomlacommunity.eu/arnhem

En dit deze wordt daarna doorgezet naar de agenda van onze huidige gebruikersgroep-pagina. Dit zal dan ook in de nieuwe website weer zo moeten gaan werken.

**Comment by conconnl** [comment]
Tegenwoordig hebben we http://joomlagebruikersgroepen.nl/arnhem

**Comment by hvdmeer** [comment]
Okay, maar dat betekend nog steeds dat die bij het live gaan ook aangepast moeten worden.

**Comment by sanderpotjer** [comment]
En sowieso graag de joomlacommunity.nl variant behouden, want dat kan vanuit de site aangestuurd worden en staat op diverse communicatie uitingen

**Comment by conconnl** [comment]
Precies, beide aanpassen. 
Die van joomlagebruikersgroepen.nl kan ik bij dus dat komt goed.

**Comment by sanderpotjer** [comment]
Via #172 oppakken dat iedere JUG een short-link krijgt

**Comment by conconnl** [comment]
Ik sluit deze omdat de nieuwe issue aangemaakt is, waarin deze oo benoemd is.

**Comment by conconnl** [comment]
De joomlagebruikersgroepen.nl links zijn aangepast en verwijzen nu naar de correcte JUG paginas
