### ISSUE TITLE
login / logout

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomlacommunity.nl#168]
ik heb lokaal de site op online gezet om issue #155 te reproduceren. 
Op die manier hoef ik niet voorbij het inlogscherm te komen, maar zie ik direct de website. 
Om issue #155 te kunnen reproduceren moet ik wel inloggen of registreren. 

Echter... ik kan de link inloggen / registreren niet vinden op de pagina. 

Kan het zijn dat deze ontbreekt?

**Comment by conconnl** [comment]
Zie #137

**Comment by hans2103** [comment]
dubbel issue dus.
