### ISSUE TITLE
Homepage slider responsive images

### ISSUE THREAD

**Issue by sanderpotjer** [stichtingsympathy/joomlacommunity.nl#17]

**Comment by conconnl** [comment]
@sanderpotjer en @n9iels kunnen jullie deze issue verduidelijken of andere actie mee doen.
Het is nu niet duidelijk wat het probleem is en wie dit dan op kan pakken.

**Comment by n9iels** [comment]
De afbeeldingen van de slider op de homepage worden soms op een vreemde manier afgekapt. Een paar voorbeelden:
![schermafdruk van 2016-04-19 20-20-37](https://cloud.githubusercontent.com/assets/2659866/14650535/7821af66-066c-11e6-8512-db12a6b3bd72.png)
![schermafdruk van 2016-04-19 20-21-05](https://cloud.githubusercontent.com/assets/2659866/14650536/7824c32c-066c-11e6-8816-dd0815133953.png)

Geen idee of hier een oplossing voor is. Daar zou een front-end developer naar moeten kijken

**Comment by n9iels** [comment]
Ik denk dat van deze issue niet veel meer valt te maken dan deze nu is. De CSS zorgt ervoor dat de afbeelding ongeveer in midden wordt gepositioneerd op mobiel.  Ik sluit deze hierbij, mocht  het echt problemen opleveren heropenen we hem.
