### ISSUE TITLE
Livegang: 1 december 2016

### ISSUE THREAD

**Issue by sanderpotjer** [stichtingsympathy/joomlacommunity.nl#170]
De site is een heel eind op weg, maar we zijn er nog net niet helemaal. Waarschijnlijk werkt het goed als we een deadline stellen: op **donderdag 1 december 2016** zal de nieuwe JoomlaCommunity.nl site live gaan, ook als die wellicht nog niet op alle onderdelen 100% af is. 

Voor de tijd zijn er uiteraard nog issues die echt opgepakt moeten worden, we zullen dit gaan prioriteren zodat we de echte show stoppers voor 1 december gefixed hebben.

Dank voor alle bijdrages tot dusver, op naar de nieuwe site op 1 december!

**Comment by hans2103** [comment]
Is er een stappenplan voor livegang? 
Kan ik ergens aan bijdragen om de daadwerkelijke livegang vlotjes te laten verlopen?

**Comment by sanderpotjer** [comment]
Het stappenplan moet nog uitgewerkt worden, nu nog niet beschikbaar

**Comment by hvdmeer** [comment]
Wordt het stappenplan ook als issue aangemaakt of als document. Wellicht dat er alvast wat aandachtspuntjes geplaatst kunnen worden.

**Comment by hvdmeer** [comment]
@sanderpotjer Je ligt vast net in bed, maar... ;)
Is hier al duidelijkheid over? Want het is nu 16 dagen tot live gaan. Gaan we alvast een artikel op de huidige website plaatsen dat het er aan zit te komen met een teaser screenshot?
