### ISSUE TITLE
Evenement registratie

### ISSUE THREAD

**Issue by MartijnMaandag** [stichtingsympathy/joomlacommunity.nl#174]
Bij het registreren voor een evenement (Deelnemen) staan de labels (Naam en e-mail) helemaal rechts.

**Comment by hvdmeer** [comment]
Zie voorbeeld:
![uitlijning](https://cloud.githubusercontent.com/assets/7062995/20037874/6e49bafa-a429-11e6-9674-f8798d03e18f.png)

**Comment by conconnl** [comment]
#138

**Comment by sanderpotjer** [comment]
Dit is nu gefixed
