### ISSUE TITLE
Evenement

### ISSUE THREAD

**Issue by MartijnMaandag** [stichtingsympathy/joomlacommunity.nl#175]
Een evenement bij de Gebruikersgroepen (op de voorpagina van de site)  verschijnt als je er op klikt bij de Pizza Bugs & Fun.

**Comment by sanderpotjer** [comment]
@MartijnMaandag heb hier even naar zitten kijken, maar RSEvents maakt een beetje een zooitje van de routing... Even kijken of we daar een werkbare oplossing voor kunnen maken. 

Probleem is voornamelijk dat je niet naar een single categorie kunt linken, bijv Utrecht. Daardoor raakt de routing in de war...

**Comment by sanderpotjer** [comment]
Opgelost door van http://nieuw.joomlacommunity.eu/bijeenkomsten de overzichtspagina van alle evenementen te maken
