### ISSUE TITLE
Fout in taalbestand rsevents

### ISSUE THREAD

**Issue by MartijnMaandag** [stichtingsympathy/joomlacommunity.nl#176]
@conconnl 
COM_RSEVENTSPRO_CONF_ARCHIVE_DAYS_DESC="Voer het aantal dagen in waarna**ar** RSEvents!Pro deze automatisch zal archiveren." moet worden "Voer het aantal dagen in waarna RSEvents!Pro deze automatisch zal archiveren."
en
COM_RSEVENTSPRO_CONF_INCOMPLETE_MINUTES_DESC="Voe**t** het aantal minuten in waarna**ar** RSEvents!Pro de incomplete evenementen zal verwijderen." moet worden "Voer het aantal minuten in waarna RSEvents!Pro de incomplete evenementen zal verwijderen."

**Comment by conconnl** [comment]
Dankjewel Martijn. 
Zal deze in de standaard vertaling bijwerken. 
Als je nog andere tegenkomt bij RSJoomla! extensies hoor ik het graag.
