### ISSUE TITLE
Vertaling RSEvents!Pro

### ISSUE THREAD

**Issue by MartijnMaandag** [stichtingsympathy/joomlacommunity.nl#178]
Ik ben wel bezig ;-)
@conconnl in RSEvents!Pro:
Bij de Kalender (http://nieuw.joomlacommunity.eu/bijeenkomsten/kalender) wordt zichtbaar Ouder en Nieuwer om te bladeren naar een vorige en volgende maand. Ik zou hier "Eerder" en "Later" gebruiken.
COM_RSEVENTSPRO_CALENDAR_NEWER="Nieuwer" en
COM_RSEVENTSPRO_CALENDAR_OLDER="Ouder"
moet dus worden:
COM_RSEVENTSPRO_CALENDAR_NEWER="Later" en
COM_RSEVENTSPRO_CALENDAR_OLDER="Eerder"

**Comment by conconnl** [comment]
Heb deze aangepast in de vertaalwebsite.
Zal het later toevoegen aan de JC website.
Kijk eerst even of er nog wat vertaald moet worden in de nieuwe versies.

Als je er meer hebt hoor ik het graag, je bent de eerste die ooit wat aanvullingen/verbeteringen stuurt.
