### ISSUE TITLE
Extra functionaliteit Joomla versie-module op voorpagina.

### ISSUE THREAD

**Issue by MartijnMaandag** [stichtingsympathy/joomlacommunity.nl#179]
Wat me opviel op de site is, dat nergens aangegeven wordt hoe je de nieuwste Joomla! versie kunt downloaden. Nu zullen er wel steeds release aankondigingen komen waarbij aangegeven wordt waar je hem kunt downloaden, maar toch.....
Kunnen we de versie-module op de Homepagina aanpassen met een extra parameter in de backend waar je een link kunnen opgeven waar naartoe een klik op de module moet leiden?  Target (current, new, ..) zou ook nog parameter kunnen zijn zoals elke URL link.
De link zal voor nu https://downloads.joomla.org/ moeten worden.
Ofwel: module wordt klikbaar en je wordt doorgestuurd naar de opgegeven URL,

**Comment by n9iels** [comment]
Ja hoor dit kan wel :-)
We kunnen de badge zelf aanklikbaar maken, dus het daadwerkelijke versie getalletje. We zouden ook een link eronder kunnen zetten, iets als: `Download de laatste versie hier`

**Comment by conconnl** [comment]
@n9iels ga je hier nog voor de LiveGang mee aan de slag?
Anders zetten we de milestone op daarna.

**Comment by n9iels** [comment]
@conconnl zet de milestone maar op deze release. Ik zal er een linkje onder zetten naar http://downloads.joomla.org/nl. Denk dat dat het duidelijkst is. Iets als: voor de laatste Nederlands talige versie van Joomla! kun je hier terecht.

**Comment by MartijnMaandag** [comment]
Maak er een taalstring van 😉

**Comment by n9iels** [comment]
![image](https://cloud.githubusercontent.com/assets/2659866/20652410/f02de836-b4f8-11e6-90ec-ab48353c1ddc.png)

zo iets? Tekst is uiteraard een taalstring, link is in de parameters te bewerken.

**Comment by MartijnMaandag** [comment]
Ik heb het resultaat van een externe link altijd liever in een nieuw venster (anders ben je de gebruiker direct kwijt).

**Comment by sanderpotjer** [comment]
@n9iels wil je dat nog even aanpassen?

**Comment by n9iels** [comment]
Ga ik doen! 👍

**Comment by n9iels** [comment]
Ik heb een update van de module uitgebracht. Ik kan deze momenteel zelf niet installeren omdat de database IP blocked is. Zal ik doen als ik thuis ben, mocht iemand in zijn lokale omgeving even op de update knop willen drukken mag dat ook :-)

Verder heb ik ook de LESS opnieuw gecompileerd. De live versie bevat niet de goede CSS viel mij namelijk op.

**Comment by sanderpotjer** [comment]
@n9iels dank! Update is op de site uitgerold
