### ISSUE TITLE
subtext mag misschien iets groter

### ISSUE THREAD

**Issue by superknutsel** [stichtingsympathy/joomlacommunity.nl#18]
Op niet alle schermen is de subtext goed leesbaar, is net wat klein.
Misschien ietjes groter dan nu het geval is.

![logo-subtext](https://cloud.githubusercontent.com/assets/9168059/12372810/1a7538bc-bc64-11e5-9e10-2042d080f221.jpg)

**Comment by hans2103** [comment]
Kleine aanpassing gedaan in de subline, waardoor de leesbaarheid vergroot wordt, maar nog steeds duidelijk is dat het een subline betreft. 
<img width="291" alt="schermafdruk 2016-05-02 18 02 28" src="https://cloud.githubusercontent.com/assets/639822/14959783/50a58136-1091-11e6-85fa-f65a78132ad1.png">
<img width="285" alt="schermafdruk 2016-05-02 18 02 35" src="https://cloud.githubusercontent.com/assets/639822/14959784/50a874e0-1091-11e6-944e-9a4cbac7dd12.png">

**Comment by conconnl** [comment]
Ziet er goed uit!

**Comment by superknutsel** [comment]
stuk beter te lezen !

**Comment by conconnl** [comment]
@hans2103 is deze al commit?
Dan kunnen we het issue sluiten.

**Comment by hans2103** [comment]
Als ik naar http://nieuw.joomlacommunity.eu/ ga, dan zie ik dat de wijzigingen doorgevoerd zijn.
