### ISSUE TITLE
[Frontpage] Springen slider frontpage

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#180]
De slider vliegt heen en weer in hoogte bij de verschillende afbeeldingen omdat deze niet allemaal even hoog zijn. Is het mogelijk dat de hoogte vastgezet wordt?

Edit: als ik terug omhoog scroll springt hij ook ineens nog een stukje omhoog, ongelijk met het scrollen van de pagina. Het oogt wat zenuwachtig.

**Comment by conconnl** [comment]
@hvdmeer klopt het dat dit nu opgelost is?
Bij mij zie ik het niet gebeuren.

**Comment by hvdmeer** [comment]
De hoogte blijft in nu wel gelijk.
Wel vind ik hem vreemd blijven springen @conconnl, tik maar eens drie keer op de cursor omlaag. De pagina verspringt een stukje meer dan normaal. Voor mij geen showstopper maar het valt mij wel erg op bij het scrollen.

**Comment by conconnl** [comment]
He Hans,
Ik zie wat je bedoelt, vanaf het punt van de H2 springt hij in één keer het hele stuk van de H2.
Op zich vindt ik dat logisch, ziet er inderdaad wel raar uit.

**Comment by hvdmeer** [comment]
Belangrijkste was de hoogte. Dit is wel te overkomen denk ik, mee eens? Dan kan hij gesloten worden

**Comment by sanderpotjer** [comment]
Laat maar even open, want ga daar nog wat aanpassingen doen

**Comment by sanderpotjer** [comment]
De slider is nu helemaal weggehaald, en daarmee probleem ook ;-)
