### ISSUE TITLE
Witte menu balk met hamburger voor/achter slider bij kleiner (mobiel) scherm

### ISSUE THREAD

**Issue by slibbe** [stichtingsympathy/joomlacommunity.nl#181]
Als ik de browser window smaller maak, of een tooltje gebruik voor de mobiele view, verdwijnt de witte menu balk met hamburger deels achter de slider bij scrollen.
Op mijn smartfoon, Samsung Galaxy Alpha in Chrome, 4.7 inch, treedt dit gedrag ook op.

**Comment by sanderpotjer** [comment]
@slibbe dank voor melden. De slider is weg en daarmee het probleem ook als het goed is :)
