### ISSUE TITLE
Reset filter bij menu-item klik

### ISSUE THREAD

**Issue by sanderpotjer** [stichtingsympathy/joomlacommunity.nl#183]
Huidige situatie, bezoek:
- http://nieuw.joomlacommunity.eu/bijeenkomsten
- klik daar op categorie "Joomla Gebruikersgroep Arnhem / Nijmegen"
- klik via hoofdmenu weer terug naar "Bijeenkomsten" http://nieuw.joomlacommunity.eu/bijeenkomsten

Dan blijft de filter voor  "Joomla Gebruikersgroep Arnhem / Nijmegen" actief. Dit is niet gewenst want iedere categorie heeft al eigen categorie pagina, bijv http://nieuw.joomlacommunity.eu/bijeenkomsten/categorie/310-joomla-gebruikersgroep-arnhem-nijmegen

@conconnl ik heb even zitten zoeken, maar volgens mij is het momenteel niet mogelijk om bij bezoeken http://nieuw.joomlacommunity.eu/bijeenkomsten de "reset filter" automatisch te forceren.

Klopt dat?

Zo ja, kan jij bij RSJoomla een verzoek hiervoor inschieten?

**Comment by hvdmeer** [comment]
En als je op de knop `[x] Toon alles` klikt dan komen ze wel te voorschijn, met als extra de volgende foutmelding:
`Warning: mb_strtolower() expects parameter 1 to be string, array given in /home/users/jooomftp/nieuw.joomlacommunity.eu/libraries/vendor/joomla/string/src/phputf8/mbstring/core.php on line 114`

**Comment by sanderpotjer** [comment]
@hvdmeer klopt, die knop heb ik daar zelf gezet ;-) Maar is beetje onhandig dat men die knop eerst moet indrukken, niet echt gebruiksvriendelijk..

**Comment by sanderpotjer** [comment]
Dit is nu opgelost middels een plugin die specifieke aanpassingen doet aan de routing voor de JUGs bij RSEvents. Dit voorkomt dat de filter gezet wordt, en dus ook niet gereset hoeft te worden. Plus nette broodkruimels en URLs voor de JUGs pagina, bijv https://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/breda
