### ISSUE TITLE
Update ondersteuning voor EasyDiscuss in RSEvents

### ISSUE THREAD

**Issue by sanderpotjer** [stichtingsympathy/joomlacommunity.nl#184]
Momenteel is er ondersteuning voor Avatars van EasyDiscuss in RSEvents, alleen is deze zo te zien gebaseerd op de oude versie van EasyDisucss. Ik heb dit nu middels een core-hack van RSEvents werkend gemaakt, maar zou uiteraard fijn zijn als dit goed wordt opgelost in RSEvents. 

@conconnl wil jij dit verzoek bij RSJoomla inschieten? Naast ondersteuning voor de Avatar dan ook graag voor profiellink (dat is er nu uberhaupt niet).

Dank!

**Comment by conconnl** [comment]
Hoi Sander,

Deze feature is gebouwd door Niels op basis van de versie (easydiscuss) die een paar maanden geleden aanwezig was in de site. 
Als EasyDiscuss nu alles aangepast heeft zal deze feature ook opnieuw gebouwd moeten worden. 
Dan kan ik wel weer proberen de nieuwe variant te laten implementeren in RSEvents. 

Als jij reeds aanpassingen hebt gedaan in RSEvents om dit weer werkend te maken, hoor ik graag welke aanpassingen het zijn en mail ik deze naar RSJoomla. 

Groeten
Wilco

**Comment by sanderpotjer** [comment]
Dank voor je reactie Wilco. De aanpassing die ik heb gedaan is momenteel een redelijk "dirty" hack. Dus die kan niet zo aangeleverd worden om toegepast te worden door RSJoomla zelf.

Voor een goede oplossing moet ik in de spaghetti van de RSEvents code duiken, daar is nu in ieder geval geen tijd voor. Mooiste zou zijn als RSJoomla dit gewoon zelf oppakt, want andere klanten van ze kunnen het immers nu ook niet gebruiken.

**Comment by conconnl** [comment]
Dat snap ik, dat kan alleen weken tot maanden duren. 
Aangezien Niels het bedacht en gebouwd heeft verwacht ik dat hij het zo gerepareerd heeft. 
Dan is het voor ons opgelost en kunnen we de code puur laten toevoegen en zit het gelijk in een nieuwe update. 

Ik kan niet programmeren en alleen maar meldingen maken, wat ik ook doe. 
Alleen lijkt het mij efficiënter als Niels even kijkt. 
Wij en ook RSJoomla kan er weinig aan doen dat EasyDiscuss in de laatste updates opeens de mechanisme aangepast hebben. 
Wat eigenlijk betekend dat we het in de basis voor niets hebben gebouwd. 

Tegelijkertijd betekend het ook dat de aanpassingen van Niels in RsComments voor EasyDiscuss ook opnieuw moeten, deze zijn op dezelfde methode gebaseerd. 

Groeten
Wilco

**Comment by sanderpotjer** [comment]
@conconnl in deze commit heb ik een juiste implementatie gedaan: https://github.com/stichtingsympathy/joomlacommunity.nl/commit/773fe605429647071a868e5320cb9451fbb4c799 die code kan RSJoomla evt gebruiken

**Comment by conconnl** [comment]
Dankjewel Sander. 
Ga ik deze vandaag nog aan ze communiceren. 

Groeten
Wilco

**Comment by conconnl** [comment]
In de tussentijd is er een update uitgekomen en geïnstalleerd. Alles zou moet werken met de nieuwe methode.
