### ISSUE TITLE
Menu titel downloads -> taalpakketten

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#189]
Moet de menu titel niet ook veranderd worden van "Downloads" naar "Taalpakketten"? In het issue over de besluiten van de download pagina staat dit vermeld.

De CSS is ook op deze manier ingericht. Momenteel heeft de menubalk op de downloads pagina ook nog niet de goede kleur. Zodra het menu item wordt gewijzigd zal dit ook goed komen.
![image](https://cloud.githubusercontent.com/assets/2659866/20732296/62112dbe-b68e-11e6-9f29-013b97dbe43a.png)

**Comment by sanderpotjer** [comment]
@n9iels Goed opgemerkt! Er is toch besloten om voor downloads te gaan. Met name nieuwe gebruikers zullen daar toch eerder op zoek naar zijn en geeft ook de ruimte ander type downloads aan te gaan bieden (bijv template overrides). Heb zojuist less variables aangepast.
