### ISSUE TITLE
HTML Fixes voor bijeenkomsten

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#191]
HTML bij de lijsten van organisatoren en mensen die komen is niet correct

![image](https://cloud.githubusercontent.com/assets/2659866/20734084/7fd76972-b697-11e6-9ad3-007c4f839d19.png)

**Comment by sanderpotjer** [comment]
@n9iels dank. Je hebt daar goed punt, maar na je aanpassing is niet meer hele rij van panel klikbaar, alleen de naam. Er was een mix van markup. Moet zijn of:
```
<div class="list-group list-group-flush panel-bijeenkomsten">
  <a class="list-group-item" href="#">Iets</a>
</div>
```
of als er geen links is maar gewoon een lijst
```
<ul class="list-group list-group-flush panel-bijeenkomsten">
  <li class="list-group-item">Iets</li>
</ul>
```

Heb de output nu naar eerste variant aangepast
