### ISSUE TITLE
Zwevend menu op mobiel

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#192]
Op mobiel en tablet zweeft het menu momenteel en plakt deze niet netjes vast bovenin het scherm

![image](https://cloud.githubusercontent.com/assets/2659866/20734266/9dbcb0cc-b698-11e6-88fd-7757a75596fd.png)

**Comment by sanderpotjer** [comment]
@n9iels thnx!
