### ISSUE TITLE
[EasyDiscuss] Bootstrap en FontAwesome worden onnodig geladen

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#194]
Het valt mij op dat bij het laden van een topic op het form zowel onderdelen als Bootstrap en FontAwesome opnieuw worden ingeladen. Bij FontAwesome wordt het gehele .woff file ook nog eens extra ingeladen. In de console log staan ook deze warnings:
![image](https://cloud.githubusercontent.com/assets/2659866/20755225/71085aba-b70e-11e6-98dd-3d69af279999.png)

Aangezien zowel Bootstrap als FontAwesome ook al via de template worden ingeladen lijkt mij dit niet nodig. Op mijn ontwikkelomgeving wordt de laadtijd ook aanzienlijk sneller als ik deze pakketten eruit haal.
Voorzover ik zie veranderd de layout van het form er niet door.

Kan iemand anders dit ook nog even goed testen? Wijzigingen hiervoor staan in de branch `ed-performance`

**Comment by sanderpotjer** [comment]
@n9iels om uitzoekwerk te voorkomen: hoe heb je ze er lokaal uit gehaald? Wat mij betreft doe je een commit ermee, dan dubbel check ik het ook nog wel even.

Zag ook dat RSEvents nog eens extra Font Awesome laadde, dit heb ik reeds weggehaald.

**Comment by sanderpotjer** [comment]
Ow wacht, zie nu je commit ;-) Ik ga het testen!

**Comment by sanderpotjer** [comment]
@n9iels stuk sneller & idd geen verschil, goed opgemerkt! Thnx!
