### ISSUE TITLE
"Stel een vraag"

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#195]
Vraag via adje:
In het forummenu staat "Stel een vraag", maar je kan ook een nieuw topic aanmaken als Tip of Opmerking. Dan dekt "Stel een vraag" de lading niet echt.

Misschien is "Nieuw onderwerp" of iets dergelijks beter?

**Comment by sanderpotjer** [comment]
Heb menu-item aangepast!
