### ISSUE TITLE
Test puntjes website

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#196]
Ik ben er zelf, en samen met mijn vader, nog even overheen gegaan. Dit waren enkele dingen die we tegen kwamen/ons opvielen:

- JUG verslagen komen best vaak terug op de website. Homepage, Nieuwsberichten etc. De suggestie is om deze in de nieuwsberichten niet terug te laten komen. Ze hebben immers hun eigen plaats in het Nieuws gedeelte en bijeenkomsten gedeelte
- Homepage van Nieuwsberichten (Zodra er op de knop "Nieuws" wordt geklikt) moet nog algemeen worden. Daar staan echter nu nog geen artikelen in.
- De Download pagina is momenteel nog niet af en duidelijk. Er staat bijvoorbeeld nergens een vermelding naar het Joomla.org Download portal.
- "Aan de slag met Joomla!" kan naar mijn idee wat meer ruimte op de homepage krijgen. Staat nu een beetje verscholen achter (wederom) de Joomla! Gebruikersgroepen.
- Slider moet nog aangepast worden met werkende links en afbeeldingen
- "Aan de slag met Joomla!" heeft nog geen intro.
- Resultaten bij zoeken geven een niet aanklikbare URL op het einde. Resultaten zijn overigens sterk verouderd (1.5 komt als eerste naar boven op "Joomla")
- Overweging of de huidige pagina die je ziet als je op het menu item "Form" klikt de goede pagina is. Wellicht dat het direct weergeven van de categorie structuur beter is?

**Comment by sanderpotjer** [comment]
@n9iels dank voor je punten. Wil je please ze opsplitsen in losse issues, anders gaat het erg onoverzichtelijk worden / door elkaar heen lopen ben in bang... (eerdere "verzamel" issues waren ook niet zo effectief)

**Comment by n9iels** [comment]
Zal ik doen :-)
