### ISSUE TITLE
[Feedback] Nieuwsberichten

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#197]
Het viel mij op dat er bij de nieuwsberichten heel veel JUG verslagen staan. Deze hebben in principe hun eigen gedeelte, namelijk het "Gebruikersgroepen" submenu.

Mijn suggestie is om het menu "Nieuws" te laten linken naar het Algemene nieuws. Deze is nu nog leeg echter

**Comment by hvdmeer** [comment]
We hebben nou eenmaal veel Gebruikersgroepen. ;-)
Maar een beetje exposure is voor de gebruikersgroepen wel welkom, al ben ik het er mee eens dat het soms een beetje veel kan zijn.

**Comment by sanderpotjer** [comment]
Momenteel staan op de huidige website de JUG verslagen tussen het gewone nieuws in eigen categorie en denk dat we dat ook zo moeten laten. 

Het is wel verwarrend dat onder "evenementen" ook verslagen staan. Dit kunnen we denk ik daar beter weghalen en bij de Gebruikersgroep pagina module tonen met laatste X verslagen van de JUG.

**Comment by hvdmeer** [comment]
Dat is zeker een goed voorstel, ik kan me daar prima in vinden.

**Comment by sanderpotjer** [comment]
Verslagen zijn nu bij JUGs zichtbaar, zie bijv https://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/categorie/318-joomla-gebruikersgroep-utrecht-de-meern
