### ISSUE TITLE
[Feedback] Homepage

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#198]
- Ik denk dat op de homepage het "Aan de slag met Joomla!" gedeelte meer naar voren mag komen. Dat staat nu nogal rechts onder verscholen in een klein blokje.
Wellicht is het een idee om dit blokje wat groter te maken? Denk dat dat voor de homepage handig is. Het idee is immers dat iemand die nieuw is met Joomla! de homepage ook nuttig kan gebruiken.
- De slider op de homepage bevat nog demo data en geen werkende links en knoppen

**Comment by sanderpotjer** [comment]
@n9iels de homepage is aangepast, zijn hiermee je punten voldoende aangepast?
