### ISSUE TITLE
[Feedback] Downloads

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#199]
De download pagina is momenteel nog niet gevuld. Ook is er nog geen duidelijkheid voor een gebruiker waar hij Joomla! kan downloaden. Er moet nog een duidelijke verwijzing komen naar het Joomla.org Download portal, en dat daar verdere instructies staan.

**Comment by MartijnMaandag** [comment]
Er moet ook een plekje komen voor path.php: http://download.joomlacommunity.eu/overige/file/32-path.html

**Comment by sanderpotjer** [comment]
@MartijnMaandag path.php heeft plekje gekregen: https://www.joomlacommunity.nl/downloads/divers/5-path-php

Verder moeten downloads nog iets verder gevuld worden en zou graag op https://www.joomlacommunity.nl/downloads onderaan wat info willen over downloads.joomla.org, dutch translation team en zelf bijdragen.

**Comment by hvdmeer** [comment]
En waar kan dat precies ingevuld worden @sanderpotjer , ik zie dat in Docman niet zo snel.

**Comment by sanderpotjer** [comment]
@hvdmeer dat kan niet gevuld worden. Moeten daar even modules (en posities) voor aanmaken

**Comment by hvdmeer** [comment]
Laat maar, module gevonden. 😎

**Comment by hvdmeer** [comment]
Inmiddels een module "Downloads - informatie onderaan" aangemaakt met alvast een blok over downloads.joomla.org.

**Comment by MartijnMaandag** [comment]
Ik heb de module aangevuld met informatie over Dutch Translation team en het voorlopig geplaatst onder de breadcrums position bij de Downloads.

**Comment by sanderpotjer** [comment]
@hvdmeer @MartijnMaandag dank voor jullie input. Tekst van Dutch Translation Team is naar aparte pagina op https://www.joomlacommunity.nl/downloads/dutch-translation-team verhuisd.
