### ISSUE TITLE
Verslagen koppelen aan gebruikersgroepen & bijeenkomsten

### ISSUE THREAD

**Issue by sanderpotjer** [stichtingsympathy/joomlacommunity.nl#20]

**Comment by Stitch123** [comment]
Het zou hierin mooi wezen dat als je het verslag hebt toegevoegd, de betreffende volgers (deelnemers van die JUG) een mail ontvangen dat het verslag gepost is.

**Comment by Stitch123** [comment]
Nog wel uitzoeken via welke manier (MailChimp/Acymailing of ?)

**Comment by conconnl** [comment]
Issue staat reeds in #28
