### ISSUE TITLE
[Feedback] Voorpagina

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#202]
Persoonlijk vind ik de voorpagina zoals die nu wordt weergegeven niet heel erg uitnodigend als startpagina. Als ik als bezoeker kom zie ik vrijwel altijd de zelfde pagina, zie bijlage
![voorpaginanjc](https://cloud.githubusercontent.com/assets/7062995/20783463/5e8c20d4-b794-11e6-8f73-477f405758c2.jpg)

Is het ook qua indexatie voor google niet handiger dat het menu item Nieuws als voorpagina gebruikt wordt? Je zou dan één module positie als zijbalk kunnen gebruiken voor de laatste versie, bijeenkomsten en starten met Joomla!

En om ruimte te besparen kan je voor de evenementen ook de introtekst weglaten.

**Comment by sanderpotjer** [comment]
@hvdmeer met de voorpagina ben ik gisteravond nog bezig geweest. Een nieuwe versie komt er sowieso aan. Het is wel zo dat we bewust voor een andere opzet voor de voorpagina hebben gekozen dan alleen nieuws. Nieuws komt er zeker op terug, maar het is ook de bedoeling dat we mensen die nog niets/weinig weten van Joomla op weg kunnen helpen en er algemene informatie komt over wat Joomla is, de features en wat je er zoal mee kan. Dit is iets dat op de huidige website mist.

**Comment by sanderpotjer** [comment]
@hvdmeer de update van de homepage is nu uitgerold. Ben benieuwd of je het zo beter vindt.

**Comment by hvdmeer** [comment]
Het is in ieder geval duidelijk dat er content geplaatst wordt, maar deze is op mijn monitor maar met één item zichtbaar.
![jcnew](https://cloud.githubusercontent.com/assets/7062995/20815867/f93989e2-b81f-11e6-8aa9-982bf51334bb.png)
Naar mijn bescheiden mening zou ik het bij één positie ipv twee houden, want zo hou je de statische informatie wel heel erg in je eerste view. 
Is het mogelijk dat die bovenste advertentie is meer in de website content geplaatst kan worden? In de huidige zit die naast het logo met het menu boven en onder. Als dat nu weer gebeurd heb je meteen meer ruimte voor de menu items.

Ik blijf wel bij mijn mening dat http://nieuw.joomlacommunity.eu/nieuws een mooi vormgegeven frontpage zou zijn. :)

**Comment by sanderpotjer** [comment]
@hvdmeer dank voor je feedback. http://nieuw.joomlacommunity.eu/nieuws  gaat sowieso niet de homepage worden. Uiteraard kan je er zelf je startpagina van maken, maar we willen juist meer een ingang vormen voor nieuwe gebruikers die nog niet de weg kennen.

Ik snap niet precies wat je met `Naar mijn bescheiden mening zou ik het bij één positie ipv twee houden, want zo hou je de statische informatie wel heel erg in je eerste view.` bedoelt eigenlijk. 

De advertentie in de website is geen optie, dan kom je teveel in de knoei met de ruimte. Als we het naast het logo zetten moet de header compleet anders en daarmee ook hoger. 

Zie overigens dat bij jou de intro tekst over 4 regels valt, bij mij 3:
<img width="1413" alt="screen shot 2016-12-02 at 00 06 49" src="https://cloud.githubusercontent.com/assets/522834/20816577/4c33210a-b823-11e6-9774-d3b26c2bd5a7.png">
Welke browser gebruik je?

**Comment by hvdmeer** [comment]
Ik zit hier standaard op Chrome, met Firefox zie ik de buttons onderin wel in mijn scherm omdat ik daar geen bladwijzerwerkbalk heb.
Ik ben een beetje "bang" dat wanneer we te veel statische informatie in de eerste view (is dit het juiste woord?) op de frontpage hebben dat mensen minder geneigd zijn om terug te komen. Wanneer het eerste scherm (om het toch maar zo te noemen) meer dynamisch is ziet men dat er nieuwe content is.

**Comment by sanderpotjer** [comment]
De "intro header" is iets minder hoog geworden, waardoor "Het laatste Joomla nieuws:" sneller zichtbaar moet zijn. Voor nu laten we dit even zo.
