### ISSUE TITLE
[Vraag] Editor forum

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#203]
Adje en Marijke hadden allebei vragen over de editor van het forum. Adje miste een preview functie en Marijke miste de smilies. Zelf had ik ze nog niet gemist omdat ik anders naar het gebruik aan het kijken was. 

Op dit moment staat de BBCode editor die met EasyDiscuss meegeleverd wordt ingesteld als standaard editor. Misschien is het wel gebruikersvriendelijker om JCE hiervoor te gebruiken. Dan moet er wel een profiel dusdanig ingesteld worden dat deze hiervoor gebruikt kan worden.

Ik heb een kopie gemaakt van het frontpageprofiel en deze alvast wat uitgekleed. Misschien dat iemand anders hier ook even naar kijken kan?

Oh, en UTF-8 Emoji vanaf JCE 2.6.0. :)
https://twitter.com/jceeditor/status/804034241336115200

**Comment by sanderpotjer** [comment]
@hvdmeer ik heb het aangepast en geactiveerd. Benieuwd of de ervaringen met deze editor beter zijn.

**Comment by marijkestuivenberg** [comment]
Gaat niet helemaal goed met uploaden van bestanden helaas. 

Wanneer ik een afbeelding via de editor werkbalk icoon probeer te uploaden krijg ik een foutmelding:
"The server returned an invalid JSON response."

Probeer ik het via knop Afbeelding onder de editor dan krijg ik een blanco pagina.
In een ander issue heb ik al gemeld dat bestand uploaden via het tabblad bijlagen ook een foutmelding geeft.

**Comment by sanderpotjer** [comment]
Ik heb de default BBCode editor weer geactiveerd, JCE geeft teveel issues icm EasyDiscuss. Smilies zitten er wel gewoon in, maar die waren niet zichtbaar. Uploaden van bestanden gaat volgens mij inmiddels wel goed via de "attachments" feature.
