### ISSUE TITLE
[Comments] - Bij evenementen geen reactie meer mogelijk

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#204]
Bij de evenementen is het niet meer mogelijk om reacties te plaatsen.
Het systeem staat wel correct ingericht hiervoor, het was ook getest.

**Comment by sanderpotjer** [comment]
@conconnl bij event waarmee ik aan het testen was stonden blijkbaar de comments sowieso niet actief, daardoor ook niet gemist ;-)

Maar ze staan er weer op.
