### ISSUE TITLE
[Forum] Bestand uploaden foutmelding

### ISSUE THREAD

**Issue by marijkestuivenberg** [stichtingsympathy/joomlacommunity.nl#205]
Bij het uploaden van een bestand (afbeelding .png 201 KB) krijg ik de volgende fout:

Waarschuwing

JFile: :kopiëren: Kan het bestand niet vinden of lezen: $/tmp/phpWidTAc
JFile: :kopiëren: Kan het bestand niet vinden of lezen: $/home/users/jooomftp/nieuw.joomlacommunity.eu/tmp/5e4a7165f5098b3af468491399b6d2a3

De afbeelding wordt niet weergegeven maar wel een 'bijlage' waar ik op kan klikken, en vervolgens een venstertje met foutmelding die ik niet kan wegklikken, enkel wegkrijg door de pagina te verversen.
![foutmelding-uploaden](https://cloud.githubusercontent.com/assets/1097499/20815847/e0732788-b81f-11e6-8a4c-8daf6b58fdd6.png)

**Comment by hvdmeer** [comment]
Ik heb @sanderpotjer even toegevoegd, ik zou hier zo 1-2-3 niks aan kunnen doen.

**Comment by sanderpotjer** [comment]
Wil er best naar kijken, maar waar upload je het bestand @marijkestuivenberg? Bij nieuw topic? Reageren op topic? PB?

**Comment by marijkestuivenberg** [comment]
In een reactie op een bestaand topic, via tabblad bijlage

Ook op andere manieren geprobeerd, zie #203 maar ook daarmee liep ik vast in foutmeldingen

**Comment by hvdmeer** [comment]
Het is mij wel gelukt door op de button "Upload bestanden..." te klikken. De buttons daarboven doen het bij mij niet, ik krijg een nieuw scherm waarin niks lijkt te gebeuren.

**Comment by marijkestuivenberg** [comment]
Inmiddels lukt het Hans el iets te uploaden, mij nog steeds niet.
Dat je de pop-up niet kan wegklikken is denk ik CSS probleempje, in de rechter bovenhoek is het er wel maar je ziet het alleen niet.

**Comment by marijkestuivenberg** [comment]
Andere afbeelding geprobeerd, waarbij het wel goed gaat.
Zou het kunnen omdat ik in die eerste afbeelding hoofdletters en koppeltekens in de naam van het bestand heb gebruikt?

**Comment by marijkestuivenberg** [comment]
Nadat ik de naam veranderd heb lukt het uiteindelijk wel, ik heb nu alleen kleine letters gebruikt en geen spaties. Nou is het de vraag wat wijsheid is, want je kan er natuurlijk op wachten dat mensen wel spaties en of hoofdletters in de bestandsnaam gebruiken. Misschien is er ergens een instelling die dat bepaalt?

**Comment by sanderpotjer** [comment]
@marijkestuivenberg ik kan dit probleem niet meer dupliceren. Bestanden met spaties / hoofdletters e.d. werken gewoon juist. Wellicht doordat het nu gewoon op de uiteindelijke plek staat (.nl)
