### ISSUE TITLE
Algemene informatie Gebruikersgroepen

### ISSUE THREAD

**Issue by Stitch123** [stichtingsympathy/joomlacommunity.nl#206]
Is het mogelijk om bij de 'Evenementen' --> Gebruikersgroepen, eerst de algemene informatie over de gebruikersgroepen te plaatsen. 
Dit artikel staat nu onder 'nieuws' vermeld maar staat volgens mij hier niet op z'n plaats. 
Hiervandaan zou dan een link naar de groepen/data moeten komen, net als bij de PBF. 

(ik hoop dat ik dit zo goed heb gedaan....is m'n 1e post....)

**Comment by sanderpotjer** [comment]
@Stitch123 Mijn vermoeden is dat mensen die naar http://joomlacommunity/evenementen/joomla-gebruikersgroepen eerder benieuwd zijn naar welke gebruikersgroepen er zoal zijn en de activiteiten die ze organiseren ipv lezen van een artikel. 

Wellicht een idee om een alinea bovenaan te tonen met dan een lees meer naar volledige artikel?

Bij PBF vindt ik het nu ook te lang, wil dat daar ook toepassen.

**Comment by Stitch123** [comment]
Hoi @sanderpotjer ,
Mee eens maar vind wel dat het er moet staan voor nieuwe bezoekers. Een algemene uitleg miste ik erg bij de 'oude' site.  Jouw voorstel lijkt me helemaal prima. Het moet ook niet een punt zijn wat irritatie opwekt. ....weer wegklikken voordat men bij de juiste info komt....
Ik vrees dat ik dit niet mooi kan aanpassen....wil jij dit doen?

**Comment by sanderpotjer** [comment]
@Stitch123 dit is nu aangepast! Intro + lees meer naar artikel
