### ISSUE TITLE
Organisatoren JUG's

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#207]
Ik heb bij de JUG categorieën in RSEvents voor zover mogelijk de organisatoren gekoppeld en een "Nick name"  toegevoegd in de EasyDiscuss profiel waar die nog niet ingevuld was. Deze wordt gebruikt in het overzicht van alle JUG's: http://nieuw.joomlacommunity.eu/evenementen/joomla-gebruikersgroepen

Voor Weert en Eindhoven weet ik niet precies wie deze organiseren, deze heb ik nog even niet ingevuld.

Wanneer de import van alle gebruikers van de huidige website voltooid is moeten de overige (te nieuwe) gebruikers nog toegevoegd worden.

**Comment by Stitch123** [comment]
Hoi Hans,
Waar kan ik dit vinden in de backend? Er zijn inmiddels wel wat wijzigingen....

**Comment by hvdmeer** [comment]
Als je het zelf wil doen, bij Componenten - RSEvents! Pro - Categories 
Open een )JUG_categorie en vul rechtsonderin bij het veld Author de code van de gebruiker in. Bij meerdere is het komma gescheiden zonder spatie.

**Comment by Stitch123** [comment]
Ok, dank je wel @hvdmeer .... ik zal eens even kijken hoe ver ik kom ;)

**Comment by Stitch123** [comment]
Ik heb er al een aantal toegevoegd. Alleen is bij sommige de naam niet zichtbaar....?

**Comment by sanderpotjer** [comment]
Waarschijnlijk is die info nog niet compleet in profiel (of profiel nog niet aanwezig)

**Comment by hvdmeer** [comment]
Zie mijn eerste post, het veld nick name moet ingevuld zijn in het EasyDiscuss profiel.

**Comment by Stitch123** [comment]
@hvdmeer  Kan ik dat doen of moeten ze dit zelf invullen?

**Comment by Stitch123** [comment]
@hvdmeer ik heb het gevonden ;) ....geen vreemde namen meer in de lijst voorlopig, ik heb hun eigen namen erin gezet i.p.v. bijnaam...

**Comment by Stitch123** [comment]
@hvdmeer Zodra de import gedaan is, wil ik de rest graag aanvullen. Kun je me hier van op de hoogte houden? Ik miste inderdaad nog enkele users/namen ;)

**Comment by hvdmeer** [comment]
@Stitch123 Het wordt voor mij ook spannend hoe het zal gaan verlopen, dit zal vlak voor het live-gaan gebeuren denk ik.

**Comment by sanderpotjer** [comment]
@Stitch123 @hvdmeer ik heb de opzet even wat aangepast: ipv handmatig de user id's in te voeren voer je eenmalig het gebruikersgroep ID in waar de JUG aan is gekoppeld. Automatisch worden dan de gebruikers die aan de groep (en dus de JUG) zijn toegewezen getoond. 

Als de Joomla gebruikersgroepen dus goed worden bijgehouden zullen de organisatoren die zichtbaar zijn dus ook automatisch kloppen. Evens nu fallback ingesteld die username toont zolang er in forum nog geen nickname is ingevoerd.
