### ISSUE TITLE
Verplaatsen van de locatie informatie van de JUG groepen?

### ISSUE THREAD

**Issue by Stitch123** [stichtingsympathy/joomlacommunity.nl#208]
Ik denk dat de vermelding over de locaties van de JUG's beter op onderstaande link geplaatst kan worden
http://nieuw.joomlacommunity.eu/evenementen/joomla-gebruikersgroepen
Deze informatie staat nu in de agenda erbij. Ik denk dat het netter is om dit naar voren te halen.
In de agenda hoort naar mijn idee alleen het 'programma' of 'doel' van de betreffende bijeenkomst te staan.

**Comment by sanderpotjer** [comment]
@Stitch123 ik denk dat ik je bericht niet helemaal snap... "beter op", bedoel je daarmee dat het op een andere plek weg moet of juist op http://nieuw.joomlacommunity.eu/evenementen/joomla-gebruikersgroepen erbij moet komen? En met locatie bedoel je in geval van Breda "Ontmoetingscentrum De Vlieren"?

**Comment by Stitch123** [comment]
Hoi @sanderpotjer , oh...sorry....
Ik bedoel dat de informatie over de locatie waar de JUG gehouden wordt inderdaad bijv. De Vlieren. met de info over hoe er te komen of men er kan eten etc.. bij de algemene info over de JUG en de organisatoren erbij moet komen. 
Het hoort naar mijn mening niet in de agenda bij de bijeenkomst te staan. In de melding van de bijeenkomst moet alleen de info over die bijeenkomst komen (het programma van die avond).

**Comment by sanderpotjer** [comment]
@Stitch123 dank voor de toelichting!

Ik denk dat het om een aantal redenen niet handig/beter is:
- een JUG kan mogelijk wisselen van locatie per bijeenkomst, of een keer een uitzondering hebben qua locatie
- meestal worden via social media links direct naar een bijeenkomst gedeeld, niet naar een JUG categorie. Daardoor handiger om op 1 pagina alle info te hebben
- RSEvents heeft geen standaard mogelijkheden voor een locatie per categorie, en als we dat zouden inbouwen hebben we ook weer uitzonderingen nodig voor een categorie als "PBF" waar de locaties per editie wisselen

Wat mij betreft is de huidige opzet dus prima.

**Comment by Stitch123** [comment]
@sanderpotjer Bedankt voor de toelichting...dan blijkt dit het maximaal haalbare.
