### ISSUE TITLE
Extensie voor beheren downloads

### ISSUE THREAD

**Issue by sanderpotjer** [stichtingsympathy/joomlacommunity.nl#21]

**Comment by conconnl** [comment]
RSFiles! + nl-NL taalpakket geïnstalleerd.
De gebruikte mappen door extensie: (Voor zover ik kan zien zonder FTP toegang)

Component
/administrator/components/com_rsfiles
/components/com_rsfiles

Taal
/administrator/language/en-GB/*com_rsfiles*
/language/en-GB/*com_rsfiles*
/administrator/language/nl-NL/*com_rsfiles*
/language/nl-NL/*com_rsfiles*

Plugins
/plugins/installer/rsfiles
/plugins/system/rsfiles
/plugins/editors-xtd/rsfiles
/plugins/search/rsfiles

Manifests
/administrator/manifests/files

**Comment by sanderpotjer** [comment]
@conconnl zo te zien is ook `templates/jc/html/com_rsfiles/` met inhoud aangemaakt, moet dit blijven? Dan voeg ik het toe aan de git repo

**Comment by conconnl** [comment]
Ja, doe maar. 
Was aan het proberen de gewenste uiterlijk voor Marijke te maken. 

Groeten
Wilco

**Comment by conconnl** [comment]
Kan gesloten worden.
De extensie staat al even geinstalleerd.
