### ISSUE TITLE
[Gebruikersgroepen] Toevoegen nieuwe bijeenkomst

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#210]
Ik wilde net via de frontend een nieuwe bijeenkomst toevoegen maar zag zo 1-2-3 geen mogelijkheid daar toe. Het toevoegen op de frontend van een bijeenkomst zou makkelijk vindbaar moeten zijn voor een JUG organisator.

**Comment by sanderpotjer** [comment]
@hvdmeer die functie is momenteel uitgezet, want dat werkte nog niet. Volgt snel na livegang, tot die tijd via de backend.

**Comment by sanderpotjer** [comment]
Zie verder in bestaand issue #182
