### ISSUE TITLE
[Gebruikersgroepen] Logo's gebruikersgroepen

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#211]
Voor de gebruikersgroepen zijn ooit logo's beschikbaar gemaakt, hierin staat ook de URL joomlacommunity.eu vermeldt. Als we met het domein naar het .nl overgaan is het handig om ook deze logo's daarop aan te passen en meteen ook naar de nieuwe stijl van Joomlacommunity.

Optie is om de nieuwe afbeelding te gebruiken die als standaard wordt ingeladen. 
![jclogo](https://cloud.githubusercontent.com/assets/7062995/20940073/b0f922b6-bbf1-11e6-97bf-7dd385b63e68.png)
Je zou dan de betreffende JUG vermelding dan in het midden daarvan kunnen plaatsen (eventueel een afkorting?)

**Comment by Stitch123** [comment]
Ik denk dat sommige JUG's hun eigen logo's zouden willen uploaden, is die mogelijkheid er?

**Comment by hvdmeer** [comment]
In de backend sowieso, gisteren nog gedaan. Frontend weet ik niet.

**Comment by sanderpotjer** [comment]
De JUGs kunnen per event de afbeelding aanpassen naar wat ze willen, dus volgens mij kan men zo uit de voeten. Is Utrecht in ieder geval gelukt ;)
