### ISSUE TITLE
[Forum] quote optie niet mogelijk

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomlacommunity.nl#212]
<img width="1113" alt="schermafdruk 2016-12-06 21 35 30" src="https://cloud.githubusercontent.com/assets/639822/20942521/f19f3f80-bbfb-11e6-83b7-12afd3024245.png">

De verwachting is dat als je op het icoontje " klikt dat de tekst gekopieerd wordt naar je reactie en geplaatst wordt als quote.
Dat gebeurt helaas niet... elke keer dat je op het icoontje " klikt komt er een javascript fout bij.
```
editor.min.js?44938c5…:2 Uncaught TypeError: ed.insertContent is not a function(…)
```

**Comment by hvdmeer** [comment]
Zal ik deze vraag/opmerking even op het EasyDiscuss forum plaatsen @hans2103 ? Of kan dit een specifiek probleem van onze site zijn?

**Comment by sanderpotjer** [comment]
Dit kwam denk ik doordat JCE in gebruik was, want lijkt nu wel goed te werken nu we weer de default EasyDiscuss editor gebruiken
