### ISSUE TITLE
[Forum] Forumcategorieën feedback gevraagd

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#214]
Gisteren tijdens #JUG073 heb ik even overleg gehad met @sanderpotjer en daarbij hebben we als doel gesteld om op het forum te proberen zo min mogelijk categorieën aan te maken.

De uitsplitsing van Webshops in Installatie/Templates/Cart etc is inmiddels omgezet naar alleen een categorie Webshops waarin alle vragen gesteld kunnen worden. 
Ik heb ook de Even voorstellen categorie uitgeschakeld, hier wordt al redelijk lang erg weinig gepost.

Binnen het Teamforum staan nu ook Downloads en Documentatie vermeld, ik heb al een vraag gehad of dit nodig zou zijn, dus deze verwijder ik ook zodat alleen de moderatorcategorie overblijft. Tijd zal leren of deze nodig is.

**Comment by sanderpotjer** [comment]
@hvdmeer dank voor het opschonen al, denk al stuk beter.

Ik zou "Over JoomlaCommunity" hernoemen in "JoomlaCommunity.nl" en zetten op het hoogste niveau (dus niet als sub van "Joomla!").

**Comment by hvdmeer** [comment]
Dat kan. Ik maak dan een container joomlcommunity.nl aan, Joomla is namelijk een container

**Comment by hvdmeer** [comment]
Geen container, een categorie. Ik verplaats meteen
* Update en veiligheidmeldingen
* Gebruikersgroepen
* Moderatoroverleg
daar ook naar toe. 

Ps Op de telefoon kan je je bericht niet bewerken.

**Comment by n9iels** [comment]
Ziet er goed uit! Ben ook van mening dat er wel minder categorieën kunnen zijn. We hebben immers nu ook tags waarmee je het onderwerp kunt aangeven. Als er meer berichten komen denk ik dat dit ook wel gaat lopen.
Intro pagina van het forum spreekt mij ook erg aan. Gewoon de berichten in die hoofd categorie, en je kunt door naar een subcategorie.

p.s: maak daar even een los issue van ;-)

**Comment by hvdmeer** [comment]
@n9iels Que? Wie wat waar welke issue waarom? :)

**Comment by sanderpotjer** [comment]
Dank voor de aanpassingen!
