### ISSUE TITLE
[Forum] Standaardcategorie ingesteld

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#215]
Bij het instellen van het forum heb ooit per ongeluk een standaardcategorie toegewezen, nieuwe topics worden hier standaard op ingedeeld. Het lijkt met verstandiger/handiger dat de vraagsteller zelf altijd moet kiezen in welk forumcategorie de vraag gesteld moet worden.

Wellicht dat in de database deze toewijzing weer teruggezet kan worden @sanderpotjer ?
Wanneer dit kan en gedaan is zal er eerst getest moet worden of er inderdaad dan topics aangemaakt kunnen worden.

**Comment by sanderpotjer** [comment]
@hvdmeer via de database inderdaad terug kunnen zetten
