### ISSUE TITLE
[Forum] Type voorpagina forum

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#217]
Toevallig kwam ik vandaag uit op /forum/forums. Ik vind dat er een stuk beter uit zien dan de gewone Recent weergave. 
@sanderpotjer ik heb deze nu even als startpagina ingesteld. (dus menu item Recent)
Ik heb een voorkeur voor deze versie, maar wat vinden jullie?

**Comment by sanderpotjer** [comment]
Wat mij betreft prima. Belangrijkste voor mij persoonlijk is dat recente activiteit goed zichtbaar is en mensen worden aangespoord onbeantwoorde topics te reageren. Dat was voordeel van de andere startpagina.

**Comment by n9iels** [comment]
Voorpagina is nu wel goed denk ik, omdat het overzichtelijk is. Ben alleen een beetje twijfelachtig over het doorklikken. Als ik nu op de voorpagina kijk zie ik berichten in de hoofdcategorie "Joomla!". Klik ik op de titel kom ik in de volgende overzichtspagina, met daarop de categorieën en berichten daarin. Ben bang dat dat wat onoverzichtelijk is.

Deze bedoel ik: https://www.joomlacommunity.nl/forum/joomla

**Comment by sanderpotjer** [comment]
@n9iels ik denk dat die weergave er beter uit komt te zien als er daadwerkelijk topics staan. Wellicht voor nu even zo houden, kunnen het altijd nog aanpassen als er wat meer echte content staat
