### ISSUE TITLE
[Forum] Vanuit profiel naar onderwerp gaan lukt niet

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#218]
Ik wilde net via een profiel naar een bericht op het nieuwe forum toegaan maar kwam uit op het profieloverzicht

Testen?
* Ga in het forummenu naar "Gebruikers"
* Zoek naar "Hans"
* Klik op mijn profielnaam
* Klik op het onderwerp "Testje code en JCE"

Je komt nu weer in het profieloverzicht

**Comment by sanderpotjer** [comment]
@hvdmeer dit is nu opgelost door het ID van het menu item "Forum" in te stellen in de SEO settings van EasyDiscuss
