### ISSUE TITLE
[Forum] Filter bij zoeken in gebruikers kan niet gereset worden

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#219]
Wanneer ik in het profielenoverzicht een zoekopdracht invoer heb ik daarna geen mogelijkheid meer om het filter te verwijderen.

**Comment by sanderpotjer** [comment]
@hvdmeer off-topic, maar de milestone "Fase 0.0.9 - Livegang" is bedoeld voor issues tijdens de livegang van de nieuwe site zelf :-)

**Comment by hvdmeer** [comment]
Oops. 🤖

**Comment by sanderpotjer** [comment]
@hvdmeer dit is default EasyDiscuss gedrag. Er is geen reset button, resetten kan door de zoektekst weg te halen en opnieuw te zoeken
