### ISSUE TITLE
[Forum] Edit buttons weghalen

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#220]
Bij het instellen van bijv. je handtekening of andere plaatsen waar je een HTML edit hebt zijn de editor buttons nog zichtbaar.
<img width="835" alt="schermafbeelding 2016-12-14 om 23 34 24" src="https://cloud.githubusercontent.com/assets/2659866/21204134/158605f4-c256-11e6-8105-f52c2ce943f6.png">

Denk dat het wijs is om die weg te halen. Een module als handtekening lijkt me niet wenselijk.
**edit** ik zie nu dat de module button enkel bij super users zichtbaar is. RSComment button is bij "Geregistreerd"  ook zichtbaar

**Comment by hvdmeer** [comment]
Dus het gaat nu alleen om de RSComment button?

**Comment by sanderpotjer** [comment]
De default EasyDicuss editor is weer terug, en daarmee probleem ook weg.
