### ISSUE TITLE
[Forum] Layout voor het stemmen

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#221]
Het is bij EasyDiscuss ook mogelijk om te stemmen op een berichten. Beetje zoals StackOverflow het doet. Dit gedeelte heeft echter nog niet zoveel styling en ziet er soms wat vreemd uit:
<img width="175" alt="schermafbeelding 2016-12-14 om 23 50 50" src="https://cloud.githubusercontent.com/assets/2659866/21204568/56590930-c258-11e6-9002-1e675d802ac1.png">

<img width="139" alt="schermafbeelding 2016-12-14 om 23 52 26" src="https://cloud.githubusercontent.com/assets/2659866/21204580/6390cd68-c258-11e6-8877-352935e405a4.png">

**Comment by sanderpotjer** [comment]
@n9iels bedoel je nu RSComments of EasyDiscuss?

**Comment by n9iels** [comment]
Ach, EasyDiscuss uiteraard

**Comment by hvdmeer** [comment]
Dat ziet er inderdaad hier ook niet goed uit. En wanneer ik op het stemmen klik krijg ik een lege "popup" en onder water deze foutmelding:

> XMLHttpRequest cannot load https://www.joomlacommunity.nl/. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://www.joomlacommunity.nl' is therefore not allowed access.
![jcstemmen](https://cloud.githubusercontent.com/assets/7062995/21288520/9f4e9fe0-c485-11e6-9637-4d08bae84ad5.png)

**Comment by sanderpotjer** [comment]
@hvdmeer als alles op www of non-www draait is dat probleem weg.

Verder vraag ik mij af of het stemmen überhaupt nodig is?

**Comment by sanderpotjer** [comment]
@hvdmeer is voor nu uitgezet, lets keep it clean and simple om te beginnen. Als het dan later gebruikt wordt moeten we het eerst even stylen.
