### ISSUE TITLE
[Forum] Javascript errors in console

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#222]
Als in een Forum topic open zie ik nog wat Javascript errors omhoog komen
<img width="1440" alt="schermafbeelding 2016-12-14 om 23 59 36" src="https://cloud.githubusercontent.com/assets/2659866/21204814/6536c70c-c259-11e6-8a1c-6d5097c1f988.png">

De laatste error komt op als je op de quote knop drukt van een bericht, zie #212

**Comment by sanderpotjer** [comment]
Google Maps API ontbrak in de settings (al wordt het niet gebruikt...) Errors zijn in ieder geval weg nu.
