### ISSUE TITLE
ReCaptcha instellen

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#223]
ReCaptcha geeft bij RSComments momenteel deze melding

<img width="317" alt="schermafbeelding 2016-12-15 om 00 05 18" src="https://cloud.githubusercontent.com/assets/2659866/21204986/3923f0ee-c25a-11e6-941b-28ef5ab8b8e4.png">

**Comment by conconnl** [comment]
als het goed is werkt het weer. 
Zat een typefout in de configuratie
