### ISSUE TITLE
[Documentatie] Afbeeldingen van "Aan de slag met Joomla!" terughalen

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#224]
De afbeeldingen bij "Aan de slag met Joomla!" zijn verdwenen. Vermoed dat deze bij het omzetten naar het .nl domein verdwaald zijn

**Comment by sanderpotjer** [comment]
Klopt, ben nog met de afbeeldingen bezig

**Comment by sanderpotjer** [comment]
Staan weer terug!
