### ISSUE TITLE
www of geen www

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#225]
Dat is de vraag.
Wanneer ik naar joomlacommunity.nl ga krijg ik het offline inlogscherm voor me. Als ik dan inlog wordt ik doorverwezen naar www.joomlacommunity.nl met opnieuw het offline inlogscherm.

Zal dit dubbel inloggen ook nog zo werken wanneer de site live gaat? Tegenwoordig kan je de www toch net zo goed laten vallen?

**Comment by hans2103** [comment]
Bij grote sites is het aan te bevelen toch www te gebruiken. Dat
vereenvoudigt de mogelijk tot gebruik van andere subdomeinen.

Op za 17 dec. 2016 om 18:11 schreef Hans van der Meer <
notifications@github.com>

**Comment by sanderpotjer** [comment]
Staat nu ingesteld om met www als default optie te gebruiken
