### ISSUE TITLE
[Informatie] - Afspraken & Besluiten / To-Do - Forum

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#23]
## To do's
- Template voor forum finetunen
- Voor verschillende (sub) fora kunnen nog sticky onderwerpen worden toegevoegd. Nalopen welke nog gebruikt kunnen worden.
- Controleren of er categorieën missen.

## Foruminstellingen die zijn aangepast
- Automatisch sluiten - uitgeschakeld.
- Rapport - moderatiemogelijkheid gebruikers ingeschakeld (werking controleren)
- Tags Maximaal aantal tags toegestaan - van 10 naar 5 gezet
- Work schedule - uitgeschakeld
- Terms & Conditions bij comment plaatsen - Uitgeschakeld
- Activeer locatie tagging in discussies - Uitgeschakeld
- Activeer locatie tagging in antwoorden - Uitgeschakeld
- Limiet aantal bijlages op 4 gezet
- Toegestaande bestandstypen - gif,jpg,png,zip,pdf
- Activeer aangepaste velden - Op Ja gezet
- Meervoudig stemmen toestaan - Op Nee gezet
- Nieuw bericht interval - Van 7 dagen naar 3 dagen gezet
- Toon moderatoren bij category - Op Nee gezet (ivm hoeveelheid Super Users)
- Show Gist Button - Op Ja gezet
- Open links in een nieuw venster - Op Ja gezet
- Site details in profiel - uitgeschakeld (kan gebruikersnaam, wachtwoord, FTP gegevens eigen site ingevuld worden)
- Sta abonnementen toe op de gehele site - Uitgeschakeld
- Bezig met het indelen van gebruikers in de Gebruikersgroepengroepen (2x woordwaarde) aan de hand van dit overzicht: http://www.joomlacommunity.eu/joomla-gebruikersgroepen.html
- Komento - Toon commentaren in profielen uitgezet :new:
- Reacties gebruiken op het forum. (Je kan dus op een post reageren of een post maken, dubbel)
- Forumregels updaten (staat inmiddels als artikel in de website)
- Social media deelopties onder een forumpost uitgeschakeld. Er wordt nu wel nog een Facebookscript ingeladen.

**Aangepast door @n9iels**
- Sta niet ingelogde mensen toe gebruikersprofielen te bekijken - op nee gezet
- Email adres afzender - aangepast naar noreplay@joomlacommunity.eu
- Naam afzender - aangepast naar Joomla! Community
- Informeer admin/moderator/beheerder bij nieuwe berichten - Op nee gezet
- Informeer eigenaar wanneer iemand het bericht leuk vind - Op nee gezet
- Activeer wachtwoord-bescherming (gebruikers kunnen hun vraag met een wachtwoord beschermen) - op nee bezet
- Activeer de "site details" tab bij vragen - op nee gezet
- Activeer enquêtes/polls voor vragen - op nee gezet 
## Foruminstellingen nog te beoordelen
- Testen resizen afbeelding avatar bij upload 
- Google Adsense - staat nu geactiveerd
- Facebook integratie: gebruiken? Dan moet Facebook ID ingevoerd worden bij Instellingen - sociale integratie :new:

**Comment by n9iels** [comment]
Zie #39 voor de gebruikersgroepen. Deze kunnen in EasyDiscuss gebruik worden

**Comment by hvdmeer** [comment]
Als ik een taal voor het forum wil installeren, hoe kan ik dat het beste doen @conconnl ?
Dit kan ik alleen via het component zelf doen zoals ik het nu zie.

**Comment by hvdmeer** [comment]
Verder, er zijn iconen voor de verschillende categorieën mogelijk. Weet iemand of er een gratis iconenset hiervoor te gebruiken is? Of dat iemand hier een ontwerp wil maken? 
Zo ziet het categorie-overzicht nu uit: http://nieuw.joomlacommunity.eu/forum/categorieen

**Comment by conconnl** [comment]
Hoi Hans,

Qua installaties van onderdelen moeten wij dit doen via een lokale installatie gekoppeld aan GIT.
Dan dienen we dit via een Pull Request naar de website te migreren.
Als je dit aan ons over wilt laten, mag je een issue aanmaken met de benodigde gegevens en dan kan iemand dit regelen.

Er zijn op internet verschillende gratis icon sets te vinden, zoals bij bijvoorbeeld YooTheme of deze interessant genoeg c.q. toereikend zijn zullen we wellicht met zijn allen uit moeten zoeken.
Het zal nog mooier zijn als iemand die helpt met deze website echt JC icoontjes kan maken.

**Comment by hvdmeer** [comment]
Ik zal een omschrijving maken voor die issue. 
Probleem bij die gratis icon sets is dat die ik vind allemaal een backlink willen, ik weet niet of dat een probleem is. Anders zou een eigen ontwerp beter zijn.

**Comment by hvdmeer** [comment]
@n9iels Ik krijg nog foutmeldingen als ik op de frontpage op de eerste twee items klik:
> Fatal error: Class 'DiscussHelper' not found in /home/users/jooomftp/nieuw.joomlacommunity.eu/templates/jc/html/com_content/article/default.php on line 35

**Comment by hvdmeer** [comment]
Ik zie ook een foutmelding komen als ik in het topmenu op Gebruikersgroepen klik:

> Fatal error: Class 'DiscussHelper' not found in /home/users/****/nieuw.joomlacommunity.eu/templates/jc/html/com_content/article/gebruikersgroepen.php on line 35

Komt dit door de override of is het een Easydiscuss probleem en is het handig om bij Stackideas te melden?

**Comment by conconnl** [comment]
De overrides laden informatie die niet meer bekend zijn in de extensie.
Maak even een aparte issue aan, dan kan een ontwikkelaar zoals @n9iels de overrides bekijken

**Comment by n9iels** [comment]
Issue is berekend idd. In mijn laatste PR voor de avatar integratie laad ik wel het goede bestand in dacht ik. Kan er nu even niet naar kijken :)

**Comment by conconnl** [comment]
@n9iels @hvdmeer 
Heb het issue opgelost.
Zal er zo een PR voor aanmaken, zodat dit naar de site gemigreerd kan worden.

**Comment by n9iels** [comment]
@conconnl @hvdmeer ik de PR gemerged :)

**Comment by MartijnMaandag** [comment]
EasyDiscuss vertaling moet bijgewerkt worden. Ik heb daar voor mijzelf nu autorisatie voor aangevraagd bij Stackideas. Hans heeft die autorisatie volgens mij vorige week door Marijke laten regelen?

**Comment by hvdmeer** [comment]
Ik ben net afgelopen week bij StackIdeas toegevoegd aan het vertaalteam, maar als jij er ook bij komt gaat het een stuk sneller. Wat bij mij hielp was een bericht plaatsen op het forum omdat ik niet toegevoegd werd toen ik alleen bij Transifex de aanvraag deed.

Heb jij de login van het forum? Anders kan ik in mijn topic jou ook nog melden met je gebruikersnaam.

**Comment by MartijnMaandag** [comment]
Ik ben inmiddels vertaler van EasyDiscuss en aan de gang ;-)
Zal eerst de Frontend doen.

**Comment by n9iels** [comment]
Ik ben even als "geregisterde" gebruiker ingelogd op het form, aan de hand daarvan heb ik nog een paar instellingen gewijzigd. Hierboven genoteerd.

**Comment by conconnl** [comment]
Heb de "Powered by" optie uitgeschakeld.
<img width="570" alt="screen shot 2016-10-10 at 20 43 05" src="https://cloud.githubusercontent.com/assets/11913918/19247224/669a4392-8f2a-11e6-851c-5c047175c4f4.png">

**Comment by hvdmeer** [comment]
Ik had deze aan laten staan omdat ik niet wist of deze gratis aangeboden wordt. En op het huidige forum staat ook vbulletin onder.

**Comment by MartijnMaandag** [comment]
Ik heb de forumregels in een artikel gezet en geplaatst in het menu.

**Comment by sanderpotjer** [comment]
Graag voor verdere punten losse issues aanmaken, wat makkelijker toe te wijzen/te volgen dan een groot issue ;-)
