### ISSUE TITLE
Geen link naar eigen profiel

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#232]
Ik kan geen link meer ontdekken naar je eigen gebruikersprofiel.  Het aanpassen van mijn avatar, mail adres of andere gegevens kan dan dus ook niet.
Eerst kreeg ik altijd een klein menu als ik op mijn eigen foto rechts boven klikte, dat is nu verdwenen.

**Comment by sanderpotjer** [comment]
@n9iels vernieuw de pagina even goed, want het zou als het goed is al gefixed moeten zijn

**Comment by hvdmeer** [comment]
Inderdaad, er is een ctrl-F5 voor nodig.

**Comment by n9iels** [comment]
Ach, iets te snel geconcludeerd. Werkt nu inderdaad goed, sorry :-)
