### ISSUE TITLE
http afbeeldingen

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#233]
Op de nieuwe pagina worden nu nog enkele afbeelding over HTTP ingeladen ipv HTTPS. Vermoed dat er op enkele plaatsen nog een absolute url staat.
![image](https://cloud.githubusercontent.com/assets/2659866/21543149/df632e42-cdc3-11e6-93d0-b21328e00f65.png)

Het is netjes als we een manier vinden om deze urls allemaal op te zetten naar https. Kan ook zijn dat dit met de livegang, en dus van .eu naar .nl, direct goed is 😄

**Comment by sanderpotjer** [comment]
Dit komt doordat de afbeeldingen nog via joomlacommunity.eu worden geladen... Moeten maar algemene zoek + vervang doen voor alles waar joomlacommunity.eu staat ;-)

**Comment by MartijnMaandag** [comment]
Misschien met ReReplacer?

**Comment by sanderpotjer** [comment]
ReReplacer kan, maar ook met paar regels code. Dat is nu gedaan.
