### ISSUE TITLE
Fout in Nieuws

### ISSUE THREAD

**Issue by MartijnMaandag** [stichtingsympathy/joomlacommunity.nl#234]
Hier gaat nog wat fout: https://www.joomlacommunity.nl/nieuws 
JUser: :_load: Kan gebruiker met ID: 4962 niet laden
Doordat er berichten niet aan de juiste gebruiker gekoppeld zijn?
Op de tweede pagina krijg ik drie meldingen.

**Comment by sanderpotjer** [comment]
Dit is gefixed als de gebruikers zijn gesynchroniseerd: #58
