### ISSUE TITLE
Kruimelpad geeft verkeerde info

### ISSUE THREAD

**Issue by alex0703** [stichtingsympathy/joomlacommunity.nl#236]
Het kruimelpad geeft verkeerde informatie bij het verslag van JUG Utrecht. Utrecht valt niet onder Zutphen... ;-) 
Zie bijlagen.

![schermafbeelding 2017-01-02 om 12 33 23](https://cloud.githubusercontent.com/assets/1523117/21588553/20f3b922-d0e8-11e6-96af-910dc4d60bd8.png)

![schermafbeelding 2017-01-02 om 12 37 46](https://cloud.githubusercontent.com/assets/1523117/21588562/4d6de4dc-d0e8-11e6-8107-eee26f692292.png)

**Comment by sanderpotjer** [comment]
@alex0703 hoe ben je op die pagina gekomen? Want via de nieuws pagina kom ik op https://www.joomlacommunity.nl/nieuws/gebruikersgroepen/343-utrecht-de-meern/1122-verslag-jug-utrecht-12-december-2016 waar kruimelpad wel goed staat>

**Comment by alex0703** [comment]
Via het bericht onder Het laatste Joomla! nieuws op de openingspagina. 

Overigens geeft jouw link een foutmelding op mijn iPhone. Zie bijlage. 

Groet,
Lex



Verstuurd vanaf mijn iPhone

**Comment by alex0703** [comment]
![img_4194](https://cloud.githubusercontent.com/assets/1523117/21589005/331fd3f6-d0ed-11e6-8ecc-92c99f62858c.PNG)

**Comment by sanderpotjer** [comment]
@alex0703 ik heb de caching van de broodkruimels even uitgezet, want lijkt erop dat het daar mis ging. Hopelijk probleem daarmee verleden tijd.
