### ISSUE TITLE
foutboodschap gebruikersgroepen

### ISSUE THREAD

**Issue by MartijnMaandag** [stichtingsympathy/joomlacommunity.nl#237]
Hier https://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/utrecht-de-meern krijg ik Class 'ContentHelperRoute' not found

**Comment by sanderpotjer** [comment]
@MartijnMaandag na het legen van de cache is probleem weg, maar wel vreemd. Om in de gaten te houden.

**Comment by slibbe** [comment]
Dit treedt niet alleen bij Gebruikersgroepen maar ook op algemene pagina's op.

En evenzeer in de LinkChecker. Het is dus misschien meer dan alleen een cache probleem.

Lijst met meer van deze problemen:
 https://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/utrecht-de-meern
 http://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/arnhem-nijmegen
 http://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/breda
 http://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/bussum
 https://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/s-hertogenbosch
 https://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/enschede
 https://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/leiden
 https://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/maastricht
 https://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/zutphen
 https://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/zwolle

ER staan overigens ook nog enkele http zonder s tussen.

**Comment by sanderpotjer** [comment]
Het blijft iets vreemds icm met caching. Maar hopelijk nu verholpen.
