### ISSUE TITLE
Ontbrekende afbeeldingen verslagen en venues

### ISSUE THREAD

**Issue by roland-d** [stichtingsympathy/joomlacommunity.nl#238]
De afbeeldingen uit de map images/stories/verslagen/jug010/ zijn niet meegekomen wellicht ook van de andere JUGs

Verder ontbreekt ook de afbeelding images/gebruikersgroepen/venues/Rotterdam.jpg

**Comment by alex0703** [comment]
Ook de afbeelding van onze venue (Zpot) is niet zichtbaar. JUG Utrecht.
https://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/utrecht-de-meern/event/96-show-your-site-en-dokter-joomla

**Comment by sanderpotjer** [comment]
@roland-d de afbeeldingen waren wel overgezet, alleen de meest recente niet. Nu wel

@alex0703 graag even opnieuw toevoegen, want kan die afbeelding niet op de oude server vinden.

**Comment by alex0703** [comment]
Is dit bruikbaar?

![zpot de meern jug utrecht](https://cloud.githubusercontent.com/assets/1523117/21589945/75efa79c-d0f7-11e6-81b4-3f94b3955700.jpg)

**Comment by sanderpotjer** [comment]
@alex0703 kan je ze zelf aan de locatie toevoegen, dat moet kunnen via de backend.

**Comment by alex0703** [comment]
Gelukt!

**Comment by hans2103** [comment]
Ik had de jc.nl site ook lokaal draaien. Daar zag ik meer afbeeldingen in images/gebruikersgroepen/venues die nog niet op de server stonden. Zijn nu toegevoegd
