### ISSUE TITLE
Google API foutmelding bij bewerken locatie Brasserie La Cocotte

### ISSUE THREAD

**Issue by roland-d** [stichtingsympathy/joomlacommunity.nl#239]
Als ik lokatie Brasserie La Cocotte wil wijzigen komt Google met deze foutmelding:
Google Maps API warning: NoApiKeys https://developers.google.com/maps/documentation/javascript/error-messages#no-api-keys

**Comment by sanderpotjer** [comment]
@roland-d de API key was niet ingesteld. Nu wel en daarmee is het probleem verholpen.

**Comment by roland-d** [comment]
@sanderpotjer Gechecked, werkt bij mij nu ook.
