### ISSUE TITLE
Tekst voor homepage Wat is Joomla

### ISSUE THREAD

**Issue by crommie** [stichtingsympathy/joomlacommunity.nl#24]
Sander wil je mij hier even aan toevoegen?

**Comment by sanderpotjer** [comment]
@crommie je hebt nog een 'uitstaande' uitnodiging, na acceptatie kan ik je toewijzen aan dit issue.

**Comment by crommie** [comment]
I'm in!

**Comment by hans2103** [comment]
@crommie wat is de status van deze issue?

**Comment by crommie** [comment]
Thom Hiemstra is ermee bezig.

**Comment by crommie** [comment]
@hans2103 Er is een tekst, maar die staat er nog niet in. Thom heeft de tekst gemaakt, het kan zijn dat @sanderpotjer hem ook heeft.

**Comment by hans2103** [comment]
@crommie Zou jij hem bij Thom kunnen opvragen?

Op wo 25 mei 2016 om 13:14 schreef Anja de Crom <notifications@github.com>

**Comment by crommie** [comment]
@hans2103 done. wordt vervolgd.

**Comment by crommie** [comment]
@hans2103 Artikel is terecht. Ik heb het (voorlopig? of definitief?) ondergebracht in het artikel "Over Joomla" dat een eigen menu-item heeft. Misschien op home alleen intro met een lees meer in module zetten? Of was iets anders de bedoeling?

**Comment by hans2103** [comment]
top.
ik heb de link van het stukje tekst in de module linksboven op de homepage gewijzigd naar /home/over-joomla, zodat het uitkomt bij de tekst Over Joomla.
