### ISSUE TITLE
Afbeelding ontbreekt bij forumregels

### ISSUE THREAD

**Issue by bamisalami** [stichtingsympathy/joomlacommunity.nl#240]
https://www.joomlacommunity.nl/forum/forumregels

helemaal onderaan de pagina
Als je denkt dat iemand zich niet aan de regels houdt, rapporteer de post dan door op het Rapporteer-icoon te klikken. De afbeelding wordt niet gevonden.

**Comment by hvdmeer** [comment]
Bedankt voor het doorgeven. 
@sanderpotjer Ik kan deze niet in de artikelen vinden, waar deze tekst volgens mij staat kan ik niet met bij. ;-)

**Comment by bamisalami** [comment]
Wat me opvalt is dat er nog een pagina is waar de afbeeldingen niet meegenomen zijn:

Ik zal hieronder de linkjes plaatsen als ik er meer tegenkom:
https://www.joomlacommunity.nl/nieuws/gebruikersgroepen/329-breda/1117-verslag-jug-breda-dd-29-november-2016

**Comment by hvdmeer** [comment]
Als ik me niet vergis is daar al een issue voor aangemaakt. 
Graag ook een probleem per issue. Dit voor het overzicht en het kunnen sluiten na een oplossing.

**Comment by bamisalami** [comment]
gooi hem wel weg.

**Comment by sanderpotjer** [comment]
@bamisalami dank voor doorgeven van ontbreken afbeelding bij JUG artikel, zijn nu terug.

Bij forumregels is het ook aangepast, goed opgemerkt!

@hvdmeer rechten ook direct even juist gezet zodat je er wel bij kan ook.
