### ISSUE TITLE
Link: Tags bij forum onderkant loopt niet helemaal lekker

### ISSUE THREAD

**Issue by bamisalami** [stichtingsympathy/joomlacommunity.nl#241]
De G is niet 100% zichtbaar. Deze valt voor een deel weg.

**Comment by hans2103** [comment]
![schermafdruk 2017-01-02 14 08 43](https://cloud.githubusercontent.com/assets/639822/21589720/01508476-d0f5-11e6-8484-beda55038b3c.png)

Zo ziet een tag er bij mij uit. @bamisalami hoe ziet het er bij jou uit?

**Comment by bamisalami** [comment]
![tags g niet lekker](https://cloud.githubusercontent.com/assets/713708/21589762/743d6b02-d0f5-11e6-91a3-348e4023ff8f.JPG)

Deze bedoelde ik.

**Comment by hans2103** [comment]
aha... deze url dus.
https://www.joomlacommunity.nl/forum/tags

dat is handig voor het reproduceren en oplossen.

**Comment by sanderpotjer** [comment]
@bamisalami dank voor het melden. Als je de pagina even goed vernieuwd moet het verholpen zijn.
