### ISSUE TITLE
Icon.png en logo niet identiek

### ISSUE THREAD

**Issue by bamisalami** [stichtingsympathy/joomlacommunity.nl#242]
Een heel klein item maar viel me meteen op.
icon.png deze afbeelding is niet gelijk aan het logo van joomlacommunity.nl
Bij icon.png zit de groene kleur links, en de blauwe rechts.
Bij het logo van joomlacommunity is dit net anders. Dus groen rechts en blauw links.
Zo ook met rood en oranje.

**Comment by sanderpotjer** [comment]
@bamisalami dat is wel heel scherp zeg! Nu aangepast, dank!
