### ISSUE TITLE
tikfout in submenu-link Forum

### ISSUE THREAD

**Issue by wilmarmeijer** [stichtingsympathy/joomlacommunity.nl#243]
registeren --> registreren 

![schermafbeelding 2017-01-02 om 14 11 55](https://cloud.githubusercontent.com/assets/4104556/21589797/d75c03ce-d0f5-11e6-8f8c-e661bed66ce1.png)

**Comment by sanderpotjer** [comment]
@wilmarmeijer dank, gefixed nu!

**Comment by MartijnMaandag** [comment]
Ik weet niet hoe Sander dit heeft gefixed, maar ik heb het in de taalbestanden aan de bron (Transifex EasyDiscuss) aangepast.

**Comment by sanderpotjer** [comment]
@MartijnMaandag dan was het daar ook een fout. Ik heb het menu item zelf aangepast :-)
