### ISSUE TITLE
Stichting Website bijwerken met de correcte urls, feeds etc

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#245]
http://www.stichtingsympathy.nl/ heeft verschillende links die naar 404 pagina's gaan op de nieuwe site. Daarnaast moeten waarschijnlijk zaken als feeds en dergelijk bijgewerkt worden.

**Comment by slibbe** [comment]
Al vast een paar:
Parent															Target
https://www.joomlacommunity.nl/templates/jc/css/template.css	https://www.joomlacommunity.nl/templates/jc/fonts/glyphicons-halflings-regular.eot
https://www.joomlacommunity.nl/templates/jc/css/template.css	https://www.joomlacommunity.nl/templates/jc/fonts/glyphicons-halflings-regular.eot#iefix
https://www.joomlacommunity.nl/templates/jc/css/template.css	https://www.joomlacommunity.nl/templates/jc/fonts/glyphicons-halflings-regular.woff2
https://www.joomlacommunity.nl/templates/jc/css/template.css	https://www.joomlacommunity.nl/templates/jc/fonts/glyphicons-halflings-regular.woff
https://www.joomlacommunity.nl/templates/jc/css/template.css	https://www.joomlacommunity.nl/templates/jc/fonts/glyphicons-halflings-regular.ttf
https://www.joomlacommunity.nl/templates/jc/css/template.css	https://www.joomlacommunity.nl/templates/jc/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular
https://www.joomlacommunity.nl/templates/jc/css/template.css	https://www.joomlacommunity.nl/templates/system/images/pdf_button.png
https://www.joomlacommunity.nl/nieuws							https://www.joomlacommunity.nl/joomla-gebruikersgroepen/regio-rotterdam/details/672-jug010-21-november-2016.html
https://www.joomlacommunity.nl/forum							https://www.joomlacommunity.nl/forum?format=feed&type=atom
https://www.joomlacommunity.nl/forum							https://www.joomlacommunity.nl/forum?format=feed&type=rss
https://www.joomlacommunity.nl/nieuws/joomlacommunity			https://www.joomlacommunity.nl/joomla-demo.html
https://www.joomlacommunity.nl/over-joomlacommunity				https://www.joomlacommunity.nl/docs.joomla.org
https://www.joomlacommunity.nl/nieuws/extensies					https://www.joomlacommunity.nl/www.joomlacommunity.eu/amsterdam

**Comment by sanderpotjer** [comment]
@slibbe check even https://guides.github.com/features/mastering-markdown/ voor hoe je het in code tags plaatst, dan gaat het goed. Ik weet overigens niet precies wat de lijst met stichtingsympathy.nl te maken heeft?

**Comment by slibbe** [comment]
404's

**Comment by sanderpotjer** [comment]
Volgens mij ging @conconnl issue specifiek over de links op stichtingsympathy.nl naar joomlacommunity.nl, maar maakt niet uit.

**Comment by slibbe** [comment]
Oh sorry. Dan maak ik een nieuwe aan.

**Comment by MartijnMaandag** [comment]
Ik heb alle links op StichtingSympathy.nl aan gepast. Alleen de feed staat nog naar de oude site.

**Comment by sanderpotjer** [comment]
Feed is nu ook gefixed, net als nieuwe screenshots op de homepage.
