### ISSUE TITLE
Mobiele weergave kruimelpad forum

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#246]
Op mijn mobiel loopt het kruimelpad van het forum niet helemaal lekker.
Zie  https://www.joomlacommunity.nl/forum/joomla/showcase/showcase-gasoline-directory-website
![20170102_142604](https://cloud.githubusercontent.com/assets/7062995/21589991/e018ae34-d0f7-11e6-890e-ee881a06f4c8.png)

**Comment by sanderpotjer** [comment]
@hvdmeer dat is niet zozeer het kruimelpad, maar navigatie naar volgende/vorige topic. Heb dit nu voor de mobiele weergave verborgen. Dank voor melden!
