### ISSUE TITLE
Locatie optie in profiel configuratie lijkt niet te werken.

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#247]
Op pagina
https://www.joomlacommunity.nl/forum/profile/edit#edit-location

Kun je een locatie instellen.
Dit kan door het adres in te voeren en ook door op de locatie bepalen knop te klikken.
Beide opties lijken niets te doen.
![2017-01-02 15_22_34-nederlands joomla forum](https://cloud.githubusercontent.com/assets/11913918/21590877/9cff5604-d0ff-11e6-8e6f-9f5978addf91.png)

**Comment by sanderpotjer** [comment]
Wat mij betreft is dat gewoon een input veld ipv automatisch opzoeken oid. Kan dat @hvdmeer?

**Comment by hvdmeer** [comment]
Het is een zoekveld zover ik weet. Ik zie een API foutmeldingoed,  waarschijnlijk moet er in het component een API ingevuld worden. Kan jij dat naar kijken @sanderpotjer ? Ik heb de rechten niet.

**Comment by sanderpotjer** [comment]
@hvdmeer ik dacht dat die rechten voor het forum team waren ingesteld, niet dus. Je moet er dus nu bij kunnen. Overigens staat er een API key ingevuld...

**Comment by hvdmeer** [comment]
@sanderpotjer Ik heb er naar gekeken en inderdaad staat alles goed zover ik het zie. Kan het zijn dat in de developers console de URL niet matcht? Deze dus: https://www.joomlacommunity.nl/forum/profile/edit#edit-location

`This API project is not authorized to use this API. Please ensure this API is activated in the Google Developers Console: https://console.developers.google.com/apis/api/geocoding_backend?project=_ For more information on authentication and Google Maps Javascript API services please see: https://developers.google.com/maps/documentation/javascript/get-api-key`

Want daar had ik laatst zelf een foutje in gemaakt voor een eigen site.

**Comment by sanderpotjer** [comment]
@hvdmeer de URL was juist, maar moest blijkbaar naast Google Maps ook de Geocode API activeren. Nu gedaan en lijkt te werken.
