### ISSUE TITLE
Stijlgids knop ??

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#250]
Er is een stijlgids knop op de site.
Waarschijnlijk is deze gebruikt tijdens het ontwikkelen.
In ieder geval toont de knop andere informatie dan een stijlgids.

![2017-01-02 15_34_06-stijlgids](https://cloud.githubusercontent.com/assets/11913918/21591055/0d866d80-d101-11e6-8e6c-15ec7fa617bd.png)

Alleen als je ingelogd bent natuurlijk.
Wellicht heb ik net iets meer rechten.
dan denk nog steeds onnodige knop

**Comment by sanderpotjer** [comment]
@conconnl die is te zien vanwege je rechten op de site. Maar menu is nu uitgeschakeld.
