### ISSUE TITLE
404's op joomlacommunity.nl

### ISSUE THREAD

**Issue by slibbe** [stichtingsympathy/joomlacommunity.nl#251]
Er zijn er natuurlijk meer, maar dit is een beginnetje.

Parent                                                       | Target
------------------------------------------------------------ | --------------------------------------------------------------------------------------------------------------
https://www.joomlacommunity.nl/templates/jc/css/template.css | https://www.joomlacommunity.nl/templates/jc/fonts/glyphicons-halflings-regular.eot
https://www.joomlacommunity.nl/templates/jc/css/template.css | https://www.joomlacommunity.nl/templates/jc/fonts/glyphicons-halflings-regular.eot#iefix
https://www.joomlacommunity.nl/templates/jc/css/template.css | https://www.joomlacommunity.nl/templates/jc/fonts/glyphicons-halflings-regular.woff2
https://www.joomlacommunity.nl/templates/jc/css/template.css | https://www.joomlacommunity.nl/templates/jc/fonts/glyphicons-halflings-regular.woff
https://www.joomlacommunity.nl/templates/jc/css/template.css | https://www.joomlacommunity.nl/templates/jc/fonts/glyphicons-halflings-regular.ttf
https://www.joomlacommunity.nl/templates/jc/css/template.css | https://www.joomlacommunity.nl/templates/jc/fonts/glyphicons-halflings-regular.svg#glyphicons_halflingsregular
https://www.joomlacommunity.nl/templates/jc/css/template.css | https://www.joomlacommunity.nl/templates/system/images/pdf_button.png
https://www.joomlacommunity.nl/nieuws | https://www.joomlacommunity.nl/joomla-gebruikersgroepen/regio-rotterdam/details/672-jug010-21-november-2016.html
https://www.joomlacommunity.nl/forum | https://www.joomlacommunity.nl/forum?format=feed&type=atom
https://www.joomlacommunity.nl/forum | https://www.joomlacommunity.nl/forum?format=feed&type=rss
https://www.joomlacommunity.nl/nieuws/joomlacommunity | https://www.joomlacommunity.nl/joomla-demo.html
https://www.joomlacommunity.nl/over-joomlacommunity | https://www.joomlacommunity.nl/docs.joomla.org
https://www.joomlacommunity.nl/nieuws/extensies | https://www.joomlacommunity.nl/www.joomlacommunity.eu/amsterdam

**Comment by sanderpotjer** [comment]
@slibbe dank! De meeste links zijn gefixed. Kan alleen niet vinden welke setting voor de RSS zorgt op het forum. @hvdmeer ben jij die tegengekomen?

**Comment by hvdmeer** [comment]
Ik heb net even gekeken maar zie niks daarvoor in EasyDiscuss. Kan het zijn dat de Joomla RSS gebruikt wordt?

**Comment by slibbe** [comment]
Nog een paar:

Parent                                                       | Target
------------------------------------------------------------ | --------------------------------------------------------------------------------------------------------------
https://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/arnhem-nijmegen/event/108-een-eigen-template-maken | https://www.joomlacommunity.nl/images/gebruikersgroepen/venues/Arnhem.jpg
https://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/heerenveen/event/109-droppics-fabrik-uwamp-en-oliebollen | https://www.joomlacommunity.nl/images/gebruikersgroepen/venues/Heerenveen.jpg
https://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/leiden/event/97-themler-templates-roeland-van-anholt | https://www.joomlacommunity.nl/images/gebruikersgroepen/venues/Leiden.jpg
https://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/maastricht/event/100-joomla-extensies | https://www.joomlacommunity.nl/images/gebruikersgroepen/venues/Maastricht.jpg
https://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/s-hertogenbosch/event/82-joomla-best-practices | https://www.joomlacommunity.nl/images/gebruikersgroepen/venues/Hertogenbosch.jpg
https://www.joomlacommunity.nl/nieuws/gebruikersgroepen/bussum | https://www.joomlacommunity.nl/joomla-gebruikersgroepen/regio-amsterdam.html
https://www.joomlacommunity.nl/nieuws/gebruikersgroepen/leiden | https://www.joomlacommunity.nl/joomla-gebruikersgroepen/regio-leiden/details/590-start-jug-leiden.html
https://www.joomlacommunity.nl/nieuws/gebruikersgroepen/leiden | https://www.joomlacommunity.nl/joomla-gebruikersgroepen/regio-leiden.html
https://www.joomlacommunity.nl/nieuws/gebruikersgroepen/rotterdam | https://www.joomlacommunity.nl/joomla-gebruikersgroepen/alle-bijeenkomsten.html
https://www.joomlacommunity.nl/nieuws/gebruikersgroepen/rotterdam | https://www.joomlacommunity.nl/www.joomlacommunity.eu/rotterdam
https://www.joomlacommunity.nl/nieuws/gebruikersgroepen/rotterdam | https://www.joomlacommunity.nl/joomla-gebruikersgroepen/details/12-jug010-bijeenkomst-22-juni-2010.html
https://www.joomlacommunity.nl/nieuws/gebruikersgroepen/rotterdam/1119-verslag-jug-rotterdam-13-december-2016 | https://www.joomlacommunity.nl/www.7strel.nl
https://www.joomlacommunity.nl/nieuws/gebruikersgroepen/rotterdam/1119-verslag-jug-rotterdam-13-december-2016 | https://www.joomlacommunity.nl/www.joomunited.com
https://www.joomlacommunity.nl/nieuws/gebruikersgroepen/zwolle | https://www.joomlacommunity.nl/index.php?option=com_gebruikersgroepen&view=categoryevents&id=5&Itemid=115
https://www.joomlacommunity.nl/nieuws/joomlacommunity | https://www.joomlacommunity.nl/joomla-gebruikersgroepen/details/165-joomla-nieuwjaarsborrel.html
https://www.joomlacommunity.nl/templates/jc/css/template.css | https://www.joomlacommunity.nl/templates/system/images/pdf_button.png

En nog een oud mail-adres op https://www.joomlacommunity.nl/agenda/joomla-gebruikersgroepen/heerenveen/event/109-droppics-fabrik-uwamp-en-oliebollen :
mailto:heerenveen@joomlacommunity.eu. 

En de atom & rss links.

**Comment by slibbe** [comment]
Waarom is deze nog open?

**Comment by hvdmeer** [comment]
Moet hij dicht? Dan gaat hij dicht!
