### ISSUE TITLE
[Forum] Automatische links

### ISSUE THREAD

**Issue by roland-d** [stichtingsympathy/joomlacommunity.nl#252]
Op deze pagina: https://www.joomlacommunity.nl/forum/joomla/showcase/showcase-gasoline-directory-website gebruikt iemand de afkorting **o.a.** dit wordt automatisch omgezet in een link op de website. Dat lijkt me niet de bedoeling ;)

**Comment by sanderpotjer** [comment]
@hvdmeer kan je deze ook opzoeken in de settings?

**Comment by hvdmeer** [comment]
@sanderpotjer Ik heb net gekeken maar zie zo 1-2-3 niet waar dit door geactiveerd wordt. Ik heb meteen maar even een vraagje op het stackideas forum geplaatst.

**Comment by hvdmeer** [comment]
@sanderpotjer Zij kunnen het niet reproduceren en vragen om toegang tot de website. Er is wel een update van ED beschikbaar, misschien deze eerst installeren?

**Comment by sanderpotjer** [comment]
@hvdmeer dat vragen ze helaas standaard... maar dat gaan we NIET doen (database van veel Joomla gebruikers). We gebruiken overigens de laatste versie, 4.0.11. Backend geeft valse warning. Zal zelf wel even zoeken hoe dit komt.

**Comment by hvdmeer** [comment]
Ik was het ook niet van plan die toegang te vragen.;)

**Comment by hvdmeer** [comment]
Ik heb het donker bruine vermoeden dat het toevoegen van de volgende link hierdoor ook niet goed gaat:
 https://tools.pingdom.com/#!/bKmJ4b/https://www.prettigovernachten.nl

Dit gaat bij stackideas.com zelf een in hun online demo wel goed.

**Comment by sanderpotjer** [comment]
Heb het probleem gevonden, en is ook in hun eigen forum: https://stackideas.com/forums/unwanted-url-in-text

**Comment by sanderpotjer** [comment]
Kan het pingdom link issue overigens niet meer dupliceren, zonde dat we topic hebben verwijderd ;-) http://joomlacommunity.dev/forum/test-forum/testing-link

**Comment by hvdmeer** [comment]
Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.

Goed gevonden Sander!

**Comment by sanderpotjer** [comment]
Net even getest, inmiddels verholpen.
