### ISSUE TITLE
[Forum] Topics in container

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#256]
Bij het importeren van de oudere topics zijn zo te zien de containers omgezet naar categorieen om de import te vergemakkelijken. 

@sanderpotjer Kan ik de topics daarin naar de juiste categorieen verplaatsen en er weer containers van maken?

**Comment by sanderpotjer** [comment]
@hvdmeer welke containers bedoel je dan? Er was sowieso ook een categorie gemarkeerd als container, terwijl dat volgens mij niet de bedoeling was (geen sub cats)

**Comment by hvdmeer** [comment]
Ah, ik zie dat het alleen om Joomlacommunity.nl gaat. De overige zijn nog wel containers. 
Blijkbaar moet ik nog even wennen aan de weergave van onderwerpen.

**Comment by sanderpotjer** [comment]
Die van joomlacommunity.nl was al geen container ;-)

Maar prima wel aan te passen, lijkt mij wel zo duidelijk. Wel dan een subcategorie voor JoomlaCommunity.nl zaken maken denk ik?

**Comment by hvdmeer** [comment]
Komt goed. 👍
