### ISSUE TITLE
Instellingen van Akeeba Backup

### ISSUE THREAD

**Issue by MartijnMaandag** [stichtingsympathy/joomlacommunity.nl#259]
In de backend is de map waar de back-ups worden weggeschreven niet benaderbaar. Het aanpassen van dit pad naar [DEFAULT_OUTPUT] verandert dat niet. Als ik de configuratiewizzard draai dan krijg ik de volgende boodschap:
Akeeba Backup could not find a writable output and temporary directory. Please give write permissions to the administrator/components/com_akeeba/backup directory and run this wizard again.

De log en temp mappen binnen Joomla staan volgens mij goed.
Maprechten in Joomla zien er goed uit.

**Comment by sanderpotjer** [comment]
@MartijnMaandag hebben we Akeeba backup eigenlijk wel nodig? Server bestanden staan in git, en van de database wordt door Byte elke 3 uur backup gemaakt.

**Comment by MartijnMaandag** [comment]
Aangezien ik nog steeds niet weet hoe ik met git kan werken en ik af en toe wel iets wil uittesten (bijvoorbeeld hoe de Engelse taalbestanden zich gedragen) vind ik Akeeba wel handig.
Ik heb wel een oude versie van de site, dus ik kan voorlopig wel verder.
Iets anders is dat er wel meer rare dingen gebeuren in de Admin: EasyDiscuss mekkert bijvoorbeeld om een update terwijl de laatste versie er staat.

**Comment by sanderpotjer** [comment]
@MartijnMaandag helder. Wil wel voorkomen dat er versies van de site (met daarin alle users daarin) gaan rondzwerven, dus moeten niet zomaar iedereen daarbij toegang geven. En even uitwerken waar je lokaal op moet letten qua mailverzending, want niet de bedoeling dat lokale sites mail gaan verzenden voor melding nieuwe topics enzo ;-)

**Comment by sanderpotjer** [comment]
@MartijnMaandag backup maken zou nu moeten werken
