### ISSUE TITLE
WENS: Zoeken vanuit frontpage klikbare url

### ISSUE THREAD

**Issue by bamisalami** [stichtingsympathy/joomlacommunity.nl#262]
Geen bug maar ik betrap me op het volgende.
Vanuit de frontpage zoek ik.
Zoals het hoort komen de berichten ook van het forum in het zoekresultaat.
Nu klik ik eigenlijk (en ja dat is mijn fout) althans ik probeer altijd op het url te klikken.
![logog](https://cloud.githubusercontent.com/assets/713708/21713152/bcfd81be-d3f8-11e6-8d2f-4ee92a955b4d.JPG)

Maarja dat werkt niet. Het klikken op een onderwerp werkt wel maar ik zou het fijn vinden als de getoonde url's ook klikbaar worden.

**Comment by sanderpotjer** [comment]
@bamisalami dat is inderdaad niet handig (is zelfs standaard zo in Joomla....) maar hebben het aangepast, URLs zijn nu klikbaar. 

Dank voor je feedback!
