### ISSUE TITLE
WENS: Agenda met kalender

### ISSUE THREAD

**Issue by bamisalami** [stichtingsympathy/joomlacommunity.nl#263]
Bij agenda zie je nu een lange lijst met aan algemeen overzicht. 
Persoonlijk voor mij een te grote lijst waar ik niets mee doe.
Wellicht een kalenderweergave erbij zetten. Dat je kan zien op welke dagen er iets is.
Ook dit blijft persoonlijk maar als je dan zelfs zou kunnen selecteren op gebruikersgroep zodat je ziet wanneer de volgende 'dates' zijn lijkt me sneller en handiger werken om even snel te kijken of je kan komen.

**Comment by sanderpotjer** [comment]
@bamisalami de kalender weergave komt eraan, maar was nog niet gereed qua layout, zie #177
