### ISSUE TITLE
Geen markering van goede antwoord

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#265]
In dit topic is mijn reactie als goede antwoord gemarkeerd (hier kreeg ik een email over):
https://www.joomlacommunity.nl/forum/joomla/overige-vragen/hulp-nodig-met-css

Het topic staat ook als "Opgelost" gemarkeerd, mijn bericht staat echter niet als "De oplossing" gemarkeerd. Misschien een goed idee om dit ook te doen? Zo is wel direct duidelijk wat de oplossing is.

**Comment by hvdmeer** [comment]
Ik kan dat in ieder geval niet instellen.

**Comment by sanderpotjer** [comment]
Volgens mij heeft de topic starter dat gewoon na de mail notificatie aangepast, want hier staat een antwoord van. mij wel als "oplossing" gemarkeerd: https://www.joomlacommunity.nl/forum/joomla/webhosting/betere-maar-betaalbare-provider

**Comment by hvdmeer** [comment]
Ik zou graag zien dat een moderator wel een antwoord kan aanwijzen en heb met de instellingen bekeken maar daarvoor niks kunnen vinden. 

Indien de topiceigenaar zelf niet reageert kan dan alsnog hier een antwoord uitgelicht worden. Dus vandaar dat ik de tag stackideas heb toegevoegd.

**Comment by hvdmeer** [comment]
Hmm, op mobiel heb ik die mogelijkheid niet maar op de pc wel. Is dat een template issue?
