### ISSUE TITLE
Opmaak blockquote EasyDiscus

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#266]
Op dit moment is er geen duidelijk verschil zichtbaar tussen tekst en een quote.

Zou iemand hieraan wat meer opmaakaan toe kunnen voegen zodat deze wat meer opvalt?

Wellicht:
padding-left: 2
font-style: italic

**Comment by hvdmeer** [comment]
Hmm. Er zit nu wel weer opmaak. Sluiten dus.

**Comment by hvdmeer** [comment]
En weer open, de quote ziet er weer gewoon als tekst uit. @n9iels weet jij hier wat van?

**Comment by n9iels** [comment]
Heb je een voorbeeld hans?

**Comment by hvdmeer** [comment]
Zeker @n9iels. Al het engelstalige is een quote: https://www.joomlacommunity.nl/forum/joomlacommunity-nl/gebruikersgroepen-nederland-en-belgie/jug-promo-in-joomla-community-magazine

**Comment by n9iels** [comment]
@hvdmeer ik heb styling toegevoegd aan de quotes. Enkel quotes in reacties op een bericht bevatte styling, niet quotes in het eerste bericht van een topic.

@sanderpotjer kun jij deze uitrollen? Heb tevens een paar updates uitgevoerd. Staat allemaal ind e develop branch

**Comment by sanderpotjer** [comment]
@n9iels code is uitgerold, thnx!
