### ISSUE TITLE
[EasyDiscus] Update beschikbaar

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#278]
Inmiddels is al even een nieuwe versie beschikbaar, v 4.0.12. Hier staat een overzicht van de wijzigingen:
https://stackideas.com/changelog/easydiscuss

Wie kan beoordelen wie of deze geïnstalleerd kan worden?

**Comment by SpiritJC** [comment]
Ik neem aan, dat er geen core hacks gebruikt zijn en dat een update niets in de weg staat. 
@sanderpotjer weet waarschijnlijk meer.

**Comment by sanderpotjer** [comment]
Extensie is bijgewerkt
