### ISSUE TITLE
[RSEvents] bewerken evenement groter invoerscherm

### ISSUE THREAD

**Issue by roland-d** [stichtingsympathy/joomlacommunity.nl#279]
In RSEvents kan je een omschrijving van het evenement plaatsen, alleen is dit invoerscherm wel erg klein.

![image](https://cloud.githubusercontent.com/assets/359377/23402164/b24c4e5e-fdaa-11e6-814e-e2de09a36e2b.png)

Het zou mooi zijn als er, zoals in standaard Joomla, een knop in de knoppenbalk is om het schermvullend te maken.

**Comment by hvdmeer** [comment]
@n9iels of @hans2103 kunnen jullie die knop toevoegen aan de editor? Ik ben er in ieder geval voor, het is niet overzichtelijk nu.
Of dat het aanpassen van het formaat van de editor mogelijk wordt door het slepen rechtsonderin, dat zou ook een goede optie zijn.

**Comment by hvdmeer** [comment]
Zeg @conconnl , die is toch een eigenschap van RSEvents? Ik zag bij mij niet zo snel een mogelijkheid om dit invoerscherm te vergroten, weet jij hier meer van?

**Comment by conconnl** [comment]
Er is een optie in de configuratie
<img width="419" alt="image" src="https://user-images.githubusercontent.com/11913918/42281245-3c225756-7fa3-11e8-8dab-c06565ca6b6d.png">

Ik weet niet wat het doet.
Kan ook niet vinden hoe ik een evenement kan plaatsen, dus kan het ook niet bekijken op de frontend.

**Comment by hvdmeer** [comment]
Ik was geloof ik zelf niet helemaal helder. Het zou mooi zijn als dit invoerscherm vergroot kan worden door in de hoek het te verslepen.

Maar de knop die bedoeld word is deze:
![jce-sink](https://user-images.githubusercontent.com/7062995/42288109-b16a54b2-7fb9-11e8-9a67-8c562e1418e4.png)

Als iemand met Admin rechten deze in het JCE-profiel van de betreffende Joomla gebruiker-groepen kan toevoegen dan is het in ieder geval mogelijk om dit kleine invoerscherm op volledig scherm te zetten.

**Comment by MartijnMaandag** [comment]
Ik heb de knop toegevoegd.

**Comment by hvdmeer** [comment]
Gevonden! Ik sluit deze issue meteen ervan uitgaande dat Roland deze ook heeft.
