### ISSUE TITLE
[Informatie] - Afspraken & Besluiten / To-Do - Gebruikersgroepen

### ISSUE THREAD

**Issue by sanderpotjer** [stichtingsympathy/joomlacommunity.nl#28]
Aantekeningen van Edith:

15 januari 2016 - Edith van Leeuwen & Patrick Smits
Opzet sessie Gebruikersgroepen
## Gebruikersgroepen
-   Algemene info
-   Overzicht JUG’s (lijst)
## Menukeuzes

Bijeenkomsten
-   Gebruikersgroepen
-   PBF
-   Developersgroup
-   Joomladagen

Locaties
-   Overzichtkaartje Nederland
-   Kaartje met Joomla logo t.b.v. JUG Locaties! .png bestand

Agenda
-   Per groep te filteren
-   Geen gehele lijst meer met alle bijeenkomsten (kijkt toch niemand meer naar)
-   Archief actief laten – hierin het verslag ook te koppelen en terug te lezen
-   Reacties op verslagen toevoegen

Apart / Gastsprekers
-   Overzicht van gastsprekers
-   Naam, onderwerpen waarop men uitgenodigd kan worden, bereid te komen of via digitaal?, wenst de gastspreker een vergoeding (kilometers)
-   De gastspreker kan zich zelf registreren

Apart/ Documenten
-   Info t.b.v. organisatie – hoe organiseer ik een JUG
-   Persbericht 
-   Plek voor uitnodigingen bijeenkomsten – borrel / BBQ? 

Nieuwsbrief? Open of besloten per JUG?
-   AcyMailing gebruiken, zodat voor meerdere doeleinden niet alleen de JUGs nieuwsbrieven verzonden kunnen worden.

**Standaard RSEvents Groep configuratie**
- Groepsnaam is JUG (Bijv. Breda)
- Groep lid is Joomla Groep (Bijv. Breda)
- **_Geselecteerde rechten_**
1. Gebruikers in deze groep kunnen evenementen bewerken - "Ja"
2. Gebruikers in deze groep kunnen evenementen plaatsen - "Ja"
3. Gebruikers in deze groep kunnen terugkerende evenementen plaatsen - "Nee"
4. Evenement vereist moderatie - "Nee"
5. Gebruikers in deze groep kunnen evenementen verwijderen - "Ja"
6. Gebruikers in deze groep kunnen zich inschrijven - "Ja"
7. Gebruikers in deze groep kunnen hun inschrijving annuleren - "Ja"
8. Gebruikers in deze groep kunnen evenement bestanden downloaden - "Ja"
9. Gebruikers in deze groep kunnen evenement bestanden uploaden - "Ja"
10. Gebruikers in deze groep kunnen frontend opties wijzigen. - "Ja"
11. Gebruikers in deze groep kunnen categorieën aanmaken - "Nee"
12. Beperkte categorieën - Bijv. Breda
13. Nieuwe tags vereisen moderatie - "Nee"
14. Gebruikers in deze groep kunnen locaties aanmaken - "Nee"
15. Gebruikers in deze groep kunnen locaties bewerken - "Nee"

**Comment by hvdmeer** [comment]
Mailchimp? Is dat handiger dan AcyMailing? Want met Mailchimp kan je niet makkelijk sitecontent toevoegen.

**Comment by pjasmits** [comment]
dan zou je eerst moeten inventariseren of de JUG's (die daar mee moeten gaan werken) over willen naar Acymailing.

**Comment by hvdmeer** [comment]
Wij gebruiken op jugan.nl al Acymailing, dus andersom werkt het ook zo. ;)

**Comment by Stitch123** [comment]
Hoi heren,
Ik bedoelde hiermee eigenlijk gewoon een 'nieuwsbrief-functie'.....ik werk zelf veel met MailChimp vandaar....maar Acymailing zou ook een optie kunnen zijn....dat moeten we even overleggen. Het ging er mij vooral over dat we dit niet zouden vergeten mee te nemen in de opzet.
Groetjes, Edith

**Comment by hvdmeer** [comment]
Ter overweging:
Bij de betaalde versie van Acymailing (vanaf essential) kan je ook de RSEvents Pro evenementen via tags in de mailings opnemen via [een plugin](http://www.acyba.com/srv/www/vhosts/www.acyba.com/www/acymailing/423-acymailing-plugin-rseventspro.html). Misschien handig bij het versturen van aankondigingen van welke JUG's wanneer een bijeenkomst hebben in de komende maand bijvoorbeeld.
Vanaf Essential zijn o.a. de volgende opties ook beschikbaar: 
* [Forward Capability](http://www.acyba.com/acymailing/8-acymailing/80-acymailing-plugin-online.html), misschien iets om makkelijk meer gebruikers te bereiken? Vanaf Enterprise kan je daarvan statistieken inzien.
* Automatic send process
* Spam test
* DKIM

**Comment by conconnl** [comment]
Als Edith in overleg met de andere organisatoren besluit dat we AcyMailing gaan gebruiken ben ik ook voorstander van de betaalde versies vanwege de extra veiligheid opties en koppel functionaliteiten.
We krijgen in ieder geval als wij willen een kortingscode van Acyba, dus die paar tientjes die je dan per jaar moet betalen voor alle mogelijkheden lijkt mij ook geen probleem.

**Comment by hans2103** [comment]
Zou tof zijn dat ze ons sponsoren en Acymailing cadeau doen

Op vr 22 apr. 2016 om 10:19 schreef Wilco Alsemgeest <
notifications@github.com>

**Comment by conconnl** [comment]
Dat willen ze niet, zonder allemaal speciale voorwaarden.
Zoals in elke mail reclame, logo op verschillende plekken op de website.
Ze eisen behoorlijk veel ten opzicht van de prijs dat de extensie kost.

**Comment by hvdmeer** [comment]
Op verschillende plekken hun logo? Ze ondersteunen alle JUG's (hoeveel ook alweer?) in Nederland hiermee, dat zou toch een mooi gebaar zijn? Als ik me niet vergis stellen sommige ontwikkelaars hun extensie gratis beschikbaar zonder eisen. (oké en anderen vast weer met eisen).

**Comment by conconnl** [comment]
Ja, ze willen op de website op 2 plekken permanente zichtbaarheid van hun logo en in elke nieuwsbrief een vermelding dat hun de extensie beschikbaar hebben gesteld.
De extensie kost maar 89 euro en ze willen wel een coupon code geven van 30 procent ofzo.
De stichting vindt het geen probleem op de extensie te kopen als we de professionele versie nodig hebben, dan zal het 60 euro zijn, dat met zo'n 15 JUGs is het ook geen zware kostenpost.

**Comment by pjasmits** [comment]
Ik zou een beetje reclame op de site niet erg vinden. Misschien moet daar toch eens wat meer over nagedacht worden. Jaarlijks wordt er veel moeite gedaan om extra sponsors voor de joomladagen te krijgen. Met sponsoring op de site zou dit makkelijker zijn is mijn mening. En is 1 schaapje over de brug ...

**Comment by conconnl** [comment]
Er is een verschil tussen reclame en advertenties.
Op de huidge website worden advertenties getoond, waar geld mee binnengehaald wordt.
Reclame levert alleen maar een beetje korting op.
Als je voor 60 euro permanente reclame moet tonen i.p.v. advertenties van verschillende organisaties waar meer geld mee verkregen wordt, zoals Affliate systemen.
Ga je je doel voorbij.

Ik verdien met mijn website, zonder dat ik er wat voor doe en veel bezoekers heb al 300 euro per jaar aan de affliate koppeling van RSJoomla!. Dan praat je over een banner op een verborgen pagina.
Als de advertentie systeem van de huidige site geintegreerd wordt in de nieuwe site en je hebt daar Affliate advertenties van RSJoomla!, Hikashop en andere, plus de advertenties van mensen die dit aanvragen komt er veel meer geld binnen.

Ik weet niet hoe dit op dit moment binnen de Stichting geregeld is, maar actief hiermee omgaan levert behoorlijk wat winst op en in de tijd dat ik de advertenties beheerde bij DutchJoomla! ging toch over een paar duizend euro per jaar.

Kortom:
* AcyMailing kopen
* In de nieuwsbrieven advertenties meenemen van organisaties.
* Advertentie systeem op de website met roterende banners

**Comment by hans2103** [comment]
Mijn excuses dat ik met mijn vraag de knuppel in het hoenderhok gegooid
heb.

Wat mij betreft geen reclame van extensies op de website als ze geen
sponsorpakket afgenomen hebben.
Onze namen staan immers ook niet op de site. (alhoewel... een humans.txt in
de root is nog te overwegen)

Gewoon zelf de betaalde versie aankopen.

Op vr 22 apr. 2016 om 13:24 schreef Patrick Smits <notifications@github.com

**Comment by hvdmeer** [comment]
Excuses zijn niet nodig hoor Hans, naar mijn bescheiden mening. Het is goed dat de opties besproken worden, dit is gewoon een onderdeel daar van. Persoonlijk, ook met de punten die Wilco aandraagt zou dan de Enterprise versie een mooie aanschaf zijn.

**Comment by hans2103** [comment]
ideetje: Erik van Doorne (evdoorne@mastersofmedia.nl) heeft de Multisite versie van Acymailing gekocht. Dit is de "AcyMailing Enterprise" maar dan met de mogelijkheid tot installatie op meerdere domeinen. 
Hij verkoopt deze enterprise versie voor gereduceerd tarief door aan zijn klanten. Wij kunnen ook een klant van hem worden. 
https://www.acyba.com/acymailing/unlimited.html

**Comment by conconnl** [comment]
He Hans, is een idee.
Wil hij het niet gewoon sponsoren aan ons ?
Hij hoeft geen werk te verrichten, als wij aan de updates kunnen komen kunnen wij de rest doen.

Kun je dat met hem bespreken?

**Comment by hans2103** [comment]
Erik moet er ook gewoon van leven. Lijkt me beter als Stichting Sympathy gewoon een rekening krijgt voor Acymailing Enterprise. Dan kan Erik altijd nog besluiten om sponsor te worden van Stichting Sympathy. 
De jaarlijkse kosten voor Acymailing Enterprise via Erik van Doorne bedragen: €45,- excl. BTW/jr.

**Comment by conconnl** [comment]
Hoi Hans,

Daar heb je een punt. 
Laten dit in onze achterhoofd houden. 
Edith moet nog besluiten of AcyMailing de gewenste richting is. 

Groeten,
Wilco

**Comment by hvdmeer** [comment]
Wie? @Stitch123 ? (ff taggen) :)

**Comment by Stitch123** [comment]
Hallo Hans,

Wat wil je dat ik doe?
Is even niet duidelijk....sorry....

Groetjes,
Edith


Met vriendelijke groet,
Nico van Leeuwen

De Linie ICT
info@delinie-ict.nl
www.delinie-ict.nl

*KvK* : 51721775
*BTW* : NL180764184B01
*IBAN* : NL27RABO0159942675
*BIC* : RABONL2U

2016-04-25 20:58 GMT+02:00 Hans <notifications@github.com>:

**Comment by hvdmeer** [comment]
Er staat nog open of het Acymail of iets anders wordt @switch123. Ik dacht, ik traag je even zodat je hier de discussie kan meelezen. :)

**Comment by superknutsel** [comment]
Ok ! Bedankt!


Met vriendelijke groet,
Nico van Leeuwen

De Linie ICT
info@delinie-ict.nl
www.delinie-ict.nl

*KvK* : 51721775
*BTW* : NL180764184B01
*IBAN* : NL27RABO0159942675
*BIC* : RABONL2U

2016-04-26 10:30 GMT+02:00 Hans <notifications@github.com>:

**Comment by hvdmeer** [comment]
Vraagje, in het huidige forum is over het algemeen weinig interactie in de categorie  Gebruikersgroepen. Elke JUG heeft daar een eigen stukje. Op dit moment heb ik in het nieuwe forum nog niks ingericht voor de gebruikersgroepen.

Zal ik het bij één categorie Gebruikersgroepen Nederland en België houden of is er wens om alle JUG's een eigen plekje op het forum te geven?

**Comment by Stitch123** [comment]
Hoi Hans,

Dat is een goede....iedereen kan de eigen JUG sowieso al mailen met
zijn/haar vraag....het lijkt mij dat we hier gewoon 'algemene' punten
kunnen melden of gemeld krijgen.
Hou het inderdaad maar bij 1 categorie hoor!

Groetjes,
Edith



Met vriendelijke groet,
Edith van Leeuwen

De Linie ICT
edith@delinie-ict.nl
www.delinie-ict.nl

*KvK* : 51721775
*BTW* : NL180764184B01
*IBAN* : NL27RABO0159942675
*BIC* : RABONL2U

Op 29 april 2016 12:29 schreef Hans <notifications@github.com>:

**Comment by hans2103** [comment]
nogmaals: 
Als besloten wordt om met AcyMailing Enterprise te gaan werken wil ik jullie vragen om contact op te nemen met Erik van Doorne. Hij heeft AcyMailing MultiSite gekocht en verkoopt deze voor jaarlijkse fee (voor updates enzo) door naar zijn klanten. Stichting Sympathy kan dan klant zijn van Erik van Doorne. 

Aan wie is het om het besluit te nemen om met AcyMailing Enterprise te werken?

**Comment by hvdmeer** [comment]
Ik ben voor, ik zie er voordelen van in boven een los systeem. Makkelijk koppelen van de agenda's van RS. :)

**Comment by BiancaCrown** [comment]
Hoi Hans , graag wil ik je laten weten dat ik ook voor A-C Mailing ben.
Bianca

Op dinsdag 10 mei 2016 heeft Hans Kuijpers <notifications@github.com> het
volgende geschreven:

> nogmaals:
> Als besloten wordt om met AcyMailing Enterprise te gaan werken wil ik
> jullie vragen om contact op te nemen met Erik van Doorne. Hij heeft
> AcyMailing MultiSite gekocht en verkoopt deze voor jaarlijkse fee (voor
> updates enzo) door naar zijn klanten. Stichting Sympathy kan dan klant zijn
> van Erik van Doorne.
>
> Aan wie is het om het besluit te nemen om met AcyMailing Enterprise te
> werken?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/stichtingsympathy/joomlacommunity.nl/issues/28#issuecomment-218140239>
>


-- 
*Met vriendelijke groet,*
*Bianca Crown*

BC Webdesign <http://www.zonderzorgonline.nl>
biancacrown@gmail.com
06-38208208
*Lid van:*

**Comment by hvdmeer** [comment]
Even mensen "lastig" vallen. @sanderpotjer @Stitch123 
Hoe zit het met besluitvorming over op welke manier de mailings verzorgd worden? Dan kan dat daarna ook opgepakt worden.

**Comment by sanderpotjer** [comment]
Als Acymailing aan de wensen en eisen voor het versturen van mailings voldoet is dat prima om te gebruiken. Ik heb echter nog niet de specs gezien waaraan het moet voldoen?

Is het bijvoorbeeld mogelijk om meerdere maillijsten te hebben waarbij een JUG alleen bij de eigen lijst kan om mailadressen in te zien en mailings te versturen naar de eigen groep? (en dus niet alle mailadressen uit de database kan plukken en spammen in ergste geval...)

**Comment by hvdmeer** [comment]
Volgens mij moet het afschermen van maillijsten op de frontend mogelijk zijn gezien dit topic:
https://www.acyba.com/forum/5-acymailing-how-to/70366-acymailing-front-end-multiple-users.html#79684

Ik heb alleen ervaring in de gratis versie waar dit niet in zit dus kan het niet controleren.

**Comment by sanderpotjer** [comment]
@hvdmeer gaat er met name om dat de JUG organisatoren een nieuwsbrief kunnen sturen, maar alleen naar de eigen JUG. Dat zal waarschijnlijk via backend moeten. Als het even kan dan bij voorkeur niet toegang tot alle maillijsten en abonnees.

**Comment by conconnl** [comment]
Volgens mij zijn dat soort dingen ook allemaal mogelijk.
Ik zal dit weekend eens door de Demo sites heen gaan bij AcyMailing

**Comment by hvdmeer** [comment]
Snap ik @sanderpotjer, wat ik zo lees kan dit ook via frontend. Het moet in ieder geval mogelijk zijn bij Acymailing. Inderdaad hoeven de JUG organisatoren alleen hun eigen maillijst te zien.
