### ISSUE TITLE
"Laad meer" link op de agenda pagina doet niets

### ISSUE THREAD

**Issue by roland-d** [stichtingsympathy/joomlacommunity.nl#283]
Op de agenda pagina (https://www.joomlacommunity.nl/agenda) staat helemaal onderaan een **Laad meer** link. Bij hover wordt de cursor geen handje/pijltje en de link zelf lijkt niets te doen. Er wordt wel een AJAX call gedaan maar de informatie die terug komt lijkt hetzelde als wat er al op de pagina staat.

**Comment by sanderpotjer** [comment]
Fixed
