### ISSUE TITLE
Logo past niet helemaal

### ISSUE THREAD

**Issue by roland-d** [stichtingsympathy/joomlacommunity.nl#284]
Het logo past niet helemaal, zie schermprint:
<img width="349" alt="image" src="https://cloud.githubusercontent.com/assets/359377/25408790/8597e652-2a0f-11e7-9716-92cf2d87dc32.png">

Het woord **portal** in de tagline wordt afgekapt.

**Comment by hans2103** [comment]
@roland-d ik kan dit issue niet meer reproduceren. Jij wel?

**Comment by roland-d** [comment]
Na meer dan een jaar kan ik het ook niet reproduceren :)
