### ISSUE TITLE
[DOWNLOADS] - New folders aren't displayed

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#288]
@sanderpotjer 

Can you fix the downloads template override so new created root folders are displayed as well on the page https://www.joomlacommunity.nl/downloads
Or make it possible that "Extensie Vertalingen" are displayed

**Comment by sanderpotjer** [comment]
@conconnl was geen template override voor nodig, wel menu en module. Deze zijn nu aangemaakt: http://joomlacommunity.dev/downloads/extensie-vertalingen

**Comment by conconnl** [comment]
@sanderpotjer dankjewel.
Het ziet er goed uit en werkt.
Enige nadeel is, dat ook al voor je in DocMan een externe URL in dan opent hij niet in een nieuw window.
Als ik me niet vergis, vindt jij dit geen probleem. Dan is het in ieder geval benoemt.
