### ISSUE TITLE
[Forum] Updaten Easydiscuss

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#289]
Ik zie dat we inmiddels twee versies achterlopen op de beschikbare downloads. Is het mogelijk dat het forum geupdate wordt?

**Comment by sanderpotjer** [comment]
@hvdmeer was er al eerder mee bezig geweest, maar subscription was verlopen... Toen hadden ze het toegevoegd, maar aan verkeerde account. Anyway, veel mails kort: we hebben weer actieve subscription en update is nu gedaan :)

**Comment by hvdmeer** [comment]
Oh ja, subscription. Ik had die gisteren toegevoegd aan ons account of iets dergelijks. Ik zal nog een licentie over en het account was niet gekoppeld.
