### ISSUE TITLE
Template Easydiscuss

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#29]
Binnen Easydiscuss zijn er vijf templates geïnstalleerd die gebruikt kunnen worden. Op dit moment staat Simplistic ingesteld. 

Kan er gekeken worden naar welke template het beste past bij de nieuwe website en ook welke aanpassingen nog gedaan moeten worden?

**Comment by sanderpotjer** [comment]
@hvdmeer volgens mij is de zinc template het beste uitgangspunt om te gebruiken.

**Comment by hvdmeer** [comment]
Dit is inderdaad wel wat meer 2016, hij staat daar weer op.

**Comment by n9iels** [comment]
Ik heb de forum tempalte "jc" gevonden en actief gemaakt. (Sander heb jij deze ooit gemaakt?) Het ziet er nog niet helemaal goed uit, maar het lijkt me een goede basis om verder mee te werken :)

**Comment by sanderpotjer** [comment]
@n9iels zoals vandaag even gezegd; een eigen template override voor forum gaat veel werk worden (veel views) en ook op lange termijn niet helemaal praktisch. Beter is zoveel mogelijk met CSS te doen. Laten we dit punt even parkeren totdat we easydiscuss 4 hebben, dan gaan we vanuit daar werken, ben er mee bezig die versie te krijgen voor JC.

**Comment by hvdmeer** [comment]
Kleine bugmelding van Easydiscuss op Joomla! 3.5, bij het opslaan in de backend van een instelling krijg je een mooie foutmelding, hier de melding van StackIdeas:
http://stackideas.com/forums/easydiscuss-3-2-9744-joomla-3-5-quick-fix

Ik kwam hier net achter toen ik de template van Easydiscuss weer terug op Zinc wilde zetten. Er is een patch beschikbaar maar aangezien het de bedoeling is dat we toch naar ED4.0 Beta 2 of verder willen gaan doe ik hier even niets aan.

**Comment by conconnl** [comment]
@sanderpotjer @hvdmeer 
Template WireFrame is de template die al een tijd aan staat.
Hierop zijn nu ook de template overrides gemaakt.
We zitten nu tevens op een niet beta versie.

Als toch een andere template gebruikt moet worden, willen we deze informatie snel ontvangen.
Dan kunnen we de template overrides nog bijwerken, naar de andere template daarna verder werken aan het uiterlijk.
Ik verwacht dat WireFrame goed genoeg is als basis
