### ISSUE TITLE
Weergave UTF-8 op IE11

### ISSUE THREAD

**Issue by pe7er** [stichtingsympathy/joomlacommunity.nl#291]
Van Jelle hoorde ik dat hij een probleem heeft in IE11 met de weergave van de https://www.joomlacommunity.nl/ site

In het artikel https://www.joomlacommunity.nl/nieuws/gebruikersgroepen/360-dutch-joomla-developers/1326-verslag-dutch-joomla-developers-api-en-saml
toont IE11 de speciale tekens niet goed:

> €œOkidokiâ€ is een nieuwe tool die real-time wysiwyg pageviews maakt door het plaatsen (drag-and-drop) van containers op een pagina. Deze containers â€“ in essentie mini-templates â€“ zijn direct gekoppeld aan Ã©Ã©n of ..

Het kan eraan liggen dat IE11 de pagina niet als UTF8 herkent.

Kan iemand op de site / in de template de UTF-8 definitie aanpassen van
`<meta http-equiv="content-type" content="text/html; charset=utf8" />`
naar
`<meta http-equiv="content-type" content="text/html; charset=utf-8" />`
(dus een streepje tussen utf en 8)?

**Comment by hans2103** [comment]
wijzigingen naar live gehaald. @810 is het issue bij jou verholpen?

**Comment by renekreijveld** [comment]
In mijn IE11  op WIndows 7 ziet het er nu prima uit.

**Comment by 810** [comment]
ja, is nu goed.

**Comment by pe7er** [comment]
Bedankt voor het aanpassen @hans2103 !
En @renekreijveld + @810 voor het testen + melden.
