### ISSUE TITLE
Foutboodschap "Kan de map niet verwijderen"

### ISSUE THREAD

**Issue by MartijnMaandag** [stichtingsympathy/joomlacommunity.nl#292]
Ik krijg een foutmelding op de volgende URL:
https://www.joomlacommunity.nl/nieuws/gebruikersgroepen/breda/1327-programma-2e-hikashop-dag-bekend
Ik krijg het niet in Firefox, maar wel met Edge, Chrome en op mijn telefoon.
Foutboodschap is: Waarschuwing Joomla\CMS\Cache\Storage\FileStorage::_deleteFolder JFolder: :verwijderen: Kan de map niet verwijderen. Pad: /home/users/jooqlftp/joomlacommunity.nl/public_html/cache/com_content

**Comment by MartijnMaandag** [comment]
Heb inmiddels de cache geschoond in het beheergedeelte en boodschap is weg.

**Comment by MartijnMaandag** [comment]
Toch nog even: waarom kwam deze boodschap op de frontend?
Volgens mij (en de instellingen?) kan dit toch niet? 
Hele pad wordt getoond aan gebruikers.

**Comment by superknutsel** [comment]
Hebben jullie het hier over?

https://www.joomlacommunity.nl/nieuws/gebruikersgroepen/
breda/1333-verslag-jug-breda-d-d-31-oktober-2017

*Waarschuwing*

Joomla\CMS\Cache\Storage\FileStorage::_deleteFolder JFolder: :verwijderen:
Kan de map niet verwijderen. Pad: /home/users/jooqlftp/joomlacom
munity.nl/public_html/cache/com_content

Met vriendelijke groet,
Edith van Leeuwen

De Linie ICT
edith@delinie-ict.nl
www.delinie-ict.nl
0162-820235

*KvK* : 51721775
*BTW* : NL180764184B01
*IBAN* : NL27RABO0159942675
*BIC* : RABONL2U

Op 20 november 2017 om 16:12 schreef Martijn Maandag <
notifications@github.com>:

**Comment by MartijnMaandag** [comment]
Ja, die ook.
Dit mag toch niet op de website getoond worden.

**Comment by sanderpotjer** [comment]
De cache staat nu uit, later moment induiken waarom het mis gaat.
