### ISSUE TITLE
Vreemde filterbalk

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#294]
Ik zie sinds de security update van deze week ineens een extra balk onder de topic filters staan. Ik heb er vanuit het forum er nog geen opmerkingen over gehoord maar ik neem aan dat de "gewone" geregistreerden deze balk ook zien.

![2018-01-filter-bardropdown](https://user-images.githubusercontent.com/7062995/34795318-1d34d466-f652-11e7-90f1-90446f28e67b.png)

In de instellingen van EasyDiscuss kon ik niet zo snel vinden waar deze uitgeschakeld kan worden. Mijn vraag is, kan iemand controleren of een gewone geregistreerde deze filter ook zit?

En indien dat het geval is, hoogstwaarschijnlijk, waar kan dit uitgeschakeld worden...

**Comment by GASOLINE** [comment]
Ik, als gewone gebruiker zie die balk ook. Lijkt me geen probleem, handige feature toch die selectie?

**Comment by hvdmeer** [comment]
Het is meer dat ik er zelf geen nut van inzie. Maar goed, ik ben ook maar één mening.

**Comment by hvdmeer** [comment]
Aangezien er geen reactie verder op gekomen is ga ik er vanuit dat iedereen het zo goed vind.
