### ISSUE TITLE
[Comment] Wordt niet geplaatst bij artikel 

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#299]
Ik heb bij het artikel van Lia over de joomladagen een commentaar ingestuurd maar deze is voor mij niet zichtbaar. 
Kan er gekeken worden wat hier mis gaat?

**Comment by hans2103** [comment]
Hier is zichtbaar wanneer er wat gebeurd is. 
https://github.com/stichtingsympathy/joomlacommunity.nl/commits/develop

**Comment by MartijnMaandag** [comment]
10 maart RSComments 1.13.10?

**Comment by MartijnMaandag** [comment]
Kan iemand RSComments eens opnieuw installeren (eventueel niet via de ontwikkelomgeving)? Misschien helpt dit (het werkt nog steeds niet).

**Comment by sanderpotjer** [comment]
Probleem is verholpen. De override moest bijgewerkt worden met de nieuwste versie zodat RSComments de juiste data meekreeg. Geplaatste comments waarbij het mis ging gecorrigeerd.
