### ISSUE TITLE
Template jc-mixins.less Compile fout

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#30]
Template.less is niet opnieuw te compilen.
-------------------------
Als je de fout regel uit jc-mixins.less haalt, komt een nieuwe regel met een fout.

**parse error: failed at** `#gradient > .horizontal(@color-transp; darken(@color,@dark); 0; 10%;); ` */home/users/jooomftp/nieuw.joomlacommunity.eu/templates/jc//less/joomlacommunity/jc-mixins.less* **on line 81**

Er is een fout opgetreden. Compileren mislukt.

**Comment by sanderpotjer** [comment]
@conconnl je compileert dan vanuit Joomla backend gok ik?

**Comment by conconnl** [comment]
Helemaal correct

**Comment by sanderpotjer** [comment]
Ok, tot nu toe is dat via de lokale tools gedaan en wordt omgezet naar `grunt` commando's. Uitleg volgt, maar via de backend is dus sowieso niet de bedoeling :)

**Comment by AnneKlapwijk** [comment]
@conconnl @sanderpotjer , Ik heb een pull request gedaan voor het compilen van less via `gulp` commando's. Hopelijk kan je daar wat mee :)

**Comment by conconnl** [comment]
Is dit al gelukt?
Ik zie nog niet dat de CSS in subsite_gebruikersgroepen.less meegenomen word.

**Comment by AnneKlapwijk** [comment]
@conconnl De CSS van subsite_gebruikersgroepen.less wordt meegenomen (zie screenshot). Kan het zijn dat je naar een oudere versie of browsercache kijkt en daardoor de wijzigingen nog niet ziet?

![image](https://cloud.githubusercontent.com/assets/3767167/12867850/2780e65a-ccf9-11e5-92bc-715775334290.png)

**Comment by conconnl** [comment]
Ik zal morgen eens kijken. 
Heb standaard mijn cache uit staan, maar wellicht gaat er iets fout. 
Als het werkt zal ik gelijk de melding sluiten. 

Groeten
Wilco

**Comment by AnneKlapwijk** [comment]
Kijk je naar een lokale installatie of naar http://nieuw.joomlacommunity.eu/gebruikersgroepen?
Want zo te zien staan de recente wijzigingen nog niet op nieuw.joomlacommunity.eu.

Als je naar een lokale installatie kijkt, dan kan je proberen om die te updaten:
`git fetch upstream`
`git checkout develop`
`git merge upstream/develop`

> https://help.github.com/articles/syncing-a-fork/

**Comment by conconnl** [comment]
Ik kijk inderdaad altijd online. 
Dat vind ik het makkelijkste zeker omdat we zaken met meerdere mensen tegelijkertijd doen en je dan dingen makkelijk kunt laten zien. 

Verstuurd vanaf mijn iPhone

**Comment by sanderpotjer** [comment]
@conconnl @AnneKlapwijk ik heb de laatste code uitgerold op http://nieuw.joomlacommunity.eu/

**Comment by n9iels** [comment]
Als ik gulp gebruik gaat het compilen van de less goed. Deze issue kan dus gesloten worden :)
Mochten er toch nog problemen zijn, voel je vrij een nieuwe te maken
