### ISSUE TITLE
[EasyDiscuss] Gebruikersrechten forum

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#302]
Er was vandaag een topic die ineens verdwenen is. Ik heb die niet verwijderd en volgens mij is normaal Martijn alleen ook aan het modereren dus ik snap het even niet.

Bij de gebruikersinstellingen staat nergens dat geregistreerden de rechten hebben om een eigen bericht of topic te kunnen verwijderen. Kan iemand dit gedrag controleren? En is er iemand die inzichtelijk heeft of deze gebruiker vandaag zich zelf als gebruiker heeft verwijderd? Info over wie dit is kan via Glip.

In dit geval zijn zover ik kan zien al zijn berichten ook verwijderd, dit heeft als gevolg dat er vreemde discussies op het forum overblijven waarin hij gereageerd heeft.

**Comment by hvdmeer** [comment]
Mag ik dan opmerken dat het anonimiseren handiger is om zo discussies logisch te houden? Een zover ik weet is dat AVG technisch toegestaan.

**Comment by hvdmeer** [comment]
Ik open deze even in verband met het instellen van het verwijderen van gebruikers binnen Easydicuss.

Kan iemand controleren of deze plugin ingesteld staat? Een is het mogelijk om dit te testen?

https://stackideas.com/docs/easydiscuss/administrators/how-tos/how-to-delete-an-user-from-easydiscuss

**Comment by MartijnMaandag** [comment]
De plugin is al geactiveerd. Ik bekijk (en test) het even.

**Comment by MartijnMaandag** [comment]
Heb alles nu zo staan dat berichten van verwijderde users worden gekoppeld aan de user "Gast".
