### ISSUE TITLE
Consent error

### ISSUE THREAD

**Issue by Joomill** [stichtingsympathy/joomlacommunity.nl#303]
Op de joomlacommunity site krijg ik deze melding wanneer ik me wil aanmelden voor de JUG
![image](https://user-images.githubusercontent.com/1471185/41661316-b606d002-749e-11e8-9986-0090f17d4293.png)

Dit komt door een update van RS-Events. Bij opties onderaan kun je dit uitzetten.
![image 1](https://user-images.githubusercontent.com/1471185/41661356-d9f3c024-749e-11e8-9115-d7400e35f1c7.png)

**Comment by sanderpotjer** [comment]
@Joomill top, dank je! Aangepast nu.
