### ISSUE TITLE
[Bug] Comments plaatsen lukt niet - consent nodig

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#305]
Een gebruiker op het forum berichtte dat het reageren op een artikel op de website niet lukt vanwege een benodigde consent. Ik heb dit zelf getest en het lukt mij ook (natuurlijk) niet. Vast een vinkje bij de betreffende comment extensie plaatsen.
![consent-comment-article](https://user-images.githubusercontent.com/7062995/41978423-22503004-7a22-11e8-82e3-2c79b92aade3.png)

**Comment by sanderpotjer** [comment]
@hvdmeer het is handiger als iemand pas issue toewijst als iemand er daadwerkelijk mee aan de gang gaat. Wellicht is er wel iemand die er eerder aan toe komt :)

**Comment by sanderpotjer** [comment]
In ieder geval aangepast ook.

**Comment by hvdmeer** [comment]
Okay!
