### ISSUE TITLE
Twee mails na bericht op Easydiscuss

### ISSUE THREAD

**Issue by MartijnMaandag** [stichtingsympathy/joomlacommunity.nl#306]
Sinds vandaag (?) krijg je in Easydiscuss twee berichten als je reageert,
Vroeger kreeg je geen bericht als je reageerde op een topic (lijkt me ook logisch je hebt gereageerd en weet dat). Momenteel krijg je dat wel. Nog vervelender: Vanaf dit moment krijg je er twee als iemand anders reageert.
Zie https://www.joomlacommunity.nl/forum/over-joomlacommunity-nl/mail-notificatie-bij-eigen-reactie 
Ik heb even gezocht en vond o.a dit: https://stackideas.com/forums/posting-with-email-parser-getting-double-notification
Ik weet niet of er afgelopen dagen veranderingen aangebracht zijn in de instellingen van Easydiscuss, die dit kunnen verklaren.
Ik weet wel dat we recentelijk van hoster zijn veranderd. Kan het misschien ook mee te maken hebben?

**Comment by hvdmeer** [comment]
Ik zag het topic, heb even bij de instellingen gekeken maar zag niks vreemds.

**Comment by MartijnMaandag** [comment]
Hier wordt een oplossing geboden (aanpassing): https://stackideas.com/forums/duplicate-e-mail-notifications-and-unable-to-remove-site-subscription 
Kan dat uitgeprobeerd worden?

**Comment by MartijnMaandag** [comment]
Er is een nieuwe versie van EasyDiscuss die dit schijnt op te lossen: https://stackideas.com/changelog/easydiscuss
Kan iemand dat installeren?

**Comment by sanderpotjer** [comment]
@MartijnMaandag update gedaan, hopelijk is probleem daarbij verholpen

**Comment by MartijnMaandag** [comment]
Dank, het werkt.
