### ISSUE TITLE
Plaatsen verslagen op frontend

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#308]
Dit is alvast de vraag voor wanneer het op joomlacommunity.nl het mogelijk is om de JUG verslagen op de frontend te kunnen plaatsen. 

Er is consensus om in de Aanmaakdatum de datum van de JUG bijeenkomst te plaatsen. Dit zodat er een chronologisch overzicht komt van JUG verslagen. Het komt namelijk voor dat een verslag van een JUG (door omstandigheden) soms een paar weken later op de website geplaatst wordt.

Indien het via de frontend toevoegen van JUG verslagen mogelijk wordt, kan dan via een override de Aanmaakdatum als "Datum bijeenkomst" getoond worden?

**Comment by hans2103** [comment]
my two cents: liever niet... Ik heb liever dat we beheer van content via de backend blijven doen. Die is er immers voor ingericht. De frontend is ingericht voor de weergave van de content.

**Comment by sanderpotjer** [comment]
Zie #40
