### ISSUE TITLE
Website stuk!

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#317]
Wanneer je vanuit Facebook doorklikt naar een content item krijg je een foutmelding te zien.

Zit op mobiel dus geen afbeelding maar het is een template override melding.
https://www.joomlacommunity.nl/nieuws/gebruikersgroepen/arnhem-nijmegen/1432-verslag-arnhem-page-builders

Kreeg er een melding van toegestuurd.
@hans2103 @sanderpotjer

**Comment by hans2103** [comment]
@hvdmeer  ik heb getest en kan het reproduceren. 

Facebook link:
https://l.facebook.com/l.php?u=https%3A%2F%2Fwww.joomlacommunity.nl%2Fnieuws%2Fgebruikersgroepen%2Farnhem-nijmegen%2F1432-verslag-arnhem-page-builders%3Ffbclid%3DIwAR2HNNn7_B8QX2rTAhPeQ4OFjqlF9_5in_EI68RhCAct0bd4fTkNg3tFQZg&h=AT2BhHG95yWMAZwVdM_6KKKmnYnpjDIgNDspoT-Gej_uzSwwLyFeNOxmRTNGLhnfWR5FdNRwvnuKCkQF2sNPXtqexm4C1osJXGdfHPCucIXWXHxD7Uhong_6hil9Mo0Xot3WYogge4tn7hU3XiSv270E2dJYnU6nlmpbpLqLcwzLL9QJgDpAtF8r7FWmXc_QAt_3j51dBSqMGgRBAO6LqlO7XjiVcGRewUvUtU4_OQQJHrwMH-sjq4zcPvdAndOFiE0PXguXGTCjtR25pYzgG7ZhNA4kHvGL2zoJrKkwj2pxEhj20pa4_ov7mM83HuvDdPs_5BhNfD7wfXu2fJCt8CnunL6ObgxoFY4QfxostVgb0JIdgECP3G_5oZMSf7MDEMX91dsUsvfBGCd_AqsANA2mJu23zhSvPTr7qDoAOQbCtVG1M3Huin4TGfALUAgDxMyU8uE_onxc2MVeN3hs-_p4pdJVhCP22jQY3aYbABDWRxPJDUNAouXc594mvX4h4MhHoEfnGBx92jAh4uN-OGBWfsVsuJWUlHyG2zFYwWFhCAsbKgTbBDHcBIyhbuDk9XtrNUuF6GuN5uS2bIUFo5zmrI8_PEwOpTJoNyt99J_ijSE7jfDRI6rgi2k

De link zodra hij op de site is:
https://www.joomlacommunity.nl/nieuws/gebruikersgroepen/arnhem-nijmegen/1432-verslag-arnhem-page-builders?fbclid=IwAR2HNNn7_B8QX2rTAhPeQ4OFjqlF9_5in_EI68RhCAct0bd4fTkNg3tFQZg

De link zonder parameters:
https://www.joomlacommunity.nl/nieuws/gebruikersgroepen/arnhem-nijmegen/1432-verslag-arnhem-page-builders

De melding op scherm:
This function is not used anymore. If you have a template override, please update your files.

Deze melding op scherm verschijnt en verdwijnt ook zodra je een nieuws item opent vanuit de category blog. Mogelijk gerelateerd aan de recent doorgevoerde updates.

**Comment by hans2103** [comment]
Issue heeft te maken met verouderde overrides in com_rscomments

**Comment by sanderpotjer** [comment]
Heb template overrides bijgewerkt waardoor melding weg is.
