### ISSUE TITLE
ACL voor site en Form

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#39]
Er moeten naast de standaard rechten ACL instellingen komen voor:
- Het Forum (moderators & beheerders)
- Gebruikersgroepen
- Nieuws artikelen plaatsen
- Downloads beheren

**Comment by hvdmeer** [comment]
Voor alle andere rollen die op het forum zichtbaar mogen zijn moet een gebruikersgroep aangemaakt worden, zoals bv. Documentatieteam, Taalteam, Gebruikersgroep. Deze worden in het huidige forum nog wel gebruikt.

**Comment by n9iels** [comment]
Ik heb de volgende gebruiksgroepen aangemaakt:
Public
- Algemeen auteur: Kan alle artikelen/items op de website bewerken
- Geregistreerd: Standaard gebruiker zonder extra rechten
- Super User
- Teams: Bovenliggende groep met rechten die elk team heeft
 - Documentaties: Kan enkel artikelen bewerken in de categorie documentaties
 - Downloads: Kan enkel download items bewerken
 - Gebruikersgroepen: Kan enkel artikelen bewerken in de categorie gebruikergroepen
 - Moderator: Forum beheer
 - Nieuws: Kan enkel categorieën bewerken in de categorie nieuws

**Comment by n9iels** [comment]
Ik heb ook nieuwe toegangsniveau's aangemaakt:
- Public
- Gast
- Teams **Items van deze groep zijn zichtbaar voor alle gebruikers die in een team zitten**
- Geregistreerd
- Speciaal **Item van deze groep zijn enkel zichtbaar voor Super user en algemeen auteur**

**Comment by conconnl** [comment]
**Teams -> Gebruikersgroepen**
We hebben dit niveau uitgebreid met groepen per JUG.

- Amsterdam / Bussum
- Arnhem / Nijmegen
- Breda
- Den Bosch
- Eindhoven
- Enschede
- Groningen
- Heerenveen
- Leiden
- Rotterdam
- Utrecht / De Meern
- Weert
- Zwolle

**Comment by hans2103** [comment]
@n9iels wat is de status van deze issue?

**Comment by n9iels** [comment]
Volgens mij is deze afgehandeld en hebben we nu alle gewenste ACL rechten. Kan gesloten worden dus :)
