### ISSUE TITLE
Joomla Gids

### ISSUE THREAD

**Issue by sanderpotjer** [stichtingsympathy/joomlacommunity.nl#4]
Overzicht van bedrijven en personen die met Joomla werken

**Comment by pjasmits** [comment]
Sander had je een module in gedachte op dit te gaan opzetten? Ik wil mij hier wel mee bezig gaan houden. Misschien is het een idee om een emailadres: aanmelden@joomlacommunity.nl te maken waar men zich kan aanmelden. Maak ik wel een lijst. Hoor het wel, groet, Patrick.

**Comment by hvdmeer** [comment]
Zoals resources op joomla.org? Persoonlijk zou ik dat wel een aanvulling vinden, de koppeling tussen de vele zakelijke know-how en de info/forum komt nu niet echt tot uiting.

Wellicht dat het ook in de gebruikersprofiel aangevuld kan worden. Endorsements of iets dergelijks.
