### ISSUE TITLE
SocialMedia Share buttons do not work

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#42]
Op de enkele artikel pagina's zie je aan de linkerkant SocialMedia knoppen. (Twitter, Facebook, Google+)
Deze knoppen werken niet, als ik in de template overrides kijk zie je alleen het stuk HTML staan, maar niets om de knoppen daadwerkelijk een actie uit te laten voeren.
Bij de Facebook knop staat er een hardcoded link, waardoor bij elke pagina dezelfde link zichtbaar is om te delen.

Voorbeeld pagina
http://nieuw.joomlacommunity.eu/nieuws/gebruikersgroepen/994-jug-zuidoost-nederland-8-januari-2015-j2store#

**Comment by hans2103** [comment]
ik kan het reproduceren... 
zie regels 98 t/m 111 van het onderstaande bestand. 
https://github.com/stichtingsympathy/joomlacommunity.nl/blob/develop/templates/jc/html/com_content/article/default.php

zo te zien is de functionaliteit er nog niet ingebouwd.
Implementatie van de module DB8_SocialMediaShare van Peter Martin zou je verder kunnen helpen:
https://github.com/pe7er/db8socialmediashare

**Comment by sanderpotjer** [comment]
Bedoeling is dat dit gewoon in override komt, geen extensie voor nodig. Komt eraan!

**Comment by hans2103** [comment]
@sanderpotjer al klaar of zal ik de code vanuit DBSocialMediaShare overnemen?
zie: https://github.com/pe7er/db8socialmediashare/blob/master/mod_db8socialmediashare.php

**Comment by sanderpotjer** [comment]
@hans2103 mag ook. Module is ook prima, zo te zien clean zonder inladen van allerlei Facebook/Twitter scripts, dat is het belangrijkste :)

Dank Hans!
