### ISSUE TITLE
RSEvents!Pro Avatar plugin

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#43]
Kan iemand (@n9iels) een plugin bouwen om de avatars in EasyDiscuss te gebruiken in RSEvents!Pro?
Afbeeldingen toegevoegd van waar wij de Avatar extensie selecteren en waar het zichtbaar wordt.
<img width="470" alt="avatar plugin" src="https://cloud.githubusercontent.com/assets/11913918/14405150/641ba300-fe88-11e5-85f3-9eb3def73777.png">
<img width="477" alt="avatar visibility" src="https://cloud.githubusercontent.com/assets/11913918/14405156/938a173e-fe88-11e5-9f2d-4feb5fc50db2.png">

**Comment by conconnl** [comment]
Dit zijn de bestaande JomSocial en CommunityBuilder Plugins
[plg_rseventspro.zip](https://github.com/stichtingsympathy/joomlacommunity.nl/files/211385/plg_rseventspro.zip)
[plug_rseventspro.zip](https://github.com/stichtingsympathy/joomlacommunity.nl/files/211386/plug_rseventspro.zip)

**Comment by n9iels** [comment]
@conconnl ik kan niet helemaal vinden waar die opties staan. Is dat in het component? zo ja waar?
Denk wel dat het mogelijk is om iets te bouwen :)

**Comment by n9iels** [comment]
hmm het lijkt erop dat er geen plugin event is waarop an worden ingehaakt. De avatars worden opgehaald met behulp van de helper `rseventsproHelper::getAvatar()`. Zal dus een manier moeten vinden om deze helper te overschrijven bij het inladen.

**Comment by conconnl** [comment]
Is het misschien een idee om de extensie zelf aan te passen.
De aanpassingen goed te documenteren en deze op te sturen naar Octavian (Een van de bazen) van RSJoomla!, dan laat ik ze gewoon zorgen dat ze het toevoegen aan de extensie.
Dus dat de dropdown een extra keuze krijgt, als ik jou goed begrijp de rseventsproHelper::getAvatar() uitbreiden.

Hiermee zorgen we dat wij hebben wat we nog hebben.
Zij een extra Feature in de extensie hebben en verantwoordelijk zijn voor de toekomstige updates.

**Comment by conconnl** [comment]
@n9iels zoals vandaag besproken:

- Aanpassingen uitvoeren op de rseventsproHelper::getAvatar()
- Deze in een aparte commit verwerken, zodat we exact weten wat er aangepast is.
- Deze aanpassingen ga ik dan communiceren met RSJoomla!, zodat het in de hoofdextensie komt en er update support is.

**Comment by n9iels** [comment]
Zucht.... Blijkbaar is er iets vaags gebeurd met de line-endings van mijn bestanden :-(

**Comment by n9iels** [comment]
Oke voor de duidelijkheid, de volgende regelnummers in de volgende bestanden:
- settings.xml L185
- settings.php L98, L124 t/m 127
- default.php L27, L33 t/m 34
- en-GB.com_rseventspro.ini L173

**Comment by conconnl** [comment]
Goed gedaan.
Het werkt perfect, ik ga zorgen dat RSJoomla dit gaat integreren, zodat het bij een update niet verdwijnt.

**Comment by conconnl** [comment]
RSEvents!Pro 1.10.0 is vandaag uit gekomen.
De EasyDiscuss optie is nu geïntegreerd.
