### ISSUE TITLE
J! 3.48 -> 3.5.1

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#44]
Created Backup and upgraded site to J! 3.5.1

**Comment by sanderpotjer** [comment]
@conconnl thnx! Maar ik zie geen commit/pull request?

**Comment by conconnl** [comment]
Hoe bedoel je dat?
Update gebeurt toch binnen de site.

**Comment by sanderpotjer** [comment]
Ja, maar de code moet dan wel in de repository terecht komen https://github.com/stichtingsympathy/joomlacommunity.nl (zie bijv recente aanpassingen van Niels) https://github.com/stichtingsympathy/joomlacommunity.nl/commits/develop

Waarschijnlijk heb je nu aanpassingen gedaan op de http://nieuw.joomlacommunity.eu omgeving, dat kan betekenen dat dit niet in de repository terecht komt en aanpassingen verloren gaan. 

De code wordt namelijk vanuit de repository op http://nieuw.joomlacommunity.eu uitgerold, en niet andersom (in principe). 

Kan het komend weekend wel even verder toelichten :)

**Comment by conconnl** [comment]
Oke, is wel handig als het voor iedereen duidelijk is.

Dus je bedoelt dat wij alles eigenlijk op een eigen tak moeten bouwen en de wijzigingen daarin via een pull request naar de Master van de site, zodat het op de site komt.

Hoe wil je dat dan doen met database aanpassingen?
Gisteren hebben Edith en Nico heel veel werk verzet, qua inrichtingen binnen de extensies, nieuwe extensie geinstalleerd en geconfigureerd.

**Comment by n9iels** [comment]
@conconnl geen zorgen, de database wijzigingen komen allemaal helemaal goed door. Die is gewoon hetzelfde voor de live en de development omgeving.

En ja idd, als je echt wijzingen wil maken aan bestanden moet je even een PR aanmaken. Dan kan iemand die daarvoor de rechten heeft op merge drukken.

Al met al zeer goed bezig allen!!

**Comment by conconnl** [comment]
Ik heb de meeste zaken kunnen herleiden en via een Fork tak commits aangemaakt om ze op GIT te laten verwerken.
Als deze allemaal verwerkt zijn kan ik opzoeken wat alle aanpassingen zijn van 3.4.8 naar 3.5.1

**Comment by hvdmeer** [comment]
Ha! Dan maar goed dat ik van die update-knopjes afblijf. ;)

**Comment by hans2103** [comment]
wijzigingen van server teruggebracht naar deze repository.
