### ISSUE TITLE
Fatal errors; veroorzaakt door EasyDiscuss?

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#50]
Ik krijg op dit moment op twee plekken fatal errors. 

Wanneer er geklikt wordt op het menu item Gebruikersgroepen wordt er een Fatal error veroorzaakt:

`
Fatal error: require_once(): Failed opening required '/home/users/xxxx/xxxx/components/com_easydiscuss/helpers/helper.php' (include_path='.:/usr/share/php') in /home/users/xxxx/xxxx/templates/jc/html/com_content/article/gebruikersgroepen.php on line 35`

Wanneer in de backend een menu item wordt aangepast, ik had een styling verwijderd, wordt daar bij opslaan ook een Fatal error veroorzaakt
`
Fatal error: Call to undefined method EasyDiscussPost::load() in /home/users/jooomftp/nieuw.joomlacommunity.eu/plugins/content/easydiscuss/easydiscuss.php on line 552
`

Is dit iets wat bij StackIdeas aangekaart moet worden?

**Comment by conconnl** [comment]
Ik kan bevestigen dat dit is sinds de nieuwe easydiscuss versie erop staat.
Het helper bestand bestaat niet meer.
Voor de gebruikersgroepen heb ik tijdelijk in de override het volgende uitgeschakeld, tot dat het probleem opgelost is.
require_once JPATH_ROOT . '/components/com_easydiscuss/helpers/helper.php';

**Comment by n9iels** [comment]
@conconnl @hans2103 het lijkt erop dat de regel gewoon weggehaald kan worden, en dat dan nog steeds de helper wordt ingeladen. Deze helper is bedoeld om profielgegevens (avatar ed.) op te halen voor het nieuwsoverzicht. Na het verwijderen van deze regel is de avatar nog steeds zichtbaar. Dus lijkt me geen probleem

**Comment by conconnl** [comment]
Issue is niet meer voorgekomen.
