### ISSUE TITLE
[Development] - RSEvents!Pro Category level selectie

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#55]
@n9iels 
In de RSEvents!Pro Categories module vindt je de optie om het niveau te selecteren vanaf waar de categorieën getoond dienen te worden. "Bovenliggende categorie"
<img width="422" alt="bovenliggende categorie" src="https://cloud.githubusercontent.com/assets/11913918/14583395/f2b1929e-0420-11e6-8d3c-5a4fb15702aa.png">

Deze optie missen wij in het menu RSEvents!pro menu welk dezelfde categorieen toont.
<img width="588" alt="rsevents menu item" src="https://cloud.githubusercontent.com/assets/11913918/14583489/5fe1b414-0423-11e6-91bb-351e3979320e.png">

Ook bij deze graag in een aparte commit de aanpassingen documenteren.
Dan kunnen wij deze weer via RSJoomla! laten integreren

**Comment by n9iels** [comment]
Ik heb atm niet de mogelijkheid om het menu item op te slaan, krijg de volgende errors:
```
Notice: Undefined property: MenusTableMenu::$state in /home/niels/lamp/public_html/joomlacommunity/plugins/content/easydiscuss/easydiscuss.php on line 505

Fatal error: Call to undefined method EasyDiscussPost::load() in /home/niels/lamp/public_html/joomlacommunity/plugins/content/easydiscuss/easydiscuss.php on line 552
```
Voor het bouwen van deze feature moet dat eerst opgelost zijn

**Comment by conconnl** [comment]
@n9iels EasyDiscuss forum is bijgewerkt.
De foutmelding op de RSEvents!Pro menu **Joomla! Gebruikersgroepen (JUG) ** komt niet meer voor.
Dus je kunt nu zonder problemen de functionaliteit bouwen.

**Comment by n9iels** [comment]
@conconnl ik heb ernaar gekeken, maar ik vrees dat ik hier niks mee kan. De structuur is zo dusdanig ingewikkeld dat het mij niet lukt om de SQL query aan te passen

**Comment by conconnl** [comment]
@n9iels heb je Glip, dan kunnen we makkelijker discussiëren?
De optie zit al in de module, dus ik verwacht dat we het makkelijk over kunnen nemen als we weten waar we moeten kijken en met SQL Query kan ik wellicht wel helpen.

**Comment by conconnl** [comment]
@n9iels je hoeft hier niets meer aan te doen.
Ik ben dit nu aan het afronden.

**Comment by conconnl** [comment]
Code change created Commit Number: 231d9d3ba2f03a30699bd753b9b3c36d50ca4ae
Zal deze ook doorzetten naar RSJoomla! om te laten integreren in de originele versie

**Comment by conconnl** [comment]
Deze aanpassing zit ook vanaf vandaag in de nieuwe versie van RSEvents!Pro
