### ISSUE TITLE
[Informatie] - Projectgroep structuur & werkwijzen.

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#56]
In dit issue staat beschreven welke projectgroep structuur en werkwijzen er gehanteerd worden voor het afronden en online zetten van de website in fase 1. (Gepland moment half Juni 2016)

> Dit is een levend document, zodat we voor de huidige fase en toekomstige fases aanpassingen kunnen doen.

`Er kan gewoon zoals gewent gereageerd worden op dit issue en als dit invloed heeft op de inhoud van deze beschrijving zullen wij het aanpassen.`

# Projectgroep Structuur

> De hoofdcoördinatie gebeurt vanuit Stichting Sympathy (@sanderpotjer), de Stichting is ten alle tijde de beslissende partij t.b.v. alle zaken die doorgevoerd dienen te worden.
Elke team heeft zijn eigen teamcoördinator, die als hoofdaanspreekpunt fungeert richting de Stichting en het team wat de betreffende onderdeel oppakt.
- Dit betekend niet dat er onderling niet gecommuniceerd kan en mag worden, er is alleen een duidelijke structuur nodig om zo min mogelijk vertraging op te lopen.
- Er zijn ook mensen die helpen die niet bij een specifieke team horen, deze kunnen helpen met specifieke zaken, zoals bijvoorbeeld het ontwikkelen van een plugin.
Denk hierbij aan @n9iels, @hans2103, Jisse Reitsma, Roland Dalmulder, Peter Martin & Rene Kreijeveld.

## Teams
-  [Voorpagina](http://nieuw.joomlacommunity.eu/)
  - Coördinator: ??
  - Teamleden: @crommie 
  - Afspraken / Besluiten & To-Do document
  - [Fase 1 Issues](https://github.com/stichtingsympathy/joomlacommunity.nl/issues?utf8=%E2%9C%93&q=is%3Aopen+milestone%3A1.0+label%3AHomepage)
- [Nieuws ](http://nieuw.joomlacommunity.eu/nieuws)
  - Coördinator: ??
  - Teamleden: ??
  - Afspraken / Besluiten & To-Do document
  - [Fase 1 Issues](https://github.com/stichtingsympathy/joomlacommunity.nl/issues?utf8=%E2%9C%93&q=is%3Aopen+milestone%3A1.0+label%3ANieuws)
- [Taalpakketten  ](http://nieuw.joomlacommunity.eu/downloads)
  - Coördinator: @conconnl / Marijke Stuivenberg
  - Teamleden: ??
  - Afspraken / Besluiten & To-Do document
  - [Fase 1 Issues](https://github.com/stichtingsympathy/joomlacommunity.nl/issues?utf8=%E2%9C%93&q=is%3Aopen+milestone%3A1.0+label%3ADowload)
- [Documentatie ](http://nieuw.joomlacommunity.eu/documentatie)
  - Coördinator: @martijnmaandag
  - Teamleden: ??
  - Afspraken / Besluiten & To-Do document
  - [Fase 1 Issues](https://github.com/stichtingsympathy/joomlacommunity.nl/issues?utf8=%E2%9C%93&q=is%3Aopen+milestone%3A1.0+label%3ADocumentatie)
- [Forum ](http://nieuw.joomlacommunity.eu/forum/recent)
  - Coördinator: @hvdmeer 
  - Teamleden: ??
  - [Afspraken / Besluiten & To-Do document](https://github.com/stichtingsympathy/joomlacommunity.nl/issues/23)
  - [Fase 1 Issues](https://github.com/stichtingsympathy/joomlacommunity.nl/issues?utf8=%E2%9C%93&q=is%3Aopen+milestone%3A1.0+label%3AForum)
- [Gebruikersgroepen ](http://nieuw.joomlacommunity.eu/gebruikersgroepen)
  - Coördinator: @Stitch123
  - Teamleden: @superknutsel
  - Afspraken / Besluiten & To-Do document
  - [Fase 1 Issues](https://github.com/stichtingsympathy/joomlacommunity.nl/issues?utf8=%E2%9C%93&q=is%3Aopen+milestone%3A1.0+label%3AGebruikersgroepen)
- Template
  - Coördinator: ??
  - Teamleden: ??
  - Afspraken / Besluiten & To-Do document
  - [Fase 1 Issues]()
- Backend
  - Coördinator: ??
  - Teamleden: ??
  - Afspraken / Besluiten & To-Do document
  - [Fase 1 Issues]()

# Werkwijzen

> Hier zullen wij bepaalde werkwijzen beschrijven.
Denk hierbij aan zaken zoals het lokaal ontwikkelen, toevoegen aan GIT, maken van issues en dergelijke zaken. Dit zal op korte termijn snel uitgebreid worden.

**Comment by sanderpotjer** [comment]
@conconnl thanks! Ik heb dit even verplaatst naar een wiki pagina: https://github.com/stichtingsympathy/joomlacommunity.nl/wiki/Projectgroep-structuur-&-werkwijzen
