### ISSUE TITLE
[Development] Installeren taalpakket Dutch in EasyDiscuss

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#57]
Er mist nog een taalpakket Dutch in EasyDiscuss die geïnstalleerd kan worden. Kan iemand een Pull Request doen om dit taalpakket te installeren?

Dat kan op de volgende manier:
* Ga naar *Componenten* *-* *EasyDiscuss*
* Klik in het menu aan de linkerzijde op "Instellingen" en daarna in het submenu op "Advanced"
* Kopieer hier de "API Key" vandaan zodat je deze lokaal kan instellen
* Klik nu in het menu aan de linkerzijde op *Languages*
* Selecteer *Dutch* *(Netherlands)*
* Klik links bovenin op de knop *Install* */* *Update*

Redelijk normaal, verder dan dit kan ik niet omschrijven want dan moet ik het ook gaan uitvoeren. Ik heb deze nieuwe site namelijk niet lokaal staan, zover ben ik nog niet met Git. :)

**Comment by conconnl** [comment]
Actie uitgevoerd.
Deze zal alleen nog gemigreerd moeten worden naar de server.
