### ISSUE TITLE
[Development] Gebruikers synchroniseren met huidige website

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#58]
Ik ben bezig met het toewijzen van gebruikers aan de verschillende gebruikersgroepen die hiervoor zijn aangemaakt. Dit zodat ze in EasyDiscuss ook gekoppeld kunnen worden aan een rol. Nu kom ik bij Leiden aan en ik zie dat Wouter niet in de nieuwe website als gebruikers is aangemaakt.

Is het mogelijk om de (missende) gebruikers uit de huidige website in de nieuwe website geplaatst kunnen worden zonder dat de huidige instellingen op gebruikersniveau kap0t gaan?

**Comment by sanderpotjer** [comment]
@hvdmeer het beste kan je er denk ik vanuit gaan dat we voor de livegang ALLE gebruikers en gegevens (zoals wachtwoorden) opnieuw overzetten naar de nieuwe site. Wat er nu staat moet je zien als demo-data. We kunnen de boel testen met inrichting/instellingen dan alles al compleet instellen. Wel is het praktisch om een stappenplan te maken voor wat er aangepast/ingesteld moet worden tijdens de livegang van de nieuwe site.

**Comment by sanderpotjer** [comment]
Note; we gaan alleen de gebruikers die afgelopen half jaar zijn ingelogd synchroniseren.

**Comment by hvdmeer** [comment]
Strak plan, na mijn actie bij het invoeren van een artikel op de front-end en dat daarna mijn mail inbox volliep omdat er zoveel niet-bestaande adressen van gebruikers bestonden van oud-gebruikers is wat opschonen niet verkeerd. 

Maar is het opschonen van niet gebruikte accounts niet te veel op te schonen te voorkomen het misschien handig om het op een jaar te zetten? (que? taaltechnisch)

**Comment by hvdmeer** [comment]
Zeg @sanderpotjer , zijn dit gebruikers van de Joomla! website en ook die van het forum? Want ik heb nu een paar accounts aangemaakt voor testers van het nieuwe forum die geen account in de huidige Joomla website hebben maar wel in VBulletin.

**Comment by sanderpotjer** [comment]
Op de huidige site zijn forum users leading, dus die zullen gemigreerd worden.

**Comment by hvdmeer** [comment]
Top, dat verwachte ik eigenlijk ook.

**Comment by sanderpotjer** [comment]
Het was een werkje, maar de gebruikers zijn allemaal overgezet. De foutmeldingen bij artikelen zijn daarmee ook verdwenen.
