### ISSUE TITLE
Zoeken dynamisch maken (smart search/finder)

### ISSUE THREAD

**Issue by sanderpotjer** [stichtingsympathy/joomlacommunity.nl#6]
- [x] Zoekvenster in top toolbar vervangen met zoekmodule
- [x] Zoekresultaten pagina met finder/smart search op joomlacommunity.nl/zoeken
- [x] Opmaken zoekpagina

**Comment by conconnl** [comment]
@hans2103 
Zoiets als in de screenshot.
Alleen dan de titel balk wat hoger tegen de border line aan?
<img width="1251" alt="screen shot 2016-05-22 at 14 08 02" src="https://cloud.githubusercontent.com/assets/11913918/15453889/c73b95a2-2026-11e6-9792-e8badfcb87db.png">

**Comment by jissereitsma** [comment]
Rechtsbovenin is een template positie voor `search` en als ik de Smart Search module aanzet op mijn eigen lokale omgeving, dan ziet dit er al prima uit.

Kan dezelfde module op de nieuw.joomlacommunity.eu site aangezet worden, ter aller vermaeck?

Wat zijn hier verder nog de issues mee? Ik zou zeggen dat het al goed is als non-designer.

**Comment by conconnl** [comment]
Module is aangezet.
Het is niet echt super leesbaar, vandaar ook mijn voorstel aan Hans.

**Comment by conconnl** [comment]
Kan iemand het onderstaande in de goeie less bestanden verwerken?
Dan krijg je het volgende:

<img width="1159" alt="screen shot 2016-09-12 at 23 00 47" src="https://cloud.githubusercontent.com/assets/11913918/18452826/ced4f992-793c-11e6-8660-3a2811cd3771.png">



```
div.finder div#search-results ul.search-results.list-striped li {
	border: 1px solid;
}

div.finder div#search-results ul.search-results.list-striped li h4.result-title {
    background-color: #95a5a6;
    margin: 0;
    padding: 5px;
    text-align: center;
}

div.finder div#search-results ul.search-results.list-striped li h4.result-title a {
	color: #ffffff;
}

div.finder div#search-results ul.search-results.list-striped li p.result-text {
	margin-left: 5px;
}

div.finder div#search-results ul.search-results.list-striped li div.small.result-url {
	margin-left: 5px;
}

```

**Comment by conconnl** [comment]
@sanderpotjer kun je dit ook meenemen, nu je toch met style zaken bezig bent?

**Comment by sanderpotjer** [comment]
Zoekresultatenpagina is nu opgemaakt.
