### ISSUE TITLE
[Design] Categoriepictogrammen EasyDiscuss

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#61]
Bij de categorie-overzicht van EasyDiscuss worden pictogrammen getoond. Deze kan ik, zover ik kan zien, niet in de instellingen uitschakelen. Wanneer er geen pictogram ingesteld wordt wordt er een placeholder gebruikt. 

Dit staat natuurlijk niet echt geweldig. Ik heb als voorbeeld even een paar pictogrammen gemaakt vanuit Font Awesome, maar hiermee kan ik niet alle categorieën een pictogram geven omdat er niet altijd geschikte mogelijkheden zijn. Zelf heb ik al naar gratis iconsets gekeken maar eigenlijk altijd moet er een minimaal backlink op de pagina gezet worden. Ik weet niet of dit wenselijk is.

Hieronder is een voorbeeld met hoe ik het op dit moment heb ingesteld.

![jc-forum-pictogram](https://cloud.githubusercontent.com/assets/7062995/14769043/07b53094-0a50-11e6-992c-b67a4923814b.png)

Is het mogelijk dat er iemand met verstand van zaken (design) een set van Joomla!Community pictogrammen maakt voor het gebruik op dit forum?

**Comment by sanderpotjer** [comment]
@hvdmeer is het misschien niet makkelijker om zonder pictogrammen te werken?

**Comment by hvdmeer** [comment]
Dan krijg je dus die mappen voor de naam. Ik heb niet kunnen vinden om dit uit te schakelen, dan zou dat wellicht via een code-aanpassing moeten gebeuren. Of gewoon die mappen gebruiken, dat is ook een optie.

**Comment by sanderpotjer** [comment]
Die mappen kunnen we wel verbergen via CSS of template override!
