### ISSUE TITLE
[Development] EasyDiscuss updaten

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#62]
Inmiddels is EasyDiscuss officieel uitgebracht en zit (volgens mij) op versie ~~4.0.2~~ 4.0.4. 
Is het mogelijk dat iemand deze update en naar Github plaatst zodat we weer op de actuele versie zitten?

**Comment by sanderpotjer** [comment]
@hvdmeer extensie is bijgewerkt naar 4.0.5
