### ISSUE TITLE
overrides RSFiles

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomlacommunity.nl#63]
Op de server zie ik twee overrides van RSFiles staan van 24 april staan. 
Omdat ik geen issue kan vinden waarin deze overrides benoemd worden maak ik deze nieuwe issue aan waar ik de overrides aan ga koppelen.

**Comment by conconnl** [comment]
Klopt, want er is geen daadwerkelijk aanpassing gedaan aan het bestand. Als je even iets checkt en op opslaan klinkt verandert de datum wel ook verandert de inhoud niet.

**Comment by hans2103** [comment]
Neem aan dat het een vergissing was om op opslaan te klikken als er geen wijzigingen zijn doorgevoerd. Heb ik ook wel eens.
