### ISSUE TITLE
[Development] PHP7.0 beschikbaar

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomlacommunity.nl#65]
https://www.byte.nl/kennisbank/item/overstappen-naar-een-nieuwere-php-versie

Testen met je eigen ip-adres? Voeg dan het volgende toe aan je .htaccess

```
RewriteEngine on
RewriteCond %{REMOTE_HOST} ^xxx\.xxx\.xxx\.xxx$
RewriteRule ^(.+\.php)$ – [T=application/cgi-php70]
```

Wanneer je alle URL’s wilt testen, ongeacht of deze eindigen op .php of niet, voeg je de volgende code toen aan je .htaccess

```
AddType application/cgi-php70 php
```

Omdat PHP7 veeeeeel sneller is dan PHP3 hihi... maar ook nog sneller dan PHP5.6 stel ik voor om de .htaccess regel aan te passen, zodat de nieuwe JC.nl site op PHP7 gebouwd wordt.

**Comment by hans2103** [comment]
na het doorvoeren van de htaccess wijziging om de site in php7 te testen faalt de gehele site:

```
## Mod_rewrite in use.
RewriteEngine on
#RewriteCond %{REMOTE_HOST} ^62\.81\.164\.219$
RewriteRule ^(.+\.php)$ - [T=application/cgi-php70]
```

daarom wijziging aan htaccess ongedaan gemaakt

**Comment by n9iels** [comment]
Ik draai de website op PHP7 lokaal en ondervind geen problemen. Lijkt me dat deze op de server van byte dus ook prima zal werken?

**Comment by conconnl** [comment]
@hans2103 kun je het nog een keer bekijken / proberen.
Wellicht door het account aan te passen en niet via de htaccess.
Ik draai al mijn sites op PHP7 zonder problemen, ik verwacht dat deze site het ook kan.

**Comment by hans2103** [comment]
@conconnl en @n9iels het omzetten van de PHP versie op de server naar PHP7 zal dus geen gevolgen hebben voor nieuw.joomlacommunity.eu. Maar... nieuw. is een subdomein van de op dezelfde server geplaatste www.joomlacommunity.eu. 
Die zal nog niet kunnen draaien met PHP7.
Daarom dat ik de wijziging niet ga doorvoeren via de server instelling, maar wel via .htaccess

**Comment by hans2103** [comment]
Via .htaccess de PHP versie naar PHP7 gezet. Door de site geklikt en zo te zien werkt het allemaal nog netjes. 

<img width="1096" alt="schermafdruk 2016-08-10 08 40 46" src="https://cloud.githubusercontent.com/assets/639822/17544203/251cfd26-5ed6-11e6-9828-10cb9ac9dc09.png">
