### ISSUE TITLE
Artikeldata meer compact

### ISSUE THREAD

**Issue by superknutsel** [stichtingsympathy/joomlacommunity.nl#7]
De extra gegevens voer o.a. auteur, publicatiedatum en categorie nemen nu vrij veel ruimte in en duwen de content flink naar beneden. Voorbeeld : http://nieuw.joomlacommunity.eu/nieuws/joomlacommunity

**Comment by n9iels** [comment]
Ik heb een nieuwe layout toegepast (deze is nog niet zichtbaar op de live website helaas). Daar is deze weergave mee verbeterd :)

Ik sluit deze nu om op te ruimen. Als de live versie is geüpdate, en je hebt nog puntjes voel je vrij een nieuwe issue aan te maken.
