### ISSUE TITLE
[Development] Opslaan vanaf de frontend werkt niet

### ISSUE THREAD

**Issue by marijkestuivenberg** [stichtingsympathy/joomlacommunity.nl#72]
Nadat een artikel is bewerkt vanaf de frontend en probeert op te slaan gebeurt er niets. (ook geen waarschuwingen of foutmeldingen op de site)

Fouten in de console:
modal.js:7 Uncaught ReferenceError: Hash is not defined
aan-de-slag-met-joomla:47 Uncaught SyntaxError: Unexpected token function
aan-de-slag-met-joomla:232 Uncaught ReferenceError: Joomla is not defined
http://nieuw.joomlacommunity.eu/fonts/joomlacommunity.ttf?rc0sy8 Failed to load resource: the server responded with a status of 404 (Categorie niet gevonden)
http://nieuw.joomlacommunity.eu/fonts/joomlacommunity.woff?rc0sy8 Failed to load resource: the server responded with a status of 404 (Categorie niet gevonden)
6aan-de-slag-met-joomla?view=form&layout=edit&a_id=2177&return=aHR0cDovL25pZXV3Lmpvb21sYWNvbW11bml0e…:359 Uncaught ReferenceError: Joomla is not defined

**Comment by n9iels** [comment]
@marijkestuivenberg Dit komt zeer waarschijnlijk omdat er een conflict is met Bootstrap 2 van Joomla! en Bootstrap 3 van de template. Ik zal eens gaan kijken of ik dit kan repareren, heb toevallig nog wel iets liggen dat hier van pas komt :)

**Comment by n9iels** [comment]
@marijkestuivenberg ik heb de weergave van front-end editing aangepast. Hij is nu volledig werkend inclusief layout :)

**Comment by n9iels** [comment]
Deze feature zit nu in de master versie en staat live, ik sluit dit issue nu dus. Indien er problemen optreden graag even een nieuwe aanmaken
