### ISSUE TITLE
[Vraag] - Is Komento noodzakelijk om te gebruiken

### ISSUE THREAD

**Issue by conconnl** [stichtingsympathy/joomlacommunity.nl#75]
@sanderpotjer wij ( @hans2103 & ik) hebben gisteren uitgebreid gekeken naar Komento.
Deze extentie bevat redelijk wat deprecated joomla en PHP functies, daarnaast kunnen wij niet echt ontdekken, waarom Komento nodig is i.p.v. een andere extensie zoals bijv. RSComments.

Wat wij kunnen ontdekken is dat deze alleen gebruikt wordt voor de artikelen, daarnaast moesten wij een plugin, feature of iets dergelijks ontwikkelen om het te laten werken in RSEvents!Pro.
RSComments kan natuurlijk standaard zelf al samenwerken met de andere RS Extensies en de Joomla! artikelen.

Kun je ons uitleggen waarom Komento nodig is, of kunnen wij overschakelen naar bijv. RSComments! om zo wat ontwikkelingen niet te hoeven doen en toch dezelfde mogelijkheden te bieden?

**Comment by sanderpotjer** [comment]
@conconnl nee hoor, niet noodzakelijk. Destijds gekozen omdat het goed integreert met EasyDiscuss (je ziet in profiel bijv ook reacties van iemand). RSComments vast prima alternatief!

**Comment by conconnl** [comment]
Dankjewel. Ga ik ermee aan de slag.
Wellicht dat we met een override een link naar de aangemaakte comments van een gebruiker kunnen toevoegen in het forum.
