### ISSUE TITLE
[Development] Homepage - Laatste Joomla! versies

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomlacommunity.nl#76]
Op de homepage staat rechtsboven een blok met daarin: "Laatste Joomla! versies"
Op dit moment is het een mod_custom en bevat de tekst "Iets met laatste Joomla versies".

De wens is dat hier dynamisch de meest recente stable versie van Joomla komt te staan.

**Comment by n9iels** [comment]
Ha Hans,

Ik zag deze voorbij komen en ik vond het wel een mooie om op te pakken!
Ik heb een module ontwikkeld die aan de hand van het update xml bestand van Joomla! en opgegeven prefixes de laatste versies weergeeft.

Geef bijvoorbeeld de volgende prefixes mee `2,3

[mod_joomlaversions.zip](https://github.com/stichtingsympathy/joomlacommunity.nl/files/278344/mod_joomlaversions.zip)

**Comment by conconnl** [comment]
@n9iels Je bent goed bezig geweest.
Heb je hier een aparte GIT Repository van gemaakt, zodat mensen kunnen bijdragen?
Wil je dit anders als nog doen, ik denk dat meer mensen in de wereld deze wel willen gebruiken.

Tip1: Maak de en-GB taalbestanden ook even aan, denk dat dit een belangrijke basis is voor alle extensies. Ik werk meestal in het Engels en nu zie ik alleen taalstrings.
Tip2: De standaard URL staat ingesteld op HTTP i.p.v. HTTPS, in deze tegenwoordige wereld (internet) is HTTPS erg belangrijk.

**Comment by n9iels** [comment]
@conconnl Zeer goed idee! Ik heb een repository aangemaakt en jou suggesties erin verwerkt.
Deze is hier te vinden: https://github.com/n9iels/mod_joomlaversions/

Het is de eerste versie van de module, het toevoegen van een prefix zou bijvoorbeeld nog netter kunnen. Maar dat is wat voor een eventuele volgende versie :)

**Comment by hans2103** [comment]
@n9iels ik heb de module geinstalleerd, maar de output blijft leeg. 
Zou jij onderzoek kunnen plegen en oplossen?

**Comment by n9iels** [comment]
@hans2103 De ajax request wordt niet verstuurd omdat er javascript fouten zijn.
De console meld de volgende:
![image](https://cloud.githubusercontent.com/assets/2659866/15495111/664ac150-218e-11e6-85fe-0a6159fd1e2b.png)

De lijken te komen door RSComments en RSFiles. Als ik de system plugins van deze extensies uitschakel werkt alles gewoon.

**Comment by conconnl** [comment]
@n9iels @hans2103 kunnen jullie dan zoeken wat de daadwerkelijk fout is in deze plugins?
Dan kunnen we dit bespreken met RSJoomla! om het te laten oplossen, hier heeft elke gebruiker wat aan.
Ze hebben vanmorgen al een nieuwe RSComments! update voor uitgebracht vanwege andere foutmeldingen.
Deze ga ik zo bijwerken.

**Comment by hans2103** [comment]
De module mod_joomlaversions werkt indien de plugins RSComments en RSFiles uit staan. 
Ik heb de comment van @n9iels verplaatst naar een nieuwe issue #79
