### ISSUE TITLE
[Development] fout in RSComments en RSFiles zorgt voor falende mod_joomlaversions

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomlacommunity.nl#79]
In issue #76 heeft Niels een nieuwe module JoomlaVersions gemaakt. Deze toont de meest recente Joomla versie. Bij implementatie komen we er achter dat er iets mis gaat in RSComments en RSFiles, waardoor ook mod_joomlaversions Ajax call faalt. 

copy van https://github.com/stichtingsympathy/joomlacommunity.nl/issues/76#issuecomment-221183759
> @hans2103 De ajax request wordt niet verstuurd omdat er javascript fouten zijn.
De console meld de volgende:
> ![664ac150-218e-11e6-85fe-0a6159fd1e2b](https://cloud.githubusercontent.com/assets/639822/15495710/d84499b8-2191-11e6-9a30-e3f64b8eb9a7.png)
> De lijken te komen door RSComments en RSFiles. Als ik de system plugins van deze extensies uitschakel werkt alles gewoon.

Graag onderzoek en oplossen.

**Comment by conconnl** [comment]
@n9iels zo te zien gebruiken ze JRepsonse nog (Deprecated) voor wat ik begrijp moet JApplicationWeb gebruikt worden.
Kun jij in de plugins kijken of je het daarmee kan oplossen, als het dan allemaal werkt kan ik het doorzetten naar RSJoomla! en een update laten uitvoeren.

**Comment by hans2103** [comment]
Opgelost in #82
