### ISSUE TITLE
[Development] install Accelerated Mobile Pages

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomlacommunity.nl#80]
Yannick Gaultier heeft tijdens JandBeyond een presentatie gegeven over de implementatie van Accelerated Mobile Pages.
Deze plugin (reeds aangeschaft door @hans2103) installeren op de website.

**Comment by hans2103** [comment]
Extensie geïnstalleerd en gedeeltelijk geconfigureerd.
Resultaat is een AMP pagina

http://nieuw.joomlacommunity.eu/nieuws/evenementen/990-ticketverkoop-joomladagen-2015-van-start/amp

Behoeft nog wel enige styling. Maar... dat kan ook in versie 2
![screencapture-nieuw-joomlacommunity-eu-nieuws-evenementen-990-ticketverkoop-joomladagen-2015-van-start-amp-1464170696974](https://cloud.githubusercontent.com/assets/639822/15536277/ef6fe7d4-2270-11e6-947a-63494d2e2048.png)

**Comment by conconnl** [comment]
@hans2103 Goed bezig :+1:

**Comment by sanderpotjer** [comment]
Heb voor nu plugin even verwijderd om site schoon te houden met wat echt af & in gebruik is. Ook maar even wachten totdat Google in NL de AMP resultaten gaat tonen.
