### ISSUE TITLE
Akeeba Backup updaten zodra beschikbaar

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#81]
Er zijn momenteel problemen met alle 5.0.X versies van Akeeba Backup. Zie dit bericht op de website: https://www.akeebabackup.com/home/news/1667-bugs-in-akeeba-backup-50x-solo-backupwp-18x.html

Momenteel draaien wij 5.0.4, het lijkt me dus een goede zaak om zodra de stable uit is hier naartoe te updaten :)

**Comment by hans2103** [comment]
En voor nu? Downgraden naar 4.7.2?
Op do 26 mei 2016 om 09:26 schreef Niels van der Veer <
notifications@github.com>

**Comment by n9iels** [comment]
Dat lijkt niet mogelijk te zijn, https://twitter.com/Hotkeyharry/status/735477095317528576

**Comment by conconnl** [comment]
Lijkt me niet noodzakelijk. 
We draaien versie 4.7.2 op de site.

**Comment by n9iels** [comment]
Ik zie hier 5.0.4 staan
![image](https://cloud.githubusercontent.com/assets/2659866/15568192/d5a02566-232a-11e6-9470-7ff9da7b5020.png)

**Comment by conconnl** [comment]
Dat is niet de live site op dit moment. 
Dat is develop. Heb net op nieuw.jc gekeken daar staat binnen de extensie nog 4.7.2
Dan nog, we ontwikkelen lokaal en zetten dit daarna op de live site. 
Database backups worden als het goed is via Byte gedaan. Op dit moment verwacht ik geen probleem.

**Comment by n9iels** [comment]
oww wacht. We hebben natuurlijk een andere database voor de live dan voor de develop. No problem in dat geval idd :+1:
