### ISSUE TITLE
[Fase 1] - Uncaught ReferenceError: Joomla is not defined

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomlacommunity.nl#83]
Bij het laden van de pagina komt in de javascript console de volgende foutmelding:

```
nieuw.joomlacommunity.eu/:75 Uncaught ReferenceError: Joomla is not defined
```

Via view-source komt het volgende naar voren
```
73  <script type="text/javascript">
74    (function() {
75      Joomla.JText.load({"COM_RSCOMMENTS_NO_SUBSCRIBER_NAME":"De inschrijvernaam is leeg.","COM_RSCOMMENTS_NO_SUBSCRIBER_EMAIL":"De inschrijver e-mail adres is leeg.","COM_RSCOMMENTS_INVALID_SUBSCRIBER_EMAIL":"Vul een geldig e-mail adres in.","COM_RSCOMMENTS_REPORT_NO_REASON":"Vul een rapporteringsreden in.","COM_RSCOMMENTS_REPORT_INVALID_CAPTCHA":"Ongeldige captcha. Probeer opnieuw.","COM_RSCOMMENTS_HIDE_FORM":"Verberg reactieformulier","COM_RSCOMMENTS_SHOW_FORM":"Laat reactieformulier zien"});
76    })();
77  </script>
```

RSComments roept ```Joomla``` op. Hiervoor is mogelijk Mootools nodig.
We willen geen Mootools. blêh

@conconnl kan jij iets bij RSJoomla regelen dat dit opgelost wordt?

**Comment by conconnl** [comment]
@hans2103 sorry voor de late reactie.
Ik had RSJoomla! voor andere errors al gemaild.

Kun jij mij duidelijk omschrijven wat ik ze hierover moet sturen?
Of de eventuele oplossing als je die weet, hoe duidelijker de info des te sneller ze iets doen.

**Comment by n9iels** [comment]
Komen deze errors niet omdat o.a. core.js niet wordt ingeladen?

**Comment by n9iels** [comment]
De error wordt veroorzaak omdat we in de template core.js verwijderen uit de head. zie hier:
https://github.com/stichtingsympathy/joomlacommunity.nl/blob/develop/templates/jc/helpers/helper.php#L308

De logische oplossing lijkt me dus dit bestand wel in te laden. Als ik deze regel weg laat is de error ook weg, en Mootools wordt nog steeds niet ingeladen

**Comment by hvdmeer** [comment]
Net gecontroleerd, deze melding is er nog steeds. Is het voorstel van @n9iels de oplossing? 
Dan zijn we weer een klein stapje verder. :)

**Comment by n9iels** [comment]
@hans2103 wat denk jij hiervan? Een goede oplossing? Ik weet namelijk geen consequenties aan het toevoegen van core.js.

**Comment by hans2103** [comment]
prima voorstel
Zou je dat door kunen voeren @n9iels ?

**Comment by n9iels** [comment]
Geregeld

**Comment by hans2103** [comment]
Ik zie de error niet meer voorbij komen. Opgelost.

**Comment by hans2103** [comment]
Succesvol getest

**Comment by hans2103** [comment]
Kan succesvol reactie plaatsen
