### ISSUE TITLE
Social media icons & links in footer

### ISSUE THREAD

**Issue by sanderpotjer** [stichtingsympathy/joomlacommunity.nl#9]
De social accounts van JC plaatsen in de footer

**Comment by hvdmeer** [comment]
Is het een idee om LinkedIn wat meer te gebruiken voor de professionele uitingen?

**Comment by hans2103** [comment]
@sanderpotjer waar had je de lijst in gedachte?

Op de huidige site staat een lijstje met de volgende items:
Volg ons op:

- Facebook -> https://www.facebook.com/joomlacommunity/
- LinkedIn -> https://www.linkedin.com/groups/1857791
- Twitter -> https://twitter.com/joomlacommunity
- Flickr -> https://www.flickr.com/groups/joomlacommunity/pool/

Voorstel: een inline list achter de copyright notice, rechts uitgelijnd.

```
Volg ons op: Facebook - LinkedInd - Twitter - Flickr
```

**Comment by hvdmeer** [comment]
Zo, die laatste foto's op Flickr zijn alweer vijf jaar oud!

**Comment by conconnl** [comment]
@hans2103 ik zou het inderdaad doen zoals je voorstelt. Wellicht dan met Social Images erbij
