### ISSUE TITLE
installatie instructies

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomlacommunity.nl#90]
Tijdens de bbq is naar voren gekomen dat alle hulp bij de afronding van deze site gewenst is. 
Mijn collega organisator Arjan Abbink wil graag meehelpen, maar we komen niet uit de installatie instructies zoals genoemd in de _readme.md_

Kan de installatie instructie opgezet worden voor iemand die vanaf NULL begint. 
Bij voorkeur geschreven vanuit een MAC met MAMP Pro geïnstalleerd.

**Comment by n9iels** [comment]
Ha Hans,
Gaat het om het Git verhaal en opzetten in MAMP? Of meer over nodejs en net compileren van de LESS van de tempalte?

**Comment by hans2103** [comment]
wat moet Arjan Abbink (@arkomat) doen om aan de slag te kunnen. 
Dus dan is het denk ik een beschrijving van Git checkout en opzetten in MAMP.

**Comment by sanderpotjer** [comment]
@hans2103 voordat we hier veel tijd aan besteden, wat is daarna het doel als het lokaal draait? Want leuk als het draait, maar om dan weer bij te dragen moet men ook van pull-requests e.d. afweten, database changes etc... Mogelijk voer voor veel handleidingen dus. Als het puur om inrichting gaat en content plaatsen oid is lokaal draaien weer niet nodig en juist onhandig. Vandaar even de vraag :)

**Comment by hans2103** [comment]
@sanderpotjer ik heb begrepen van @arkomat dat hij ook mee wil helpen met code. 
Dus uitleg over  pull-requests en database changes etc... zal op den duur ook moeten komen denk ik.

**Comment by jissereitsma** [comment]
Ik heb al even wat extra opmerkingen toegevoegd: https://github.com/stichtingsympathy/joomlacommunity.nl/wiki/Aan-de-slag-met-GitHub

**Comment by conconnl** [comment]
Wiki kan bijgewerkt wanneer nodig.
Issue wordt voor nu gesloten.
