### ISSUE TITLE
[Development] Foutmelding op forum bij openen topic

### ISSUE THREAD

**Issue by hvdmeer** [stichtingsympathy/joomlacommunity.nl#91]
Bianca heeft gisteren een bericht op het forum geplaatst. Maar bij het openen van het topic krijg ik een foutmelding op mijn scherm. Dit is de link van het topic:
http://nieuw.joomlacommunity.eu/forum/recent/centreren-van-een-module-in-een-artikel

En dit is de foutmelding:
```
Fatal error: Class 'ES' not found in /home/users/jooomftp/nieuw.joomlacommunity.eu/administrator/components/com_easydiscuss/includes/post/post.php on line 6149
```

**Comment by n9iels** [comment]
ik krijg geen foutmelding bij mijn lokale installatie. Ik vermoed dat de live versie achter loop. @sanderpotjer kan de development versie uitrollen naar de live versie. Kijken of de error dan is opgelost :)

**Comment by sanderpotjer** [comment]
@n9iels laatste code staat nu uitgerold, maar fout is er nog steeds. Moeten er dus even verder in duiken :)

**Comment by n9iels** [comment]
Aha het ziet er naar uit dat de error enkel wordt weergeven als je ingelogd bent. Vandaar dat ik hem eerst niet zag denk ik. Op mijn development omgeving ben ik niet altijd ingelogd.

De live versie is ondertussen ook al weer achterhaald overigens haha, tja gaat hard met die commits :P

**Comment by hvdmeer** [comment]
Als ik op het forum zit en ik start Firebug zie ik de volgende melding. Heeft dit er toevallig mee te maken?

> categories:45 Uncaught ReferenceError: Joomla is not defined

**Comment by n9iels** [comment]
Die melding is een Javascript error. Hij probeert een Joomla! taalstring te vertalen, maar het script daarvoor kan die niet vinden. Is een bekend probleem.

Dat kan niet het probleem zijn. De error op het form is namelijk een PHP error :)

**Comment by hvdmeer** [comment]
Ik heb net gekeken en dit probleem is nog steeds online aanwezig.

**Comment by n9iels** [comment]
Er wordt hier een oplossing voor het probleem beschreven http://stackideas.com/forums/php-fatal-error-class-es-not-found-com_easydiscuss-not-show-post-after-login, en deze werkt.

Vind het alleen geen goede oplossing.
@conconnl of @sanderpotjer ik weet niet wie hem heeft, maar kan een van jullie EasyDiscuss opnieuw installeren? Zowel lokaal als op de live website krijg je een error als je een topic probeert te bekijken terwijl je bent ingelogd. Wellicht dat deze met een herinstallatie weg is :)

**Comment by MartijnMaandag** [comment]
Ik kan daar denk ik wel bij. Ik zal hem ophalen en daarna installeren.

**Comment by MartijnMaandag** [comment]
Ik heb in het beheergedeelte een update van EasyDiscuss gedaan. Nu werkt het raadplegen van de forumberichten weer

**Comment by hvdmeer** [comment]
Als iemand dit ook voor de versie op Github doet kan deze issue gesloten worden. :)

**Comment by conconnl** [comment]
Goed gezien @hvdmeer 
@MartijnMaandag stuur mij de installer maar, dan zorg ik dat het via de correcte manier in GitHub terecht komt, zodat de server daarna bijgewerkt kan worden.
Alle installaties en updates moeten we lokaal doen en via GitHub doorzetten.

**Comment by MartijnMaandag** [comment]
@conconnl dit is de installatie-zip van Easydiscuss 4.0.8
[com_easydiscuss_full_pro_4.0.8_joomla.zip](https://github.com/stichtingsympathy/joomlacommunity.nl/files/414792/com_easydiscuss_full_pro_4.0.8_joomla.zip)

**Comment by hans2103** [comment]
update verwerkt in commit 6d874a8f2b233006e7f346282700461b099fcab9

**Comment by hans2103** [comment]
@hvdmeer ik kan het issue niet meer reproduceren. Ik kan succesvol een forum topic openen.

**Comment by n9iels** [comment]
Gelukkig dat het weer werkt! Kunnen we ons eindelijk focussen op het belangrijkste gedeelte van de website :)

**Comment by hvdmeer** [comment]
Online en Github zijn dus bijgewerkt, dan kan de issue gesloten worden :lock:
