### ISSUE TITLE
[Structuur] Nieuws artikelen en verslagen opnieuw indelen

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#95]
De volgende dingen moeten nog gebeuren met de nieuws artikelen en verslagen
- [ ] Bepalen tot welke data we deze behouden (hebben we bijvoorbeeld nog een nieuws artikel  uit 2013 nodig?)
- [ ] De categorie "Algemeen" onder nieuws is nu nog leeg, er moet gekeken worden wat hieronder moet komen te staan
- [ ] Verslagen van gebruikersgroepen staan nu  nog onder de categorie "Verslagen", echter  hebben we een categorie voor verslagen van elke groep. Alle verslagen moeten dus naar de juiste categorie.

**Comment by MartijnMaandag** [comment]
Ik heb alle artikelen van voor 1-1-2016 op gearchiveerd gezet (lijkt me niet zinvol deze te handhaven).

**Comment by sanderpotjer** [comment]
@MartijnMaandag maar dan worden die op geen enkele manier meer ontsloten?

**Comment by MartijnMaandag** [comment]
Ik ben bang dat niemand dit terugleest (hoewel ik het zelf nog wel eens gebruik als ik een nieuw artikel schrijf en wil weten hoe we iets vroeger hebben gecommuniceerd). We kunnen ook een menu-item aanmaken met Archief en daar de oude zaken tonen (gearchiveerd)?

**Comment by sanderpotjer** [comment]
@MartijnMaandag dank. Maar wat is het bezwaar tegen de blog weergave zoals nu op de site het geval, archief zit dus gewoon in de paginering?

**Comment by MartijnMaandag** [comment]
Ik zelf vind paginering (waarbij er tientallen pagina's staan, met ieder x artikelen) niet gebruikersvriendelijk. Ik denk dan al gauw als er zoveel is kijk ik niet verder. Bij 2 of 3 pagina's ben ik eerder geneigd nog even verder te bladeren. Daarom apart Archief waar je bewust verder kunt kijken.

**Comment by sanderpotjer** [comment]
Sja, smaken kunnen denk ik verschillen. Want als ik op pagina 3 ben en dan net niet bij de datum ben waarnaar ik op zoek ben, dan naar een archief moet navigeren en daar weer gaan zoeken ipv naar p4 te gaan is dat weer minder gebruikersvriendelijk. 

Denk bijvoorbeeld aan nieuwscategorie Joomla releases. Dan kan ik niet door bladeren in categorie naar de geschiedenis kijken.

Als we archiveren is dat dan ook iets wat we met regelmaat moeten gaan doen.

**Comment by MartijnMaandag** [comment]
Van mij is het ook maar een mening ;-)
We moeten alles bij implementeren toch nog een keer overhalen, dan staat het weer gepubliceerd.
