### ISSUE TITLE
[Fase 1] - [Development] Foutmelding na inloggen

### ISSUE THREAD

**Issue by n9iels** [stichtingsympathy/joomlacommunity.nl#96]
Als je inlogt er vervolgens naar het menu item "Nieuws" gaat krijg je de volgende melding:
![image](https://cloud.githubusercontent.com/assets/2659866/17380167/1eec8062-59c6-11e6-97ea-82910743f017.png)
Zodra je de pagina een keer herlaad is deze weg

Geen idee waardoor deze wordt veroorzaakt....

**Comment by hvdmeer** [comment]
Ik krijg die melding niet hier

**Comment by n9iels** [comment]
Dat is vreemd, op de live site toont ie inderdaad niet. Opzich niet erg, want dan zal het dus wel meevallen :)

**Comment by hans2103** [comment]
Heb je lokaal je database bijgewerkt @n9iels ?

**Comment by n9iels** [comment]
Ik gebruik de remote database van Byte, dus valt weinig bij te werken

**Comment by conconnl** [comment]
Is je cache wel leeg lokaal?
Ik heb zowel lokaal als live nergens last van.

**Comment by conconnl** [comment]
Speelt dit probleem nog steeds?

**Comment by jissereitsma** [comment]
Ik heb dit ook net getest en ondervind zelf geen problemen.

**Comment by conconnl** [comment]
Aangezien andere hier geen last van hebben en @n9iels de ACL structuur pas heeft bijgewerkt, sluit ik deze ticket.
Indien het probleem er toch nog ergens is, kan deze altijd opnieuw geopend worden.
