### ISSUE TITLE
wijziging naam menuitem gebruikersgroepen naar bijeenkomsten

### ISSUE THREAD

**Issue by hans2103** [stichtingsympathy/joomlacommunity.nl#99]
suggestie:

http://nieuw.joomlacommunity.eu/gebruikersgroepen
zou ik graag gewijzigd willen zien in 
http://nieuw.joomlacommunity.eu/bijeenkomsten

Het is namelijk groter dan alleen gebruikersgroepen
Bij akkoord of afwijzing van discussie graag toevoegen aan #28 
"[Informatie] - Afspraken & Besluiten / To-Do - Gebruikersgroepen"

**Comment by conconnl** [comment]
Ik ben er voor. 
Zeker omdat de sub-pagina's al verdeelt zijn op soort bijeenkomst.

**Comment by sanderpotjer** [comment]
Ik twijfel, "Gebruikersgroepen" zijn namelijk wel een hele ingeburgerde term in de Joomlacommunity, maar aan de andere kant biedt "Bijeenkomsten" wel weer meer ruimte voor goed en compleet overzicht van alle bijeenkomsten die er rond Joomla zijn in NL & België :)

**Comment by MartijnMaandag** [comment]
Zoals Wilco zegt: De onderverdeling op de pagina splitst het verder uit. Je komt als je voor 'Bijeenkomsten' kiest op de JUG pagina (de belangrijkste bijeenkomst). Wat mij betreft dus Bijeenkomsten.

**Comment by BiancaCrown** [comment]
Hoi allemaal, bij deze ik ben het met Martijn en Wilco eens

*Met vriendelijke groet,*
*Bianca Crown*

BC Webdesign <http://www.zonderzorgonline.nl>
biancacrown@gmail.com
06-38208208
*Lid van:*
*Organisator:*



2016-08-09 10:56 GMT+02:00 Martijn Maandag <notifications@github.com>:

**Comment by crommie** [comment]
Ik kom er maar even in vallen hoor, maar eh... "Activiteiten"? (Ik twijfel daar zelf ook over maar ik wou het toch even suggereren)

**Comment by BiancaCrown** [comment]
Anja, ik snap dat jouw voorstel taal technisch mooier is, maar alle
submenu's net wat wilco zegt sluiten met bijeenkomsten mooi aan. Ik blijf
bij bijeenkomsten.

*Met vriendelijke groet,*
*Bianca Crown*

BC Webdesign <http://www.zonderzorgonline.nl>
biancacrown@gmail.com
06-38208208
*Lid van:*
*Organisator:*



2016-08-09 11:42 GMT+02:00 Anja de Crom <notifications@github.com>:

**Comment by conconnl** [comment]
Ik vraag me af of taaltechnisch activiteiten wel zou kloppen.
Activiteiten zijn in mijn ogen namelijk de dingen die je doet op een bijeenkomst en niet de bijeenkomst zelf.

Ik ga naar de bijeenkomst "Pizza, Bugs & Fun" en de activiteiten die ik daar doe is Bugs Testen, Plezier hebben en Pizza eten.

**Comment by crommie** [comment]
Ja jongens, ik twijfel niet voor niks natuurlijk :). Het klinkt alleen wat ehm... nou ja, actiever dan bijeenkomsten. En meer als iets waaraan je kunt deelnemen.

**Comment by n9iels** [comment]
Ik stem voor het idee van @crommie, activiteiten klinkt acties dan bijeenkomsten. Plus je zou kunnen zeggen dan een PBF, JUG en Joomla! Dagen ook activiteiten zijn die door de Joomla! Community worden georganiseerd. Het ligt vrij dicht bij elkaar :)

**Comment by hans2103** [comment]
Ergo... het huidige menu item "Gebruikersgroepen" kan vervangen worden door "Activiteiten"
Ik zal het verwerken in #28 
MOcht Edith (@Stitch123) als coördinator van de Gebruikersgroepen er niet mee eens zijn kunnen we het altijd nog terug draaien.

Hieruit vloeit dus voort dat het menu item plus alias aangepast moet worden.
Andere issues die hieruit voortkomen kunnen nieuw aangemaakt worden.
